# Code generated by `ubx sdk gen` from cloudflare_service. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ServiceConfig:
    # Identifier of a Cloudflare account.
    account_id: Any = None

@dataclasses.dataclass
class ServiceAttrs:
    # Identifier of a Cloudflare account.
    account_id: Any = None

Service = ubx.DataSourceBinding(
    wire_type="cloudflare_service",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
