// Code generated by `ubx sdk gen` from cloudflare_registrar_api_sandbox_extension_response_single. DO NOT EDIT.
package extension

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RegistrarApiSandboxExtensionResponseSingleConfig struct {
	Extension any
}

type RegistrarApiSandboxExtensionResponseSingleAttrs struct {
	// Identifier.
	AccountId any
	Extension any
}

var RegistrarApiSandboxExtensionResponseSingle = ubx.DataSourceBinding{
	WireType: "cloudflare_registrar_api_sandbox_extension_response_single",
	Fields: ubx.FieldMap{
		"Extension": ubx.FieldSpec{WireName: "extension"},
	},
}
