# Code generated by `ubx sdk gen` from cloudflare_iam_response_collection_accounts. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IamResponseCollectionAccounts_Result_ManagedBy:
    parent_org_id: Any = None
    parent_org_name: Any = None

@dataclasses.dataclass
class IamResponseCollectionAccounts_Result_Settings:
    abuse_contact_email: Any = None
    enforce_twofactor: Any = None

@dataclasses.dataclass
class IamResponseCollectionAccounts_Result:
    created_on: Any = None
    id: Any = None
    managed_by: Any = None
    name: Any = None
    settings: Any = None
    type: Any = None

@dataclasses.dataclass
class IamResponseCollectionAccountsConfig:
    # Direction to order results.
    direction: Any = None
    # Page number of paginated results.
    page: Any = None
    # Maximum number of results per page.
    per_page: Any = None

@dataclasses.dataclass
class IamResponseCollectionAccountsAttrs:
    # Direction to order results.
    direction: Any = None
    # Name of the account.
    name: Any = None
    # Page number of paginated results.
    page: Any = None
    # Maximum number of results per page.
    per_page: Any = None
    result: Any = None

IamResponseCollectionAccounts = ubx.DataSourceBinding(
    wire_type="cloudflare_iam_response_collection_accounts",
    fields={
        "direction": ubx.FieldSpec(wire_name="direction"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
