// Code generated by `ubx sdk gen` from cloudflare_schema. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Schema_Result_Input {
  additionalProperties: boolean | Computed<boolean>;
  description: string | Computed<string>;
  type: string | Computed<string>;
}

export interface Schema_Result {
  input: Schema_Result_Input | Computed<Schema_Result_Input>;
  output: Schema_Result_Input | Computed<Schema_Result_Input>;
}

export interface SchemaConfig {
  accountId: string | Computed<string>;
  /** Model Name */
  model: string | Computed<string>;
}

export interface SchemaAttrs {
  accountId: string;
  /** Model Name */
  model: string;
  result: Schema_Result;
  success: boolean;
}

export const Schema: DataSourceBinding<SchemaConfig, SchemaAttrs> = {
  wireType: "cloudflare_schema",
  fields: {
    accountId: "account_id",
    model: "model",
  },
};
