# Code generated by `ubx sdk gen` from cloudflare_overall. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Overall_Data:
    # Count of total livestreams.
    count: Any = None
    # Total time duration for which the input was given or the meeting was streamed.
    total_ingest_seconds: Any = None
    # Total view time for which the viewers watched the stream.
    total_viewer_seconds: Any = None

@dataclasses.dataclass
class OverallConfig:
    # The account identifier tag.
    account_id: Any = None
    # The app identifier tag.
    app_id: Any = None
    end_time: Any = None
    filters: Any = None
    start_time: Any = None

@dataclasses.dataclass
class OverallAttrs:
    # The account identifier tag.
    account_id: Any = None
    # The app identifier tag.
    app_id: Any = None
    data: Any = None
    end_time: Any = None
    filters: Any = None
    start_time: Any = None
    success: Any = None

Overall = ubx.DataSourceBinding(
    wire_type="cloudflare_overall",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "app_id": ubx.FieldSpec(wire_name="app_id"),
        "end_time": ubx.FieldSpec(wire_name="end_time"),
        "filters": ubx.FieldSpec(wire_name="filters"),
        "start_time": ubx.FieldSpec(wire_name="start_time"),
    },
)
