# Code generated by `ubx sdk gen` from cloudflare_resource_sharing_share_resource_response_single. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ShareResourceResponseSingle_Errors:
    code: Any = None
    message: Any = None

@dataclasses.dataclass
class ShareResourceResponseSingle_Result:
    # When the share was created.
    created: Any = None
    # Share Resource identifier.
    id: Any = None
    # Resource Metadata.
    meta: Any = None
    # When the share was modified.
    modified: Any = None
    # Account identifier.
    resource_account_id: Any = None
    # Share Resource identifier.
    resource_id: Any = None
    # Resource Type.
    resource_type: Any = None
    # Resource Version.
    resource_version: Any = None
    # Resource Status.
    status: Any = None

@dataclasses.dataclass
class ShareResourceResponseSingleConfig:
    # Resource Metadata.
    meta: Any = None
    # Account identifier.
    resource_account_id: Any = None
    # Share Resource identifier.
    resource_id: Any = None
    # Resource Type.
    resource_type: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    share_id: Any = None
    # path parameter, not part of the API's own resource representation
    share_resource_id: Any = None

@dataclasses.dataclass
class ShareResourceResponseSingleAttrs:
    # Errors returned by the API call, empty when the call succeeds. (AI-inferred)
    errors: Any = None
    # Resource Metadata.
    meta: Any = None
    # Account identifier.
    resource_account_id: Any = None
    # Share Resource identifier.
    resource_id: Any = None
    # Resource Type.
    resource_type: Any = None
    result: Any = None
    # Whether the API call was successful.
    success: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    share_id: Any = None
    # path parameter, not part of the API's own resource representation
    share_resource_id: Any = None

ShareResourceResponseSingle = ubx.ResourceBinding(
    wire_type="cloudflare_resource_sharing_share_resource_response_single",
    fields={
        "meta": ubx.FieldSpec(wire_name="meta"),
        "resource_account_id": ubx.FieldSpec(wire_name="resource_account_id"),
        "resource_id": ubx.FieldSpec(wire_name="resource_id"),
        "resource_type": ubx.FieldSpec(wire_name="resource_type"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "share_id": ubx.FieldSpec(wire_name="share_id"),
        "share_resource_id": ubx.FieldSpec(wire_name="share_resource_id"),
    },
)
