# Code generated by `ubx sdk gen` from cloudflare_pipeline. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Pipeline_Result_Tables:
    id: Any = None
    latest: Any = None
    name: Any = None
    type: Any = None
    version: Any = None

@dataclasses.dataclass
class Pipeline_Result:
    created_at: Any = None
    # Indicates the reason for the failure of the Pipeline.
    failure_reason: Any = None
    # Indicates a unique identifier for this pipeline.
    id: Any = None
    modified_at: Any = None
    # Indicates the name of the Pipeline.
    name: Any = None
    # Specifies SQL for the Pipeline processing flow.
    sql: Any = None
    # Indicates the current status of the Pipeline.
    status: Any = None
    # List of streams and sinks used by this pipeline.
    tables: Any = None

@dataclasses.dataclass
class PipelineConfig:
    # Specifies the name of the Pipeline.
    name: Any = None
    # Specifies SQL for the Pipeline processing flow.
    sql: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    pipeline_id: Any = None

@dataclasses.dataclass
class PipelineAttrs:
    # Specifies the name of the Pipeline.
    name: Any = None
    result: Any = None
    # Specifies SQL for the Pipeline processing flow.
    sql: Any = None
    # Indicates whether the API call was successful.
    success: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    pipeline_id: Any = None

Pipeline = ubx.ResourceBinding(
    wire_type="cloudflare_pipeline",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "sql": ubx.FieldSpec(wire_name="sql"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "pipeline_id": ubx.FieldSpec(wire_name="pipeline_id"),
    },
)
