# Code generated by `ubx sdk gen` from cloudflare_dnssec_e2e. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DnssecE2e_Result_Meta_ConfidenceInfo_Annotations:
    data_source: Any = None
    description: Any = None
    end_date: Any = None
    event_type: Any = None
    is_instantaneous: Any = None
    linked_url: Any = None
    start_date: Any = None
    tags: Any = None

@dataclasses.dataclass
class DnssecE2e_Result_Meta_ConfidenceInfo:
    annotations: Any = None
    # Provides an indication of how much confidence Cloudflare has in the data.
    level: Any = None

@dataclasses.dataclass
class DnssecE2e_Result_Meta_DateRange:
    end_time: Any = None
    start_time: Any = None

@dataclasses.dataclass
class DnssecE2e_Result_Meta_Units:
    name: Any = None
    value: Any = None

@dataclasses.dataclass
class DnssecE2e_Result_Meta:
    confidence_info: Any = None
    date_range: Any = None
    # Timestamp of the last dataset update.
    last_updated: Any = None
    # Normalization method applied to the results. Refer to [Normalization methods](https://developers.cloudflare.com/radar/concepts/normalization/).
    normalization: Any = None
    # Measurement units for the results.
    units: Any = None

@dataclasses.dataclass
class DnssecE2e_Result_Summary0:
    # A numeric string.
    negative: Any = None
    # A numeric string.
    positive: Any = None

@dataclasses.dataclass
class DnssecE2e_Result:
    # Metadata for the results.
    meta: Any = None
    summary_0: Any = None

@dataclasses.dataclass
class DnssecE2eConfig:
    # Filters results by Autonomous System. Specify one or more Autonomous System Numbers (ASNs) as a comma-separated list. Prefix with `-` to exclude ASNs from results. For example, `-174, 3356` excludes results from AS174, but includes results from AS3356.
    asn: Any = None
    # Filters results by continent. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude continents from results. For example, `-EU,NA` excludes results from EU, but includes results from NA.
    continent: Any = None
    # End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected.
    date_end: Any = None
    # Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters).
    date_range: Any = None
    # Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected.
    date_start: Any = None
    # Format in which results will be returned.
    format: Any = None
    # Filters results by location. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude locations from results. For example, `-US,PT` excludes results from the US, but includes results from PT.
    location: Any = None
    # Array of names used to label the series in the response.
    name: Any = None
    # Specifies whether the response includes empty DNS responses (NODATA).
    nodata: Any = None
    # Filters results by DNS transport protocol.
    protocol: Any = None
    # Filters results by DNS query type.
    query_type: Any = None
    # Filters results by DNS response code.
    response_code: Any = None
    # Filters results by top-level domain. Incompatible with the `ipVersion`, `protocol`, `dnssecE2e`, `dnssecAware`, `responseTtl`, and `cacheHit` filters/dimensions; this restriction does not apply to country-code TLDs (2-letter, e.g. `uk`).
    tld: Any = None

@dataclasses.dataclass
class DnssecE2eAttrs:
    # Filters results by Autonomous System. Specify one or more Autonomous System Numbers (ASNs) as a comma-separated list. Prefix with `-` to exclude ASNs from results. For example, `-174, 3356` excludes results from AS174, but includes results from AS3356.
    asn: Any = None
    # Filters results by continent. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude continents from results. For example, `-EU,NA` excludes results from EU, but includes results from NA.
    continent: Any = None
    # End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected.
    date_end: Any = None
    # Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters).
    date_range: Any = None
    # Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected.
    date_start: Any = None
    # Format in which results will be returned.
    format: Any = None
    # Filters results by location. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude locations from results. For example, `-US,PT` excludes results from the US, but includes results from PT.
    location: Any = None
    # Array of names used to label the series in the response.
    name: Any = None
    # Specifies whether the response includes empty DNS responses (NODATA).
    nodata: Any = None
    # Filters results by DNS transport protocol.
    protocol: Any = None
    # Filters results by DNS query type.
    query_type: Any = None
    # Filters results by DNS response code.
    response_code: Any = None
    result: Any = None
    success: Any = None
    # Filters results by top-level domain. Incompatible with the `ipVersion`, `protocol`, `dnssecE2e`, `dnssecAware`, `responseTtl`, and `cacheHit` filters/dimensions; this restriction does not apply to country-code TLDs (2-letter, e.g. `uk`).
    tld: Any = None

DnssecE2e = ubx.DataSourceBinding(
    wire_type="cloudflare_dnssec_e2e",
    fields={
        "asn": ubx.FieldSpec(wire_name="asn"),
        "continent": ubx.FieldSpec(wire_name="continent"),
        "date_end": ubx.FieldSpec(wire_name="date_end"),
        "date_range": ubx.FieldSpec(wire_name="date_range"),
        "date_start": ubx.FieldSpec(wire_name="date_start"),
        "format": ubx.FieldSpec(wire_name="format"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "nodata": ubx.FieldSpec(wire_name="nodata"),
        "protocol": ubx.FieldSpec(wire_name="protocol"),
        "query_type": ubx.FieldSpec(wire_name="query_type"),
        "response_code": ubx.FieldSpec(wire_name="response_code"),
        "tld": ubx.FieldSpec(wire_name="tld"),
    },
)
