// Code generated by `ubx sdk gen` from cloudflare_access_response_collection_3. DO NOT EDIT.
package accessservicetokens

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AccessResponseCollection3Config struct {
	// Identifier.
	AccountId any
	// The name of the service token.
	Name any
	// Page number of results.
	Page any
	// Number of results per page.
	PerPage any
	// Search for service tokens by other listed query parameters.
	Search any
}

type AccessResponseCollection3Attrs struct {
	// Identifier.
	AccountId any
	// The name of the service token.
	Name any
	// Page number of results.
	Page any
	// Number of results per page.
	PerPage any
	// Search for service tokens by other listed query parameters.
	Search any
}

var AccessResponseCollection3 = ubx.DataSourceBinding{
	WireType: "cloudflare_access_response_collection_3",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"Search": ubx.FieldSpec{WireName: "search"},
	},
}
