// Code generated by `ubx sdk gen` from cloudflare_iam_sso_connector_collection_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IamSsoConnectorCollectionResponse_AccountId {
}

export interface IamSsoConnectorCollectionResponse_Result_Verification {
  code?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface IamSsoConnectorCollectionResponse_Result {
  createdOn?: string | Computed<string>;
  emailDomain?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  id?: IamSsoConnectorCollectionResponse_AccountId | Computed<IamSsoConnectorCollectionResponse_AccountId>;
  updatedOn?: string | Computed<string>;
  useFedrampLanguage?: boolean | Computed<boolean>;
  verification?: IamSsoConnectorCollectionResponse_Result_Verification | Computed<IamSsoConnectorCollectionResponse_Result_Verification>;
}

const IamSsoConnectorCollectionResponse_AccountIdFields: FieldMap = {
};

export interface IamSsoConnectorCollectionResponseConfig {
  /** Account identifier tag. */
  accountId: IamSsoConnectorCollectionResponse_AccountId | Computed<IamSsoConnectorCollectionResponse_AccountId>;
}

export interface IamSsoConnectorCollectionResponseAttrs {
  /** Account identifier tag. */
  accountId: IamSsoConnectorCollectionResponse_AccountId;
  result: IamSsoConnectorCollectionResponse_Result[];
}

export const IamSsoConnectorCollectionResponse: DataSourceBinding<IamSsoConnectorCollectionResponseConfig, IamSsoConnectorCollectionResponseAttrs> = {
  wireType: "cloudflare_iam_sso_connector_collection_response",
  fields: {
    accountId: {
      wireName: "account_id",
      kind: "object",
      fields: IamSsoConnectorCollectionResponse_AccountIdFields,
    },
  },
};
