// Code generated by `ubx sdk gen` from cloudflare_zero_trust_gateway_response_collection_4. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ZeroTrustGatewayResponseCollection4_Result {
  createdAt?: string | Computed<string>;
  data?: unknown | Computed<unknown>;
  id?: string | Computed<string>;
  operationType?: string | Computed<string>;
  processingError?: string | Computed<string>;
  result?: string | Computed<string>;
  status?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface ZeroTrustGatewayResponseCollection4Config {
  /** Provide the identifier string. */
  accountId: string | Computed<string>;
}

export interface ZeroTrustGatewayResponseCollection4Attrs {
  /** Provide the identifier string. */
  accountId: string;
  result: ZeroTrustGatewayResponseCollection4_Result[];
}

export const ZeroTrustGatewayResponseCollection4: DataSourceBinding<ZeroTrustGatewayResponseCollection4Config, ZeroTrustGatewayResponseCollection4Attrs> = {
  wireType: "cloudflare_zero_trust_gateway_response_collection_4",
  fields: {
    accountId: "account_id",
  },
};
