# Code generated by `ubx sdk gen` from cloudflare_addressing_response_collection_3. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AddressingResponseCollection3Config:
    # Identifier of a Cloudflare account.
    account_id: Any = None

@dataclasses.dataclass
class AddressingResponseCollection3Attrs:
    # Identifier of a Cloudflare account.
    account_id: Any = None

AddressingResponseCollection3 = ubx.DataSourceBinding(
    wire_type="cloudflare_addressing_response_collection_3",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
