// Code generated by `ubx sdk gen` from cloudflare_account_mapping. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AccountMappingConfig {
  accountId: string | Computed<string>;
}

export interface AccountMappingAttrs {
  accountId: string;
}

export const AccountMapping: DataSourceBinding<AccountMappingConfig, AccountMappingAttrs> = {
  wireType: "cloudflare_account_mapping",
  fields: {
    accountId: "account_id",
  },
};
