// Code generated by `ubx sdk gen` from cloudflare_pipeline. DO NOT EDIT.
package workerspipelinesother

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Pipeline_Result_Tables struct {
	Id      any
	Latest  any
	Name    any
	Type    any
	Version any
}

type Pipeline_Result struct {
	CreatedAt any
	// Indicates the reason for the failure of the Pipeline.
	FailureReason any
	// Indicates a unique identifier for this pipeline.
	Id         any
	ModifiedAt any
	// Indicates the name of the Pipeline.
	Name any
	// Specifies SQL for the Pipeline processing flow.
	Sql any
	// Indicates the current status of the Pipeline.
	Status any
	// List of streams and sinks used by this pipeline.
	Tables any
}

type PipelineConfig struct {
	// Specifies the name of the Pipeline.
	Name any
	// Specifies SQL for the Pipeline processing flow.
	Sql any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	PipelineId any
}

type PipelineAttrs struct {
	// Specifies the name of the Pipeline.
	Name any
	// The requested resource or collection of resources. (AI-inferred)
	Result any
	// Specifies SQL for the Pipeline processing flow.
	Sql any
	// Indicates whether the API call was successful.
	Success any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	PipelineId any
}

var Pipeline = ubx.ResourceBinding{
	WireType: "cloudflare_pipeline",
	Fields: ubx.FieldMap{
		"Name":       ubx.FieldSpec{WireName: "name"},
		"Sql":        ubx.FieldSpec{WireName: "sql"},
		"AccountId":  ubx.FieldSpec{WireName: "account_id"},
		"PipelineId": ubx.FieldSpec{WireName: "pipeline_id"},
	},
}
