# Code generated by `ubx sdk gen` from cloudflare_tls_certificates_and_hostnames_ssl_universal_settings_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TlsCertificatesAndHostnamesSslUniversalSettingsResponseConfig:
    # Identifier.
    zone_id: Any = None

@dataclasses.dataclass
class TlsCertificatesAndHostnamesSslUniversalSettingsResponseAttrs:
    # Identifier.
    zone_id: Any = None

TlsCertificatesAndHostnamesSslUniversalSettingsResponse = ubx.DataSourceBinding(
    wire_type="cloudflare_tls_certificates_and_hostnames_ssl_universal_settings_response",
    fields={
        "zone_id": ubx.FieldSpec(wire_name="zone_id"),
    },
)
