// Code generated by `ubx sdk gen` from cloudflare_posture_api_paginated_finding_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface PostureApiPaginatedFindingListConfig {
  accountId: string | Computed<string>;
  cursor?: string | Computed<string>;
  direction?: string | Computed<string>;
  findingTypeIds?: string | Computed<string>;
  ignored?: boolean | Computed<boolean>;
  integrationId?: string | Computed<string>;
  maxAfflictionDate?: string | Computed<string>;
  minAfflictionDate?: string | Computed<string>;
  observation?: string | Computed<string>;
  order?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  product?: string | Computed<string>;
  search?: string | Computed<string>;
  severity?: string | Computed<string>;
  type?: string | Computed<string>;
  /** Supported vendor types for integrations. */
  vendor?: string | Computed<string>;
}

export interface PostureApiPaginatedFindingListAttrs {
  accountId: string;
  cursor: string;
  direction: string;
  findingTypeIds: string;
  ignored: boolean;
  integrationId: string;
  maxAfflictionDate: string;
  minAfflictionDate: string;
  observation: string;
  order: string;
  page: number;
  perPage: number;
  product: string;
  search: string;
  severity: string;
  type: string;
  /** Supported vendor types for integrations. */
  vendor: string;
}

export const PostureApiPaginatedFindingList: DataSourceBinding<PostureApiPaginatedFindingListConfig, PostureApiPaginatedFindingListAttrs> = {
  wireType: "cloudflare_posture_api_paginated_finding_list",
  fields: {
    accountId: "account_id",
    cursor: "cursor",
    direction: "direction",
    findingTypeIds: "finding_type_ids",
    ignored: "ignored",
    integrationId: "integration_id",
    maxAfflictionDate: "max_affliction_date",
    minAfflictionDate: "min_affliction_date",
    observation: "observation",
    order: "order",
    page: "page",
    perPage: "per_page",
    product: "product",
    search: "search",
    severity: "severity",
    type: "type",
    vendor: "vendor",
  },
};
