// Code generated by `ubx sdk gen` from cloudflare_cloudforce_one_rule_approvals_list_response. DO NOT EDIT.
package approvals

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudforceOneRuleApprovalsListResponse_Approvals_ProposedChanges struct {
	Content          any
	CreatedAt        any
	CreatedBy        any
	Description      any
	Enabled          any
	Id               any
	IsPublic         any
	Name             any
	Namespaces       any
	Path             any
	StructuredSource any
	SyncMessage      any
	SyncSource       any
	Type             any
}

type CloudforceOneRuleApprovalsListResponse_Approvals struct {
	AuditLogId             any
	CanReview              any
	CancelledAt            any
	CancelledBy            any
	ChangeDescription      any
	ChangeType             any
	CommitMessage          any
	Id                     any
	ProposedChanges        any
	RejectionReason        any
	RequestedAt            any
	RequestedBy            any
	ReviewedAt             any
	ReviewerScope          any
	RevisionNumber         any
	RuleId                 any
	RuleName               any
	Status                 any
	SupersededByApprovalId any
	SupersedesApprovalId   any
}

type CloudforceOneRuleApprovalsListResponseConfig struct {
	AccountId any
	// Limits approvals to the specified mutation type.
	ChangeType any
	// When true, returns the newest revision in each approval chain.
	LatestOnly any
	Limit      any
	Offset     any
	// Limits approvals to the specified reviewer scope.
	ReviewerScope any
	// Filter approvals by rule ID.
	RuleId any
	// Selects approval statuses. Repeat the parameter to OR-match statuses (for example, status=pending&status=rejected). Use status=all alone to disable status filtering.
	Status any
}

type CloudforceOneRuleApprovalsListResponseAttrs struct {
	AccountId any
	Approvals any
	// Limits approvals to the specified mutation type.
	ChangeType any
	// When true, returns the newest revision in each approval chain.
	LatestOnly any
	Limit      any
	Offset     any
	// Limits approvals to the specified reviewer scope.
	ReviewerScope any
	// Filter approvals by rule ID.
	RuleId any
	// Selects approval statuses. Repeat the parameter to OR-match statuses (for example, status=pending&status=rejected). Use status=all alone to disable status filtering.
	Status any
	Total  any
}

var CloudforceOneRuleApprovalsListResponse = ubx.DataSourceBinding{
	WireType: "cloudflare_cloudforce_one_rule_approvals_list_response",
	Fields: ubx.FieldMap{
		"AccountId":     ubx.FieldSpec{WireName: "account_id"},
		"ChangeType":    ubx.FieldSpec{WireName: "change_type"},
		"LatestOnly":    ubx.FieldSpec{WireName: "latest_only"},
		"Limit":         ubx.FieldSpec{WireName: "limit"},
		"Offset":        ubx.FieldSpec{WireName: "offset"},
		"ReviewerScope": ubx.FieldSpec{WireName: "reviewer_scope"},
		"RuleId":        ubx.FieldSpec{WireName: "rule_id"},
		"Status":        ubx.FieldSpec{WireName: "status"},
	},
}
