// Code generated by `ubx sdk gen` from cloudflare_pay_per_crawl_get_terms_signature_link_response. DO NOT EDIT.
package ppcterms

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PayPerCrawlGetTermsSignatureLinkResponse_Errors_ErrorChain struct {
}

type PayPerCrawlGetTermsSignatureLinkResponse_Errors_Source struct {
	Parameter any
	ParameterValueIndex any
	Pointer any
}

type PayPerCrawlGetTermsSignatureLinkResponse_Errors struct {
	Code any
	DocumentationUrl any
	ErrorChain any
	Message any
	Meta any
	Source any
}

type PayPerCrawlGetTermsSignatureLinkResponse_Result struct {
	Link any
}

type PayPerCrawlGetTermsSignatureLinkResponse_ResultInfo struct {
	Count any
	Page any
	PerPage any
	TotalCount any
	// TotalPages is a pointer so that if TotalPages == 0 we return that there are indeed 0 pages. omitempty would have removed the field otherwise. This is important as a customer may be relying on always reading this property and it should not be absent just because it is 0, only absent if a value is never provided.
	TotalPages any
}

type PayPerCrawlGetTermsSignatureLinkResponseConfig struct {
	AccountId any
}

type PayPerCrawlGetTermsSignatureLinkResponseAttrs struct {
	AccountId any
	Errors any
	Messages any
	Result any
	ResultInfo any
	Success any
}

var PayPerCrawlGetTermsSignatureLinkResponse = ubx.DataSourceBinding{
	WireType: "cloudflare_pay_per_crawl_get_terms_signature_link_response",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
