// Code generated by `ubx sdk gen` from cloudflare_stream_live_input_response_single. DO NOT EDIT.
package streamliveinputs

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type StreamLiveInputResponseSingle_Recording struct {
	// Lists the origins allowed to display videos created with this input. Enter allowed origin domains in an array and use `*` for wildcard subdomains. An empty array allows videos to be viewed on any origin.
	AllowedOrigins any
	// Disables reporting the number of live viewers when this property is set to `true`.
	HideLiveViewerCount any
	// Specifies the recording behavior for the live input. Set this value to `off` to prevent a recording. Set the value to `automatic` to begin a recording and transition to on-demand after Stream Live stops receiving input.
	Mode any
	// Indicates if a video using the live input has the `requireSignedURLs` property set. Also enforces access controls on any video recording of the livestream with the live input.
	RequireSignedUrls any
	// Determines the amount of time a live input configured in `automatic` mode should wait before a recording transitions from live to on-demand. `0` is recommended for most use cases and indicates the platform default should be used.
	TimeoutSeconds any
}

var StreamLiveInputResponseSingle_RecordingFields = ubx.FieldMap{
		"AllowedOrigins": ubx.FieldSpec{WireName: "allowed_origins"},
		"HideLiveViewerCount": ubx.FieldSpec{WireName: "hide_live_viewer_count"},
		"Mode": ubx.FieldSpec{WireName: "mode"},
		"RequireSignedUrls": ubx.FieldSpec{WireName: "require_signed_urls"},
		"TimeoutSeconds": ubx.FieldSpec{WireName: "timeout_seconds"},
	}

type StreamLiveInputResponseSingleConfig struct {
	// Sets the creator ID asssociated with this live input.
	DefaultCreator any
	// Indicates the number of days after which the live inputs recordings will be deleted. When a stream completes and the recording is ready, the value is used to calculate a scheduled deletion date for that recording. Omit the field to indicate no change, or include with a `null` value to remove an existing scheduled deletion.
	DeleteRecordingAfterDays any
	// Indicates whether the live input is enabled and can accept streams.
	Enabled any
	// A user modifiable key-value store used to reference other systems of record for managing live inputs.
	Meta any
	// When enabled, the live stream is delivered using Low-Latency HLS (LL-HLS), reducing glass-to-glass latency for viewers at the cost of reduced player compatibility.
	PreferLowLatency any
	// Records the input to a Cloudflare Stream video. Behavior depends on the mode. In most cases, the video will initially be viewable as a live video and transition to on-demand after a condition is satisfied.
	Recording any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	LiveInputIdentifier any
}

type StreamLiveInputResponseSingleAttrs struct {
	// Sets the creator ID asssociated with this live input.
	DefaultCreator any
	// Indicates the number of days after which the live inputs recordings will be deleted. When a stream completes and the recording is ready, the value is used to calculate a scheduled deletion date for that recording. Omit the field to indicate no change, or include with a `null` value to remove an existing scheduled deletion.
	DeleteRecordingAfterDays any
	// Indicates whether the live input is enabled and can accept streams.
	Enabled any
	// A user modifiable key-value store used to reference other systems of record for managing live inputs.
	Meta any
	// When enabled, the live stream is delivered using Low-Latency HLS (LL-HLS), reducing glass-to-glass latency for viewers at the cost of reduced player compatibility.
	PreferLowLatency any
	// Records the input to a Cloudflare Stream video. Behavior depends on the mode. In most cases, the video will initially be viewable as a live video and transition to on-demand after a condition is satisfied.
	Recording any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	LiveInputIdentifier any
}

var StreamLiveInputResponseSingle = ubx.ResourceBinding{
	WireType: "cloudflare_stream_live_input_response_single",
	Fields: ubx.FieldMap{
		"DefaultCreator": ubx.FieldSpec{WireName: "default_creator"},
		"DeleteRecordingAfterDays": ubx.FieldSpec{WireName: "delete_recording_after_days"},
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"Meta": ubx.FieldSpec{WireName: "meta"},
		"PreferLowLatency": ubx.FieldSpec{WireName: "prefer_low_latency"},
		"Recording": ubx.FieldSpec{
			WireName: "recording",
			Kind: "object",
			Fields: StreamLiveInputResponseSingle_RecordingFields,
		},
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"LiveInputIdentifier": ubx.FieldSpec{WireName: "live_input_identifier"},
	},
}
