// Code generated by `ubx sdk gen` from cloudflare_level. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Level_Result {
  createdAt: string | Computed<string>;
  description?: string | Computed<string>;
  id: string | Computed<string>;
  name: string | Computed<string>;
  updatedAt: string | Computed<string>;
}

export interface LevelConfig {
  description?: string | Computed<string>;
  name: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  sensitivityGroupId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  sensitivityLevelId: string | Computed<string>;
}

export interface LevelAttrs {
  description: string;
  name: string;
  result: Level_Result;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  sensitivityGroupId: string;
  /** path parameter, not part of the API's own resource representation */
  sensitivityLevelId: string;
}

export const Level: ResourceBinding<LevelConfig, LevelAttrs> = {
  wireType: "cloudflare_level",
  fields: {
    description: "description",
    name: "name",
    accountId: "account_id",
    sensitivityGroupId: "sensitivity_group_id",
    sensitivityLevelId: "sensitivity_level_id",
  },
};
