// Code generated by `ubx sdk gen` from cloudflare_transformation. DO NOT EDIT.
package accountsettings

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Transformation_Errors struct {
	Code    any
	Message any
}

type Transformation_Result struct {
	CfZoneTag  any
	Editable   any
	Id         any
	ModifiedOn any
	Value      any
}

type TransformationConfig struct {
	// Identifier.
	AccountId any
}

type TransformationAttrs struct {
	// Identifier.
	AccountId any
	Errors    any
	Messages  any
	Result    any
	// Whether the API call was successful.
	Success any
}

var Transformation = ubx.DataSourceBinding{
	WireType: "cloudflare_transformation",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
