# Code generated by `ubx sdk gen` from cloudflare_waf_product_api_bundle_response_custom_detection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WafProductApiBundleResponseCustomDetection_Id:
    pass

@dataclasses.dataclass
class WafProductApiBundleResponseCustomDetection_Result:
    # Defines the unique ID for this custom detection.
    id: Any = None
    # Defines ehe ruleset expression to use in matching the password in a request.
    password: Any = None
    # Defines the ruleset expression to use in matching the username in a request.
    username: Any = None

_WafProductApiBundleResponseCustomDetection_IdFields = {
}

@dataclasses.dataclass
class WafProductApiBundleResponseCustomDetectionConfig:
    # Defines the unique ID for this custom detection.
    id: Any = None
    # Defines ehe ruleset expression to use in matching the password in a request.
    password: Any = None
    # Defines the ruleset expression to use in matching the username in a request.
    username: Any = None
    # path parameter, not part of the API's own resource representation
    zone_id: Any = None
    # path parameter, not part of the API's own resource representation
    detection_id: Any = None

@dataclasses.dataclass
class WafProductApiBundleResponseCustomDetectionAttrs:
    # Defines the unique ID for this custom detection.
    id: Any = None
    # Defines ehe ruleset expression to use in matching the password in a request.
    password: Any = None
    # Defines a custom set of username/password expressions to match Leaked Credential Checks on.
    result: Any = None
    # Defines the ruleset expression to use in matching the username in a request.
    username: Any = None
    # path parameter, not part of the API's own resource representation
    zone_id: Any = None
    # path parameter, not part of the API's own resource representation
    detection_id: Any = None

WafProductApiBundleResponseCustomDetection = ubx.ResourceBinding(
    wire_type="cloudflare_waf_product_api_bundle_response_custom_detection",
    fields={
        "id": ubx.FieldSpec(
            wire_name="id",
            kind="object",
            fields=_WafProductApiBundleResponseCustomDetection_IdFields,
        ),
        "password": ubx.FieldSpec(wire_name="password"),
        "username": ubx.FieldSpec(wire_name="username"),
        "zone_id": ubx.FieldSpec(wire_name="zone_id"),
        "detection_id": ubx.FieldSpec(wire_name="detection_id"),
    },
)
