// Code generated by `ubx sdk gen` from cloudflare_query. DO NOT EDIT.
package event

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type QueryConfig struct {
	// Enable alerts for this query
	AlertEnabled any
	// Enable alert rollup for this query
	AlertRollupEnabled any
	// Unique name for the saved query
	Name any
	// JSON string containing the query parameters
	QueryJson any
	// Enable rule for this query
	RuleEnabled any
	// Scope for the rule
	RuleScope any
	// path parameter, not part of the API's own resource representation
	QueryId any
}

type QueryAttrs struct {
	// Account ID
	AccountId any
	// Enable alerts for this query
	AlertEnabled any
	// Enable alert rollup for this query
	AlertRollupEnabled any
	// Creation timestamp
	CreatedAt any
	// Intel Indicator Feed ID (numeric)
	CustomThreatFeedId any
	// Unique identifier for the saved query
	Id any
	// Unique name for the saved query
	Name any
	// JSON string containing the query parameters
	QueryJson any
	// Enable rule for this query
	RuleEnabled any
	// WAF rules list ID for blocking
	RuleListId any
	// Scope for the rule
	RuleScope any
	// Last update timestamp
	UpdatedAt any
	// Email of the user who created the query
	UserEmail any
	// path parameter, not part of the API's own resource representation
	QueryId any
}

var Query = ubx.ResourceBinding{
	WireType: "cloudflare_query",
	Fields: ubx.FieldMap{
		"AlertEnabled":       ubx.FieldSpec{WireName: "alert_enabled"},
		"AlertRollupEnabled": ubx.FieldSpec{WireName: "alert_rollup_enabled"},
		"Name":               ubx.FieldSpec{WireName: "name"},
		"QueryJson":          ubx.FieldSpec{WireName: "query_json"},
		"RuleEnabled":        ubx.FieldSpec{WireName: "rule_enabled"},
		"RuleScope":          ubx.FieldSpec{WireName: "rule_scope"},
		"QueryId":            ubx.FieldSpec{WireName: "query_id"},
	},
}
