// Code generated by `ubx sdk gen` from cloudflare_dos_expression_filter_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DosExpressionFilterResponseConfig {
  /** Identifier. */
  accountId: string | Computed<string>;
  /** UUID. */
  filterId: string | Computed<string>;
}

export interface DosExpressionFilterResponseAttrs {
  /** Identifier. */
  accountId: string;
  /** UUID. */
  filterId: string;
}

export const DosExpressionFilterResponse: DataSourceBinding<DosExpressionFilterResponseConfig, DosExpressionFilterResponseAttrs> = {
  wireType: "cloudflare_dos_expression_filter_response",
  fields: {
    accountId: "account_id",
    filterId: "filter_id",
  },
};
