// Code generated by `ubx sdk gen` from cloudflare_article. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Article_Errors {
  message?: string | Computed<string>;
}

export interface Article_Result_Articles_Tags {
  appliedBy?: string | Computed<string>;
  categoryId?: string | Computed<string>;
  uuid?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface Article_Result_Articles {
  datasetId?: string | Computed<string>;
  eventId?: string | Computed<string>;
  feedDisplayName?: string | Computed<string>;
  feedId?: string | Computed<string>;
  fetchedAt?: string | Computed<string>;
  id?: string | Computed<string>;
  link?: string | Computed<string>;
  publishedAt?: string | Computed<string>;
  read?: boolean | Computed<boolean>;
  readAt?: string | Computed<string>;
  summary?: string | Computed<string>;
  tags?: Article_Result_Articles_Tags[] | Computed<Article_Result_Articles_Tags[]>;
  title?: string | Computed<string>;
}

export interface Article_Result {
  articles: Article_Result_Articles[] | Computed<Article_Result_Articles[]>;
  hasMore: boolean | Computed<boolean>;
  nextCursor: string | Computed<string>;
  totalCount: number | Computed<number>;
  totalCountIsExact: boolean | Computed<boolean>;
}

export interface ArticleConfig {
  accountId: string | Computed<string>;
  cursor?: string | Computed<string>;
  feedCategory?: string | Computed<string>;
  feedId?: string | Computed<string>;
  fetchedAfter?: string | Computed<string>;
  fetchedBefore?: string | Computed<string>;
  includeTotal?: boolean | Computed<boolean>;
  perPage?: number | Computed<number>;
  publishedAfter?: string | Computed<string>;
  publishedBefore?: string | Computed<string>;
  read?: boolean | Computed<boolean>;
  search?: string | Computed<string>;
  sort?: string | Computed<string>;
  sourceType?: string | Computed<string>;
  tag?: string | Computed<string>;
  tagAppliedBy?: string | Computed<string>;
  tagCategory?: string | Computed<string>;
  tagId?: string | Computed<string>;
}

export interface ArticleAttrs {
  accountId: string;
  cursor: string;
  errors: Article_Errors[];
  feedCategory: string;
  feedId: string;
  fetchedAfter: string;
  fetchedBefore: string;
  includeTotal: boolean;
  perPage: number;
  publishedAfter: string;
  publishedBefore: string;
  read: boolean;
  result: Article_Result;
  search: string;
  sort: string;
  sourceType: string;
  success: boolean;
  tag: string;
  tagAppliedBy: string;
  tagCategory: string;
  tagId: string;
}

export const Article: DataSourceBinding<ArticleConfig, ArticleAttrs> = {
  wireType: "cloudflare_article",
  fields: {
    accountId: "account_id",
    cursor: "cursor",
    feedCategory: "feed_category",
    feedId: "feed_id",
    fetchedAfter: "fetched_after",
    fetchedBefore: "fetched_before",
    includeTotal: "include_total",
    perPage: "per_page",
    publishedAfter: "published_after",
    publishedBefore: "published_before",
    read: "read",
    search: "search",
    sort: "sort",
    sourceType: "source_type",
    tag: "tag",
    tagAppliedBy: "tag_applied_by",
    tagCategory: "tag_category",
    tagId: "tag_id",
  },
};
