# Code generated by `ubx sdk gen` from cloudflare_mconn_customer_connectors_get_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MconnCustomerConnectorsGetResponse_Device:
    id: Any = None
    # When true, create and provision a new licence key for the connector.
    provision_license: Any = None
    serial_number: Any = None

@dataclasses.dataclass
class MconnCustomerConnectorsGetResponse_Result_Device:
    id: Any = None
    serial_number: Any = None
    type: Any = None

@dataclasses.dataclass
class MconnCustomerConnectorsGetResponse_Result:
    activated: Any = None
    device: Any = None
    id: Any = None
    # Allowed days of the week for upgrades. Default is all days.
    interrupt_window_days_of_week: Any = None
    interrupt_window_duration_hours: Any = None
    # List of dates (YYYY-MM-DD) when upgrades are blocked.
    interrupt_window_embargo_dates: Any = None
    interrupt_window_hour_of_day: Any = None
    last_heartbeat: Any = None
    last_seen_version: Any = None
    last_updated: Any = None
    license_key: Any = None
    notes: Any = None
    primary: Any = None
    site_id: Any = None
    timezone: Any = None

_MconnCustomerConnectorsGetResponse_DeviceFields = {
    "id": ubx.FieldSpec(wire_name="id"),
    "provision_license": ubx.FieldSpec(wire_name="provision_license"),
    "serial_number": ubx.FieldSpec(wire_name="serial_number"),
}

@dataclasses.dataclass
class MconnCustomerConnectorsGetResponseConfig:
    # Whether this connector device has been activated. (AI-inferred)
    activated: Any = None
    # Exactly one of id, serial_number, or provision_license must be provided.
    device: Any = None
    # Allowed days of the week for upgrades. Default is all days.
    interrupt_window_days_of_week: Any = None
    # How many hours this connector's own maintenance interrupt window lasts. (AI-inferred)
    interrupt_window_duration_hours: Any = None
    # List of dates (YYYY-MM-DD) when upgrades are blocked.
    interrupt_window_embargo_dates: Any = None
    # The hour of day this connector's own maintenance interrupt window starts. (AI-inferred)
    interrupt_window_hour_of_day: Any = None
    # A free-text note about this connector device. (AI-inferred)
    notes: Any = None
    # Whether this is the site's own primary connector device. (AI-inferred)
    primary: Any = None
    # The real Magic WAN Connector site this device belongs to. (AI-inferred)
    site_id: Any = None
    # The real timezone this connector's own interrupt window is scheduled against. (AI-inferred)
    timezone: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    connector_id: Any = None

@dataclasses.dataclass
class MconnCustomerConnectorsGetResponseAttrs:
    # Whether this connector device has been activated. (AI-inferred)
    activated: Any = None
    # Exactly one of id, serial_number, or provision_license must be provided.
    device: Any = None
    # Allowed days of the week for upgrades. Default is all days.
    interrupt_window_days_of_week: Any = None
    # How many hours this connector's own maintenance interrupt window lasts. (AI-inferred)
    interrupt_window_duration_hours: Any = None
    # List of dates (YYYY-MM-DD) when upgrades are blocked.
    interrupt_window_embargo_dates: Any = None
    # The hour of day this connector's own maintenance interrupt window starts. (AI-inferred)
    interrupt_window_hour_of_day: Any = None
    # A free-text note about this connector device. (AI-inferred)
    notes: Any = None
    # Whether this is the site's own primary connector device. (AI-inferred)
    primary: Any = None
    # The requested resource, present when the API call succeeds. (AI-inferred)
    result: Any = None
    # The real Magic WAN Connector site this device belongs to. (AI-inferred)
    site_id: Any = None
    # The real timezone this connector's own interrupt window is scheduled against. (AI-inferred)
    timezone: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    connector_id: Any = None

MconnCustomerConnectorsGetResponse = ubx.ResourceBinding(
    wire_type="cloudflare_mconn_customer_connectors_get_response",
    fields={
        "activated": ubx.FieldSpec(wire_name="activated"),
        "device": ubx.FieldSpec(
            wire_name="device",
            kind="object",
            fields=_MconnCustomerConnectorsGetResponse_DeviceFields,
        ),
        "interrupt_window_days_of_week": ubx.FieldSpec(wire_name="interrupt_window_days_of_week"),
        "interrupt_window_duration_hours": ubx.FieldSpec(wire_name="interrupt_window_duration_hours"),
        "interrupt_window_embargo_dates": ubx.FieldSpec(wire_name="interrupt_window_embargo_dates"),
        "interrupt_window_hour_of_day": ubx.FieldSpec(wire_name="interrupt_window_hour_of_day"),
        "notes": ubx.FieldSpec(wire_name="notes"),
        "primary": ubx.FieldSpec(wire_name="primary"),
        "site_id": ubx.FieldSpec(wire_name="site_id"),
        "timezone": ubx.FieldSpec(wire_name="timezone"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "connector_id": ubx.FieldSpec(wire_name="connector_id"),
    },
)
