// Code generated by `ubx sdk gen` from cloudflare_dls_prefix_binding_response. DO NOT EDIT.
package prefixbindings

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DlsPrefixBindingResponseConfig struct {
	// IP prefix in CIDR notation to bind.
	Cidr any
	// The ID of the parent IP prefix that contains the CIDR.
	PrefixId any
	// Region key from managed regions (e.g., "us", "eu").
	RegionKey any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	BindingId any
}

type DlsPrefixBindingResponseAttrs struct {
	// IP prefix in CIDR notation to bind.
	Cidr any
	// The ID of the parent IP prefix that contains the CIDR.
	PrefixId any
	// Region key from managed regions (e.g., "us", "eu").
	RegionKey any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	BindingId any
}

var DlsPrefixBindingResponse = ubx.ResourceBinding{
	WireType: "cloudflare_dls_prefix_binding_response",
	Fields: ubx.FieldMap{
		"Cidr": ubx.FieldSpec{WireName: "cidr"},
		"PrefixId": ubx.FieldSpec{WireName: "prefix_id"},
		"RegionKey": ubx.FieldSpec{WireName: "region_key"},
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"BindingId": ubx.FieldSpec{WireName: "binding_id"},
	},
}
