# Code generated by `ubx sdk gen` from cloudflare_stream_output_response_collection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class StreamOutputResponseCollectionConfig:
    # Identifier.
    account_id: Any = None
    # A unique identifier for a live input.
    live_input_identifier: Any = None

@dataclasses.dataclass
class StreamOutputResponseCollectionAttrs:
    # Identifier.
    account_id: Any = None
    # A unique identifier for a live input.
    live_input_identifier: Any = None

StreamOutputResponseCollection = ubx.DataSourceBinding(
    wire_type="cloudflare_stream_output_response_collection",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "live_input_identifier": ubx.FieldSpec(wire_name="live_input_identifier"),
    },
)
