# Code generated by `ubx sdk gen` from cloudflare_service. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Service_Errors_Source:
    pointer: Any = None

@dataclasses.dataclass
class Service_Errors:
    code: Any = None
    documentation_url: Any = None
    message: Any = None
    source: Any = None

@dataclasses.dataclass
class Service_Result:
    id: Any = None
    name: Any = None

@dataclasses.dataclass
class ServiceConfig:
    # Identifier of a Cloudflare account.
    account_id: Any = None

@dataclasses.dataclass
class ServiceAttrs:
    # Identifier of a Cloudflare account.
    account_id: Any = None
    errors: Any = None
    messages: Any = None
    result: Any = None
    # Whether the API call was successful.
    success: Any = None

Service = ubx.DataSourceBinding(
    wire_type="cloudflare_service",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
