// Code generated by `ubx sdk gen` from cloudflare_dns_settings_dns_response_single_2. DO NOT EDIT.
package dnssettingsforazone

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DnsSettingsDnsResponseSingle2_Result_Nameservers struct {
	NsSet any
	Type  any
}

type DnsSettingsDnsResponseSingle2_Result struct {
	Nameservers any
}

type DnsSettingsDnsResponseSingle2Config struct {
	// Identifier.
	ZoneId any
}

type DnsSettingsDnsResponseSingle2Attrs struct {
	Result any
	// Identifier.
	ZoneId any
}

var DnsSettingsDnsResponseSingle2 = ubx.DataSourceBinding{
	WireType: "cloudflare_dns_settings_dns_response_single_2",
	Fields: ubx.FieldMap{
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
	},
}
