# Code generated by `ubx sdk gen` from cloudflare_target_environment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TargetEnvironment_Errors_Source:
    pointer: Any = None

@dataclasses.dataclass
class TargetEnvironment_Errors:
    code: Any = None
    documentation_url: Any = None
    message: Any = None
    source: Any = None

@dataclasses.dataclass
class TargetEnvironment_Result_Target:
    type: Any = None
    zone_tag: Any = None

@dataclasses.dataclass
class TargetEnvironment_Result:
    # Optional description providing additional context.
    description: Any = None
    # Target environment identifier.
    id: Any = None
    # Human-readable name.
    name: Any = None
    # Identifies the Cloudflare asset to scan. Uses a `type` discriminator. Currently the service supports only `zone` targets.
    target: Any = None

_TargetEnvironment_Result_TargetFields = {
    "type": ubx.FieldSpec(wire_name="type"),
    "zone_tag": ubx.FieldSpec(wire_name="zone_tag"),
}

@dataclasses.dataclass
class TargetEnvironmentConfig:
    # Optional description.
    description: Any = None
    # Human-readable name.
    name: Any = None
    # Identifies the Cloudflare asset to scan. Uses a `type` discriminator. Currently the service supports only `zone` targets.
    target: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    target_environment_id: Any = None

@dataclasses.dataclass
class TargetEnvironmentAttrs:
    # Optional description.
    description: Any = None
    # Errors returned by the API call, empty when the call succeeds. (AI-inferred)
    errors: Any = None
    # Informational messages returned alongside the API call's own result. (AI-inferred)
    messages: Any = None
    # Human-readable name.
    name: Any = None
    result: Any = None
    # Pagination metadata for this list response (page size, cursor or page number, total count). (AI-inferred)
    result_info: Any = None
    # Whether the API call was successful.
    success: Any = None
    # Identifies the Cloudflare asset to scan. Uses a `type` discriminator. Currently the service supports only `zone` targets.
    target: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    target_environment_id: Any = None

TargetEnvironment = ubx.ResourceBinding(
    wire_type="cloudflare_target_environment",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "name": ubx.FieldSpec(wire_name="name"),
        "target": ubx.FieldSpec(
            wire_name="target",
            kind="object",
            fields=_TargetEnvironment_Result_TargetFields,
        ),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "target_environment_id": ubx.FieldSpec(wire_name="target_environment_id"),
    },
)
