// Code generated by `ubx sdk gen` from cloudflare_tunnel_hostname_route_response_single. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface TunnelHostnameRouteResponseSingleConfig {
  /** An optional description of the hostname route. */
  comment?: string | Computed<string>;
  /** The hostname of the route. */
  hostname?: string | Computed<string>;
  /** UUID of the tunnel. */
  tunnelId?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  hostnameRouteId: string | Computed<string>;
}

export interface TunnelHostnameRouteResponseSingleAttrs {
  /** An optional description of the hostname route. */
  comment: string;
  /** The hostname of the route. */
  hostname: string;
  /** UUID of the tunnel. */
  tunnelId: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  hostnameRouteId: string;
}

export const TunnelHostnameRouteResponseSingle: ResourceBinding<TunnelHostnameRouteResponseSingleConfig, TunnelHostnameRouteResponseSingleAttrs> = {
  wireType: "cloudflare_tunnel_hostname_route_response_single",
  fields: {
    comment: "comment",
    hostname: "hostname",
    tunnelId: "tunnel_id",
    accountId: "account_id",
    hostnameRouteId: "hostname_route_id",
  },
};
