// Code generated by `ubx sdk gen` from cloudflare_access_single_user_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccessSingleUserResponse_Result {
  /** True if the user has authenticated with Cloudflare Access. */
  accessSeat?: boolean | Computed<boolean>;
  /** The number of active devices registered to the user. */
  activeDeviceCount?: number | Computed<number>;
  createdAt?: string | Computed<string>;
  /** The email of the user. */
  email?: string | Computed<string>;
  /** True if the user has logged into the WARP client. */
  gatewaySeat?: boolean | Computed<boolean>;
  /** UUID. */
  id?: string | Computed<string>;
  /** The time at which the user last successfully logged in. */
  lastSuccessfulLogin?: string | Computed<string>;
  /** The name of the user. */
  name?: string | Computed<string>;
  /** The unique API identifier for the Zero Trust seat. */
  seatUid?: string | Computed<string>;
  /** The unique API identifier for the user. */
  uid?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface AccessSingleUserResponseConfig {
  /** The email of the user. */
  email: string | Computed<string>;
  /** The name of the user. */
  name?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  userId: string | Computed<string>;
}

export interface AccessSingleUserResponseAttrs {
  /** The email of the user. */
  email: string;
  /** The name of the user. */
  name: string;
  /** The requested resource, present when the API call succeeds. (AI-inferred) */
  result: AccessSingleUserResponse_Result;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  userId: string;
}

export const AccessSingleUserResponse: ResourceBinding<AccessSingleUserResponseConfig, AccessSingleUserResponseAttrs> = {
  wireType: "cloudflare_access_single_user_response",
  fields: {
    email: "email",
    name: "name",
    accountId: "account_id",
    userId: "user_id",
  },
};
