// Code generated by `ubx sdk gen` from cloudflare_access_response_collection_23. DO NOT EDIT.
package zonelevelaccesspolicies

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AccessResponseCollection23Config struct {
	// UUID.
	AppId any
	// Identifier.
	ZoneId any
}

type AccessResponseCollection23Attrs struct {
	// UUID.
	AppId any
	// Identifier.
	ZoneId any
}

var AccessResponseCollection23 = ubx.DataSourceBinding{
	WireType: "cloudflare_access_response_collection_23",
	Fields: ubx.FieldMap{
		"AppId": ubx.FieldSpec{WireName: "app_id"},
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
	},
}
