# Code generated by `ubx sdk gen` from cloudflare_scan. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Scan_Errors:
    message: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Asns_Asn:
    asn: Any = None
    description: Any = None
    location_alpha2: Any = None
    name: Any = None
    org_name: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Asns:
    # ASN's contacted
    asn: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Certificates:
    issuer: Any = None
    subject_name: Any = None
    valid_from: Any = None
    valid_to: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains_ExampleCom_Categories_Content:
    id: Any = None
    name: Any = None
    super_category_id: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains_ExampleCom_Categories_Inherited:
    content: Any = None
    from_: Any = None
    risks: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains_ExampleCom_Categories:
    content: Any = None
    inherited: Any = None
    risks: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains_ExampleCom_Dns:
    address: Any = None
    dnssec_valid: Any = None
    name: Any = None
    type: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains_ExampleCom_Rank:
    bucket: Any = None
    name: Any = None
    # Rank in the Global Radar Rank, if set. See more at https://blog.cloudflare.com/radar-domain-rankings/
    rank: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains_ExampleCom:
    categories: Any = None
    dns: Any = None
    name: Any = None
    rank: Any = None
    type: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Domains:
    example_com: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Geo:
    continents: Any = None
    locations: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Ips_Ip:
    asn: Any = None
    asn_description: Any = None
    asn_location_alpha2: Any = None
    asn_name: Any = None
    asn_org_name: Any = None
    continent: Any = None
    geoname_id: Any = None
    ip: Any = None
    ip_version: Any = None
    latitude: Any = None
    location_alpha2: Any = None
    location_name: Any = None
    longitude: Any = None
    subdivision1_name: Any = None
    subdivision2_name: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Ips:
    ip: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Links_Link:
    # Outgoing link detected in the DOM
    href: Any = None
    text: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Links:
    link: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta_Processors_Categories:
    content: Any = None
    risks: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta_Processors_Tech_Categories:
    groups: Any = None
    id: Any = None
    name: Any = None
    priority: Any = None
    slug: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta_Processors_Tech_Evidence_Patterns:
    confidence: Any = None
    excludes: Any = None
    implies: Any = None
    match: Any = None
    name: Any = None
    regex: Any = None
    type: Any = None
    value: Any = None
    version: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta_Processors_Tech_Evidence:
    implied_by: Any = None
    patterns: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta_Processors_Tech:
    categories: Any = None
    confidence: Any = None
    description: Any = None
    evidence: Any = None
    icon: Any = None
    name: Any = None
    slug: Any = None
    website: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta_Processors:
    categories: Any = None
    phishing: Any = None
    rank: Any = None
    tech: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Meta:
    processors: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page_Console:
    category: Any = None
    text: Any = None
    type: Any = None
    url: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page_Cookies:
    domain: Any = None
    expires: Any = None
    http_only: Any = None
    name: Any = None
    path: Any = None
    priority: Any = None
    same_party: Any = None
    secure: Any = None
    session: Any = None
    size: Any = None
    source_port: Any = None
    source_scheme: Any = None
    value: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page_Headers:
    name: Any = None
    value: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page_Js_Variables:
    name: Any = None
    type: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page_Js:
    variables: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page_SecurityViolations:
    category: Any = None
    text: Any = None
    url: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Page:
    asn: Any = None
    asn_location_alpha2: Any = None
    asnname: Any = None
    console: Any = None
    cookies: Any = None
    country: Any = None
    country_location_alpha2: Any = None
    domain: Any = None
    headers: Any = None
    ip: Any = None
    js: Any = None
    security_violations: Any = None
    status: Any = None
    subdivision1_name: Any = None
    subdivision2name: Any = None
    url: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Performance:
    connect_end: Any = None
    connect_start: Any = None
    decoded_body_size: Any = None
    dom_complete: Any = None
    dom_content_loaded_event_end: Any = None
    dom_content_loaded_event_start: Any = None
    dom_interactive: Any = None
    domain_lookup_end: Any = None
    domain_lookup_start: Any = None
    duration: Any = None
    encoded_body_size: Any = None
    entry_type: Any = None
    fetch_start: Any = None
    initiator_type: Any = None
    load_event_end: Any = None
    load_event_start: Any = None
    name: Any = None
    next_hop_protocol: Any = None
    redirect_count: Any = None
    redirect_end: Any = None
    redirect_start: Any = None
    request_start: Any = None
    response_end: Any = None
    response_start: Any = None
    secure_connection_start: Any = None
    start_time: Any = None
    transfer_size: Any = None
    type: Any = None
    unload_event_end: Any = None
    unload_event_start: Any = None
    worker_start: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Task_ScannedFrom:
    # IATA code of Cloudflare datacenter
    colo: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Task:
    # Submitter location
    client_location: Any = None
    client_type: Any = None
    # URL of the primary request, after all HTTP redirects
    effective_url: Any = None
    errors: Any = None
    scanned_from: Any = None
    status: Any = None
    success: Any = None
    time: Any = None
    time_end: Any = None
    # Submitted URL
    url: Any = None
    # Scan ID
    uuid: Any = None
    visibility: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Verdicts_Overall:
    categories: Any = None
    # At least one of our subsystems marked the site as potentially malicious at the time of the scan.
    malicious: Any = None
    phishing: Any = None

@dataclasses.dataclass
class Scan_Result_Scan_Verdicts:
    overall: Any = None

@dataclasses.dataclass
class Scan_Result_Scan:
    # Dictionary of Autonomous System Numbers where ASN's are the keys
    asns: Any = None
    certificates: Any = None
    domains: Any = None
    geo: Any = None
    ips: Any = None
    links: Any = None
    meta: Any = None
    page: Any = None
    performance: Any = None
    task: Any = None
    verdicts: Any = None

@dataclasses.dataclass
class Scan_Result:
    scan: Any = None

@dataclasses.dataclass
class ScanConfig:
    # Move these accounts to the destination organization.
    account_ids: Any = None
    # Move accounts to this organization ID.
    destination_organization_id: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    scan_id: Any = None

@dataclasses.dataclass
class ScanAttrs:
    # Move these accounts to the destination organization.
    account_ids: Any = None
    # Move accounts to this organization ID.
    destination_organization_id: Any = None
    errors: Any = None
    messages: Any = None
    result: Any = None
    # Whether request was successful or not
    success: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    scan_id: Any = None

Scan = ubx.ResourceBinding(
    wire_type="cloudflare_scan",
    fields={
        "account_ids": ubx.FieldSpec(wire_name="account_ids"),
        "destination_organization_id": ubx.FieldSpec(wire_name="destination_organization_id"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "scan_id": ubx.FieldSpec(wire_name="scan_id"),
    },
)
