# Code generated by `ubx sdk gen` from cloudflare_registrar_api_sandbox_registration_response_collection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RegistrarApiSandboxRegistrationResponseCollectionConfig:
    cursor: Any = None
    direction: Any = None
    per_page: Any = None
    sort_by: Any = None

@dataclasses.dataclass
class RegistrarApiSandboxRegistrationResponseCollectionAttrs:
    # Identifier.
    account_id: Any = None
    cursor: Any = None
    direction: Any = None
    per_page: Any = None
    sort_by: Any = None

RegistrarApiSandboxRegistrationResponseCollection = ubx.DataSourceBinding(
    wire_type="cloudflare_registrar_api_sandbox_registration_response_collection",
    fields={
        "cursor": ubx.FieldSpec(wire_name="cursor"),
        "direction": ubx.FieldSpec(wire_name="direction"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "sort_by": ubx.FieldSpec(wire_name="sort_by"),
    },
)
