# Code generated by `ubx sdk gen` from cloudflare_predefined. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Predefined_ContextAwareness_Skip:
    # If the content type is a file, skip context analysis and return all matches.
    files: Any = None

@dataclasses.dataclass
class Predefined_ContextAwareness:
    # If true, scan the context of predefined entries to only return matches surrounded by keywords.
    enabled: Any = None
    # Content types to exclude from context analysis and return all matches.
    skip: Any = None

@dataclasses.dataclass
class Predefined_Entries:
    enabled: Any = None
    id: Any = None

_Predefined_ContextAwareness_SkipFields = {
    "files": ubx.FieldSpec(wire_name="files"),
}

_Predefined_ContextAwarenessFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "skip": ubx.FieldSpec(
        wire_name="skip",
        kind="object",
        fields=_Predefined_ContextAwareness_SkipFields,
    ),
}

_Predefined_EntriesFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "id": ubx.FieldSpec(wire_name="id"),
}

@dataclasses.dataclass
class PredefinedConfig:
    # Whether AI-based context analysis is enabled for this predefined DLP entry. (AI-inferred)
    ai_context_enabled: Any = None
    # How many real matches this predefined DLP entry allows before it triggers. (AI-inferred)
    allowed_match_count: Any = None
    # The real minimum confidence level a match must reach before this predefined DLP entry triggers. (AI-inferred)
    confidence_threshold: Any = None
    # Scan the context of predefined entries to only return matches surrounded by keywords.
    context_awareness: Any = None
    # The real, individual detection entries this predefined DLP profile groups together. (AI-inferred)
    entries: Any = None
    # Whether this predefined DLP entry scans image text via OCR. (AI-inferred)
    ocr_enabled: Any = None
    # The real predefined DLP profile this entry belongs to. (AI-inferred)
    profile_id: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None

@dataclasses.dataclass
class PredefinedAttrs:
    # Whether AI-based context analysis is enabled for this predefined DLP entry. (AI-inferred)
    ai_context_enabled: Any = None
    # How many real matches this predefined DLP entry allows before it triggers. (AI-inferred)
    allowed_match_count: Any = None
    # The real minimum confidence level a match must reach before this predefined DLP entry triggers. (AI-inferred)
    confidence_threshold: Any = None
    # Scan the context of predefined entries to only return matches surrounded by keywords.
    context_awareness: Any = None
    # The real, individual detection entries this predefined DLP profile groups together. (AI-inferred)
    entries: Any = None
    # Whether this predefined DLP entry scans image text via OCR. (AI-inferred)
    ocr_enabled: Any = None
    # The real predefined DLP profile this entry belongs to. (AI-inferred)
    profile_id: Any = None
    # The requested resource, present when the API call succeeds. (AI-inferred)
    result: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None

Predefined = ubx.ResourceBinding(
    wire_type="cloudflare_predefined",
    fields={
        "ai_context_enabled": ubx.FieldSpec(wire_name="ai_context_enabled"),
        "allowed_match_count": ubx.FieldSpec(wire_name="allowed_match_count"),
        "confidence_threshold": ubx.FieldSpec(wire_name="confidence_threshold"),
        "context_awareness": ubx.FieldSpec(
            wire_name="context_awareness",
            kind="object",
            fields=_Predefined_ContextAwarenessFields,
        ),
        "entries": ubx.FieldSpec(
            wire_name="entries",
            kind="list",
            fields=_Predefined_EntriesFields,
        ),
        "ocr_enabled": ubx.FieldSpec(wire_name="ocr_enabled"),
        "profile_id": ubx.FieldSpec(wire_name="profile_id"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
