// Code generated by `ubx sdk gen` from cloudflare_addressing_response_collection_4. DO NOT EDIT.
package ipaddressmanagementleases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AddressingResponseCollection4Config struct {
	// Identifier of a Cloudflare account.
	AccountId any
}

type AddressingResponseCollection4Attrs struct {
	// Identifier of a Cloudflare account.
	AccountId any
}

var AddressingResponseCollection4 = ubx.DataSourceBinding{
	WireType: "cloudflare_addressing_response_collection_4",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
