// Code generated by `ubx sdk gen` from cloudflare_supported. DO NOT EDIT.
package workersai

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Supported_Result struct {
	Extension any
	MimeType  any
}

type SupportedConfig struct {
	AccountId any
}

type SupportedAttrs struct {
	AccountId any
	Result    any
	Success   any
}

var Supported = ubx.DataSourceBinding{
	WireType: "cloudflare_supported",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
