# Code generated by `ubx sdk gen` from cloudflare_securitytxt. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SecuritytxtConfig:
    # Identifier.
    zone_id: Any = None

@dataclasses.dataclass
class SecuritytxtAttrs:
    # Identifier.
    zone_id: Any = None

Securitytxt = ubx.DataSourceBinding(
    wire_type="cloudflare_securitytxt",
    fields={
        "zone_id": ubx.FieldSpec(wire_name="zone_id"),
    },
)
