// Code generated by `ubx sdk gen` from cloudflare_sending_domain_restriction. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SendingDomainRestrictionConfig {
  direction?: string | Computed<string>;
  order?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  search?: string | Computed<string>;
}

export interface SendingDomainRestrictionAttrs {
  direction: string;
  order: string;
  page: number;
  perPage: number;
  search: string;
}

export const SendingDomainRestriction: DataSourceBinding<SendingDomainRestrictionConfig, SendingDomainRestrictionAttrs> = {
  wireType: "cloudflare_sending_domain_restriction",
  fields: {
    direction: "direction",
    order: "order",
    page: "page",
    perPage: "per_page",
    search: "search",
  },
};
