# Code generated by `ubx sdk gen` from cloudflare_client_version. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ClientVersion_Errors:
    code: Any = None
    message: Any = None

@dataclasses.dataclass
class ClientVersion_Result:
    package_size: Any = None
    package_url: Any = None
    release_date: Any = None
    release_notes: Any = None
    version: Any = None

@dataclasses.dataclass
class ClientVersion_ResultInfo:
    # Number of records in the response.
    count: Any = None
    # The page size number of the response.
    page: Any = None
    # The limit for the number of records in the response.
    per_page: Any = None
    # Total number of records available.
    total_count: Any = None
    # Total number of pages available.
    total_pages: Any = None

@dataclasses.dataclass
class ClientVersionConfig:
    account_id: Any = None
    page: Any = None
    per_page: Any = None
    release_track: Any = None
    target_environment: Any = None

@dataclasses.dataclass
class ClientVersionAttrs:
    account_id: Any = None
    errors: Any = None
    messages: Any = None
    page: Any = None
    per_page: Any = None
    release_track: Any = None
    result: Any = None
    result_info: Any = None
    # Indicates whether the API call was successful.
    success: Any = None
    target_environment: Any = None

ClientVersion = ubx.DataSourceBinding(
    wire_type="cloudflare_client_version",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "release_track": ubx.FieldSpec(wire_name="release_track"),
        "target_environment": ubx.FieldSpec(wire_name="target_environment"),
    },
)
