// Code generated by `ubx sdk gen` from cloudflare_aig_billing_get_credit_balance_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AigBillingGetCreditBalanceResponse_Errors {
  code?: number | Computed<number>;
  message?: string | Computed<string>;
}

export interface AigBillingGetCreditBalanceResponse_Result_PaymentMethod {
  brand?: string | Computed<string>;
  last4?: string | Computed<string>;
}

export interface AigBillingGetCreditBalanceResponse_Result_TopupConfig {
  amount: number | Computed<number>;
  disabledReason?: string | Computed<string>;
  error?: string | Computed<string>;
  lastFailedAt?: number | Computed<number>;
  threshold: number | Computed<number>;
}

export interface AigBillingGetCreditBalanceResponse_Result {
  balance: number | Computed<number>;
  firstTopupSuccess?: boolean | Computed<boolean>;
  hasDefaultPaymentMethod: boolean | Computed<boolean>;
  paymentMethod: AigBillingGetCreditBalanceResponse_Result_PaymentMethod | Computed<AigBillingGetCreditBalanceResponse_Result_PaymentMethod>;
  topupConfig: AigBillingGetCreditBalanceResponse_Result_TopupConfig | Computed<AigBillingGetCreditBalanceResponse_Result_TopupConfig>;
}

export interface AigBillingGetCreditBalanceResponse_ResultInfo {
  hasMore: boolean | Computed<boolean>;
  page: number | Computed<number>;
  perPage: number | Computed<number>;
  totalCount: number | Computed<number>;
}

export interface AigBillingGetCreditBalanceResponseConfig {
  accountId: string | Computed<string>;
}

export interface AigBillingGetCreditBalanceResponseAttrs {
  accountId: string;
  errors: AigBillingGetCreditBalanceResponse_Errors[];
  messages: AigBillingGetCreditBalanceResponse_Errors[];
  result: AigBillingGetCreditBalanceResponse_Result;
  resultInfo: AigBillingGetCreditBalanceResponse_ResultInfo;
  success: boolean;
}

export const AigBillingGetCreditBalanceResponse: DataSourceBinding<AigBillingGetCreditBalanceResponseConfig, AigBillingGetCreditBalanceResponseAttrs> = {
  wireType: "cloudflare_aig_billing_get_credit_balance_response",
  fields: {
    accountId: "account_id",
  },
};
