// Code generated by `ubx sdk gen` from cloudflare_magic_site_single_response. DO NOT EDIT.
package magicsites

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MagicSiteSingleResponse_Location struct {
	// Latitude
	Lat any
	// Longitude
	Lon any
}

type MagicSiteSingleResponse_Result struct {
	// Magic Connector identifier tag.
	ConnectorId any
	Description any
	// Site high availability mode. If set to true, the site can have two connectors and runs in high availability mode.
	HaMode any
	// Identifier
	Id any
	// Location of site in latitude and longitude.
	Location any
	// The name of the site.
	Name any
	// Magic Connector identifier tag. Used when high availability mode is on.
	SecondaryConnectorId any
}

var MagicSiteSingleResponse_LocationFields = ubx.FieldMap{
	"Lat": ubx.FieldSpec{WireName: "lat"},
	"Lon": ubx.FieldSpec{WireName: "lon"},
}

type MagicSiteSingleResponseConfig struct {
	// Magic Connector identifier tag.
	ConnectorId any
	// A human-readable description of the site. (AI-inferred)
	Description any
	// Site high availability mode. If set to true, the site can have two connectors and runs in high availability mode.
	HaMode any
	// Location of site in latitude and longitude.
	Location any
	// The name of the site.
	Name any
	// Magic Connector identifier tag. Used when high availability mode is on.
	SecondaryConnectorId any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	SiteId any
}

type MagicSiteSingleResponseAttrs struct {
	// Magic Connector identifier tag.
	ConnectorId any
	// A human-readable description of the site. (AI-inferred)
	Description any
	// Site high availability mode. If set to true, the site can have two connectors and runs in high availability mode.
	HaMode any
	// Location of site in latitude and longitude.
	Location any
	// The name of the site.
	Name any
	// The requested resource, present when the API call succeeds. (AI-inferred)
	Result any
	// Magic Connector identifier tag. Used when high availability mode is on.
	SecondaryConnectorId any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	SiteId any
}

var MagicSiteSingleResponse = ubx.ResourceBinding{
	WireType: "cloudflare_magic_site_single_response",
	Fields: ubx.FieldMap{
		"ConnectorId": ubx.FieldSpec{WireName: "connector_id"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"HaMode":      ubx.FieldSpec{WireName: "ha_mode"},
		"Location": ubx.FieldSpec{
			WireName: "location",
			Kind:     "object",
			Fields:   MagicSiteSingleResponse_LocationFields,
		},
		"Name":                 ubx.FieldSpec{WireName: "name"},
		"SecondaryConnectorId": ubx.FieldSpec{WireName: "secondary_connector_id"},
		"AccountId":            ubx.FieldSpec{WireName: "account_id"},
		"SiteId":               ubx.FieldSpec{WireName: "site_id"},
	},
}
