// Code generated by `ubx sdk gen` from cloudflare_constant. DO NOT EDIT.
package requestforinformationrfi

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ConstantConfig struct {
	// Identifier.
	AccountId any
}

type ConstantAttrs struct {
	// Identifier.
	AccountId any
}

var Constant = ubx.DataSourceBinding{
	WireType: "cloudflare_constant",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
