// Code generated by `ubx sdk gen` from cloudflare_as_set. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AsSet_Result_AsSets {
  asMembersCount?: number | Computed<number>;
  asSetMembersCount?: number | Computed<number>;
  asSetUpstreamsCount?: number | Computed<number>;
  asnConeSize?: number | Computed<number>;
  hierarchicalAsn?: number | Computed<number>;
  inferredAsn?: number | Computed<number>;
  irrSources?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  peeringdbAsn?: number | Computed<number>;
}

export interface AsSet_Result {
  asSets: AsSet_Result_AsSets[] | Computed<AsSet_Result_AsSets[]>;
  /** Paths from the AS-SET that include the given AS to its upstreams recursively */
  paths: string[][] | Computed<string[][]>;
}

export interface AsSetConfig {
  /** Retrieves all AS-SETs that the given AS is a member of. */
  asn: number | Computed<number>;
  /** Format in which results will be returned. */
  format?: string | Computed<string>;
}

export interface AsSetAttrs {
  /** Retrieves all AS-SETs that the given AS is a member of. */
  asn: number;
  /** Format in which results will be returned. */
  format: string;
  result: AsSet_Result;
  success: boolean;
}

export const AsSet: DataSourceBinding<AsSetConfig, AsSetAttrs> = {
  wireType: "cloudflare_as_set",
  fields: {
    asn: "asn",
    format: "format",
  },
};
