// Code generated by `ubx sdk gen` from cloudflare_rel. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Rel_Result_Meta {
  dataTime: string | Computed<string>;
  queryTime: string | Computed<string>;
  totalPeers: number | Computed<number>;
}

export interface Rel_Result_Rels {
  asn1?: number | Computed<number>;
  asn1Country?: string | Computed<string>;
  asn1Name?: string | Computed<string>;
  asn2?: number | Computed<number>;
  asn2Country?: string | Computed<string>;
  asn2Name?: string | Computed<string>;
  rel?: string | Computed<string>;
}

export interface Rel_Result {
  meta: Rel_Result_Meta | Computed<Rel_Result_Meta>;
  rels: Rel_Result_Rels[] | Computed<Rel_Result_Rels[]>;
}

export interface RelConfig {
  /** Retrieves all ASNs with provider-customer or peering relationships with the given ASN. */
  asn: number | Computed<number>;
  /** Retrieves the AS relationship of ASN2 with respect to the given ASN. */
  asn2?: number | Computed<number>;
  /** Format in which results will be returned. */
  format?: string | Computed<string>;
}

export interface RelAttrs {
  /** Retrieves all ASNs with provider-customer or peering relationships with the given ASN. */
  asn: number;
  /** Retrieves the AS relationship of ASN2 with respect to the given ASN. */
  asn2: number;
  /** Format in which results will be returned. */
  format: string;
  result: Rel_Result;
  success: boolean;
}

export const Rel: DataSourceBinding<RelConfig, RelAttrs> = {
  wireType: "cloudflare_rel",
  fields: {
    asn: "asn",
    asn2: "asn2",
    format: "format",
  },
};
