// Code generated by `ubx sdk gen` from cloudflare_dos_syn_protection_rule_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DosSynProtectionRuleResponse_Errors_Source {
  pointer?: string | Computed<string>;
}

export interface DosSynProtectionRuleResponse_Errors {
  code?: number | Computed<number>;
  documentationUrl?: string | Computed<string>;
  message?: string | Computed<string>;
  source?: DosSynProtectionRuleResponse_Errors_Source | Computed<DosSynProtectionRuleResponse_Errors_Source>;
}

export interface DosSynProtectionRuleResponse_Result {
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string | Computed<string>;
  /** The creation timestamp of the SYN Protection rule. */
  createdOn: string | Computed<string>;
  /** The unique ID of the SYN Protection rule. */
  id: string | Computed<string>;
  /** The type of mitigation for SYN Protection. Must be one of 'challenge' or 'retransmit'. */
  mitigationType: string | Computed<string>;
  /** The mode for SYN Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string | Computed<string>;
  /** The last modification timestamp of the SYN Protection rule. */
  modifiedOn: string | Computed<string>;
  /** The name of the SYN Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string | Computed<string>;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string | Computed<string>;
  /** The scope for the SYN Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string | Computed<string>;
}

export interface DosSynProtectionRuleResponseConfig {
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string | Computed<string>;
  /** The type of mitigation. Must be one of 'challenge' or 'retransmit'. Optional. Defaults to 'challenge'. */
  mitigationType?: string | Computed<string>;
  /** The mode for SYN Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string | Computed<string>;
  /** The name of the SYN Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string | Computed<string>;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string | Computed<string>;
  /** The scope for the SYN Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string | Computed<string>;
}

export interface DosSynProtectionRuleResponseAttrs {
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string;
  /** Errors returned by the API call, empty when the call succeeds. (AI-inferred) */
  errors: DosSynProtectionRuleResponse_Errors[];
  /** Informational messages returned alongside the API call's own result. (AI-inferred) */
  messages: DosSynProtectionRuleResponse_Errors[];
  /** The type of mitigation. Must be one of 'challenge' or 'retransmit'. Optional. Defaults to 'challenge'. */
  mitigationType: string;
  /** The mode for SYN Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string;
  /** The name of the SYN Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string;
  result: DosSynProtectionRuleResponse_Result;
  /** The scope for the SYN Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string;
  /** Whether the API call was successful. */
  success: boolean;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string;
}

export const DosSynProtectionRuleResponse: ResourceBinding<DosSynProtectionRuleResponseConfig, DosSynProtectionRuleResponseAttrs> = {
  wireType: "cloudflare_dos_syn_protection_rule_response",
  fields: {
    burstSensitivity: "burst_sensitivity",
    mitigationType: "mitigation_type",
    mode: "mode",
    name: "name",
    rateSensitivity: "rate_sensitivity",
    scope: "scope",
    accountId: "account_id",
    ruleId: "rule_id",
  },
};
