// Code generated by `ubx sdk gen` from cloudflare_dos_dns_protection_rule_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DosDnsProtectionRuleResponseConfig {
  /** Whether to block DNS ANY queries. Optional. Defaults to true. */
  blockAnyQueries?: boolean | Computed<boolean>;
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string | Computed<string>;
  /** The mode for DNS Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string | Computed<string>;
  /** The name of the DNS Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string | Computed<string>;
  /** The profile sensitivity. Recommended setting is 'low'. Must be one of 'low', 'medium', 'high', or 'very_high'. */
  profileSensitivity: string | Computed<string>;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string | Computed<string>;
  /** The scope for the DNS Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string | Computed<string>;
}

export interface DosDnsProtectionRuleResponseAttrs {
  /** Whether to block DNS ANY queries. Optional. Defaults to true. */
  blockAnyQueries: boolean;
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string;
  /** The mode for DNS Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string;
  /** The name of the DNS Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string;
  /** The profile sensitivity. Recommended setting is 'low'. Must be one of 'low', 'medium', 'high', or 'very_high'. */
  profileSensitivity: string;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string;
  /** The scope for the DNS Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string;
}

export const DosDnsProtectionRuleResponse: ResourceBinding<DosDnsProtectionRuleResponseConfig, DosDnsProtectionRuleResponseAttrs> = {
  wireType: "cloudflare_dos_dns_protection_rule_response",
  fields: {
    blockAnyQueries: "block_any_queries",
    burstSensitivity: "burst_sensitivity",
    mode: "mode",
    name: "name",
    profileSensitivity: "profile_sensitivity",
    rateSensitivity: "rate_sensitivity",
    scope: "scope",
    accountId: "account_id",
    ruleId: "rule_id",
  },
};
