// Code generated by `ubx sdk gen` from cloudflare_dos_syn_protection_rule_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DosSynProtectionRuleResponseConfig {
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string | Computed<string>;
  /** The type of mitigation. Must be one of 'challenge' or 'retransmit'. Optional. Defaults to 'challenge'. */
  mitigationType?: string | Computed<string>;
  /** The mode for SYN Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string | Computed<string>;
  /** The name of the SYN Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string | Computed<string>;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string | Computed<string>;
  /** The scope for the SYN Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string | Computed<string>;
}

export interface DosSynProtectionRuleResponseAttrs {
  /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
  burstSensitivity: string;
  /** The type of mitigation. Must be one of 'challenge' or 'retransmit'. Optional. Defaults to 'challenge'. */
  mitigationType: string;
  /** The mode for SYN Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
  mode: string;
  /** The name of the SYN Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
  name: string;
  /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
  rateSensitivity: string;
  /** The scope for the SYN Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
  scope: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string;
}

export const DosSynProtectionRuleResponse: ResourceBinding<DosSynProtectionRuleResponseConfig, DosSynProtectionRuleResponseAttrs> = {
  wireType: "cloudflare_dos_syn_protection_rule_response",
  fields: {
    burstSensitivity: "burst_sensitivity",
    mitigationType: "mitigation_type",
    mode: "mode",
    name: "name",
    rateSensitivity: "rate_sensitivity",
    scope: "scope",
    accountId: "account_id",
    ruleId: "rule_id",
  },
};
