// Code generated by `ubx sdk gen` from cloudflare_dos_prefix_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DosPrefixResponseConfig {
  /** A comment describing the prefix. */
  comment: string | Computed<string>;
  /** Whether to exclude the prefix from protection. */
  excluded: boolean | Computed<boolean>;
  /** The prefix to add in CIDR format. */
  prefix: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  prefixId: string | Computed<string>;
}

export interface DosPrefixResponseAttrs {
  /** A comment describing the prefix. */
  comment: string;
  /** Whether to exclude the prefix from protection. */
  excluded: boolean;
  /** The prefix to add in CIDR format. */
  prefix: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  prefixId: string;
}

export const DosPrefixResponse: ResourceBinding<DosPrefixResponseConfig, DosPrefixResponseAttrs> = {
  wireType: "cloudflare_dos_prefix_response",
  fields: {
    comment: "comment",
    excluded: "excluded",
    prefix: "prefix",
    accountId: "account_id",
    prefixId: "prefix_id",
  },
};
