# Code generated by `ubx sdk gen` from cloudflare_resource_sharing_share_recipient_response_collection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ShareRecipientResponseCollection_Result_Resources:
    error: Any = None
    resource_id: Any = None
    resource_version: Any = None
    terminal: Any = None

@dataclasses.dataclass
class ShareRecipientResponseCollection_Result:
    account_id: Any = None
    association_status: Any = None
    created: Any = None
    id: Any = None
    modified: Any = None
    resources: Any = None

@dataclasses.dataclass
class ShareRecipientResponseCollectionConfig:
    # Account identifier.
    account_id: Any = None
    include_resources: Any = None
    page: Any = None
    per_page: Any = None
    # Share identifier tag.
    share_id: Any = None

@dataclasses.dataclass
class ShareRecipientResponseCollectionAttrs:
    # Account identifier.
    account_id: Any = None
    include_resources: Any = None
    page: Any = None
    per_page: Any = None
    result: Any = None
    # Share identifier tag.
    share_id: Any = None

ShareRecipientResponseCollection = ubx.DataSourceBinding(
    wire_type="cloudflare_resource_sharing_share_recipient_response_collection",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "include_resources": ubx.FieldSpec(wire_name="include_resources"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "share_id": ubx.FieldSpec(wire_name="share_id"),
    },
)
