// Code generated by `ubx sdk gen` from cloudflare_iam_collection_role_response. DO NOT EDIT.
package accountroles

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IamCollectionRoleResponse_AccountId struct {
}

var IamCollectionRoleResponse_AccountIdFields = ubx.FieldMap{
	}

type IamCollectionRoleResponseConfig struct {
	// Account identifier tag.
	AccountId any
	// Page number of paginated results.
	Page any
	// Number of roles per page.
	PerPage any
}

type IamCollectionRoleResponseAttrs struct {
	// Account identifier tag.
	AccountId any
	// Page number of paginated results.
	Page any
	// Number of roles per page.
	PerPage any
}

var IamCollectionRoleResponse = ubx.DataSourceBinding{
	WireType: "cloudflare_iam_collection_role_response",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{
			WireName: "account_id",
			Kind: "object",
			Fields: IamCollectionRoleResponse_AccountIdFields,
		},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
