// Code generated by `ubx sdk gen` from cloudflare_logpush_logpush_field_response_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface LogpushLogpushFieldResponseCollectionConfig {
  /** Identifier. */
  accountId: string | Computed<string>;
  /** Name of the dataset. A list of supported datasets can be found on the [Developer Docs](https://developers.cloudflare.com/logs/reference/log-fields/). */
  datasetId: string | Computed<string>;
}

export interface LogpushLogpushFieldResponseCollectionAttrs {
  /** Identifier. */
  accountId: string;
  /** Name of the dataset. A list of supported datasets can be found on the [Developer Docs](https://developers.cloudflare.com/logs/reference/log-fields/). */
  datasetId: string;
}

export const LogpushLogpushFieldResponseCollection: DataSourceBinding<LogpushLogpushFieldResponseCollectionConfig, LogpushLogpushFieldResponseCollectionAttrs> = {
  wireType: "cloudflare_logpush_logpush_field_response_collection",
  fields: {
    accountId: "account_id",
    datasetId: "dataset_id",
  },
};
