# Code generated by `ubx sdk gen` from cloudflare_content_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ContentPolicy_CreatedAt:
    pass

@dataclasses.dataclass
class ContentPolicy_Result:
    created_at: Any = None
    enabled: Any = None
    id: Any = None
    modified_at: Any = None
    name: Any = None
    notes: Any = None
    pattern: Any = None
    targets: Any = None

@dataclasses.dataclass
class ContentPolicyConfig:
    # Whether this content policy is currently active. (AI-inferred)
    enabled: Any = None
    # This content policy's own real, human-readable name. (AI-inferred)
    name: Any = None
    # A free-text note about this content policy. (AI-inferred)
    notes: Any = None
    # The content pattern this policy matches against. (AI-inferred)
    pattern: Any = None
    # The real set of message parts (subject, body, attachments) this policy enforces against. (AI-inferred)
    targets: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    policy_id: Any = None

@dataclasses.dataclass
class ContentPolicyAttrs:
    # When this content policy was created. (AI-inferred)
    created_at: Any = None
    # Whether this content policy is currently active. (AI-inferred)
    enabled: Any = None
    # This content policy's own real identifier. (AI-inferred)
    id: Any = None
    # When this content policy was last modified. (AI-inferred)
    modified_at: Any = None
    # This content policy's own real, human-readable name. (AI-inferred)
    name: Any = None
    # A free-text note about this content policy. (AI-inferred)
    notes: Any = None
    # The content pattern this policy matches against. (AI-inferred)
    pattern: Any = None
    # A content policy pattern that matches against the subject or body of an email.
    result: Any = None
    # The real set of message parts (subject, body, attachments) this policy enforces against. (AI-inferred)
    targets: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    policy_id: Any = None

ContentPolicy = ubx.ResourceBinding(
    wire_type="cloudflare_content_policy",
    fields={
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "name": ubx.FieldSpec(wire_name="name"),
        "notes": ubx.FieldSpec(wire_name="notes"),
        "pattern": ubx.FieldSpec(wire_name="pattern"),
        "targets": ubx.FieldSpec(wire_name="targets"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "policy_id": ubx.FieldSpec(wire_name="policy_id"),
    },
)
