// Code generated by `ubx sdk gen` from cloudflare_stream_video_response_collection. DO NOT EDIT.
package streamvideos

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type StreamVideoResponseCollectionConfig struct {
	// The account identifier tag.
	AccountId any
	After any
	// Lists videos in ascending order of creation.
	Asc any
	Before any
	// A user-defined identifier for the media creator.
	Creator any
	// Lists videos created before the specified date.
	End any
	Id any
	// Includes the total number of videos associated with the submitted query parameters.
	IncludeCounts any
	Limit any
	LiveInputId any
	Name any
	// Provides a partial word match of the `name` key in the `meta` field. Slow for medium to large video libraries. May be unavailable for very large libraries.
	Search any
	// Lists videos created after the specified date.
	Start any
	// Specifies the processing status for all quality levels for a video.
	Status any
	// Specifies whether the video is `vod` or `live`.
	Type any
	// Provides a fast, exact string match on the `name` key in the `meta` field.
	VideoName any
}

type StreamVideoResponseCollectionAttrs struct {
	// The account identifier tag.
	AccountId any
	After any
	// Lists videos in ascending order of creation.
	Asc any
	Before any
	// A user-defined identifier for the media creator.
	Creator any
	// Lists videos created before the specified date.
	End any
	Id any
	// Includes the total number of videos associated with the submitted query parameters.
	IncludeCounts any
	Limit any
	LiveInputId any
	Name any
	// Provides a partial word match of the `name` key in the `meta` field. Slow for medium to large video libraries. May be unavailable for very large libraries.
	Search any
	// Lists videos created after the specified date.
	Start any
	// Specifies the processing status for all quality levels for a video.
	Status any
	// Specifies whether the video is `vod` or `live`.
	Type any
	// Provides a fast, exact string match on the `name` key in the `meta` field.
	VideoName any
}

var StreamVideoResponseCollection = ubx.DataSourceBinding{
	WireType: "cloudflare_stream_video_response_collection",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"After": ubx.FieldSpec{WireName: "after"},
		"Asc": ubx.FieldSpec{WireName: "asc"},
		"Before": ubx.FieldSpec{WireName: "before"},
		"Creator": ubx.FieldSpec{WireName: "creator"},
		"End": ubx.FieldSpec{WireName: "end"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"IncludeCounts": ubx.FieldSpec{WireName: "include_counts"},
		"Limit": ubx.FieldSpec{WireName: "limit"},
		"LiveInputId": ubx.FieldSpec{WireName: "live_input_id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Search": ubx.FieldSpec{WireName: "search"},
		"Start": ubx.FieldSpec{WireName: "start"},
		"Status": ubx.FieldSpec{WireName: "status"},
		"Type": ubx.FieldSpec{WireName: "type"},
		"VideoName": ubx.FieldSpec{WireName: "video_name"},
	},
}
