// Code generated by `ubx sdk gen` from cloudflare_access_response_collection_23. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AccessResponseCollection23Config {
  /** UUID. */
  appId: string | Computed<string>;
  /** Identifier. */
  zoneId: string | Computed<string>;
}

export interface AccessResponseCollection23Attrs {
  /** UUID. */
  appId: string;
  /** Identifier. */
  zoneId: string;
}

export const AccessResponseCollection23: DataSourceBinding<AccessResponseCollection23Config, AccessResponseCollection23Attrs> = {
  wireType: "cloudflare_access_response_collection_23",
  fields: {
    appId: "app_id",
    zoneId: "zone_id",
  },
};
