# Code generated by `ubx sdk gen` from cloudflare_cache_reserve. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CacheReserveConfig:
    pass

@dataclasses.dataclass
class CacheReserveAttrs:
    # Identifier.
    zone_id: Any = None

CacheReserve = ubx.DataSourceBinding(
    wire_type="cloudflare_cache_reserve",
    fields={
    },
)
