// Code generated by `ubx sdk gen` from cloudflare_lock. DO NOT EDIT.
package r2bucket

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LockConfig struct {
	// Account ID.
	AccountId any
	// Name of the bucket.
	BucketName any
}

type LockAttrs struct {
	// Account ID.
	AccountId any
	// Name of the bucket.
	BucketName any
}

var Lock = ubx.DataSourceBinding{
	WireType: "cloudflare_lock",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"BucketName": ubx.FieldSpec{WireName: "bucket_name"},
	},
}
