// Code generated by `ubx sdk gen` from cloudflare_analytics_engine_json_format_response. DO NOT EDIT.
package analyticsengine

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type JsonFormatResponse_Meta struct {
	Name any
	Type any
}

type JsonFormatResponseConfig struct {
	Query any
}

type JsonFormatResponseAttrs struct {
	// Array of result rows. Each row is an object with keys corresponding to the selected columns.
	Data any
	// Column metadata describing the name and type of each column in the result set.
	Meta  any
	Query any
	// Total number of rows in the result set.
	Rows any
}

var JsonFormatResponse = ubx.DataSourceBinding{
	WireType: "cloudflare_analytics_engine_json_format_response",
	Fields: ubx.FieldMap{
		"Query": ubx.FieldSpec{WireName: "query"},
	},
}
