// Code generated by `ubx sdk gen` from cloudflare_access_single_response_17. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccessSingleResponse17_Exclude_AuthContext {
  acId?: string | Computed<string>;
  id?: string | Computed<string>;
  identityProviderId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_AuthMethod {
  authMethod?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_AzureAd {
  id?: string | Computed<string>;
  identityProviderId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_CloudflareAccountMember {
  accountId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_CommonName {
  commonName?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_DevicePosture {
  integrationUid?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Email {
  email?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_EmailDomain {
  domain?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_EmailList {
  id?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_ExternalEvaluation {
  evaluateUrl?: string | Computed<string>;
  keysUrl?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Geo {
  countryCode?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_GithubOrganization {
  identityProviderId?: string | Computed<string>;
  name?: string | Computed<string>;
  team?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Gsuite {
  email?: string | Computed<string>;
  identityProviderId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Ip {
  ip?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_LinkedAppToken {
  appUid?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Oidc {
  claimName?: string | Computed<string>;
  claimValue?: string | Computed<string>;
  identityProviderId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Okta {
  identityProviderId?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_Saml {
  attributeName?: string | Computed<string>;
  attributeValue?: string | Computed<string>;
  identityProviderId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_ServiceToken {
  tokenId?: string | Computed<string>;
}

export interface AccessSingleResponse17_Exclude_UserRiskScore {
  userRiskScore?: string[] | Computed<string[]>;
}

export interface AccessSingleResponse17_Exclude {
  anyValidServiceToken?: unknown | Computed<unknown>;
  authContext?: AccessSingleResponse17_Exclude_AuthContext | Computed<AccessSingleResponse17_Exclude_AuthContext>;
  authMethod?: AccessSingleResponse17_Exclude_AuthMethod | Computed<AccessSingleResponse17_Exclude_AuthMethod>;
  azureAd?: AccessSingleResponse17_Exclude_AzureAd | Computed<AccessSingleResponse17_Exclude_AzureAd>;
  certificate?: unknown | Computed<unknown>;
  cloudflareAccountMember?: AccessSingleResponse17_Exclude_CloudflareAccountMember | Computed<AccessSingleResponse17_Exclude_CloudflareAccountMember>;
  commonName?: AccessSingleResponse17_Exclude_CommonName | Computed<AccessSingleResponse17_Exclude_CommonName>;
  devicePosture?: AccessSingleResponse17_Exclude_DevicePosture | Computed<AccessSingleResponse17_Exclude_DevicePosture>;
  email?: AccessSingleResponse17_Exclude_Email | Computed<AccessSingleResponse17_Exclude_Email>;
  emailDomain?: AccessSingleResponse17_Exclude_EmailDomain | Computed<AccessSingleResponse17_Exclude_EmailDomain>;
  emailList?: AccessSingleResponse17_Exclude_EmailList | Computed<AccessSingleResponse17_Exclude_EmailList>;
  everyone?: unknown | Computed<unknown>;
  externalEvaluation?: AccessSingleResponse17_Exclude_ExternalEvaluation | Computed<AccessSingleResponse17_Exclude_ExternalEvaluation>;
  geo?: AccessSingleResponse17_Exclude_Geo | Computed<AccessSingleResponse17_Exclude_Geo>;
  githubOrganization?: AccessSingleResponse17_Exclude_GithubOrganization | Computed<AccessSingleResponse17_Exclude_GithubOrganization>;
  group?: AccessSingleResponse17_Exclude_EmailList | Computed<AccessSingleResponse17_Exclude_EmailList>;
  gsuite?: AccessSingleResponse17_Exclude_Gsuite | Computed<AccessSingleResponse17_Exclude_Gsuite>;
  ip?: AccessSingleResponse17_Exclude_Ip | Computed<AccessSingleResponse17_Exclude_Ip>;
  ipList?: AccessSingleResponse17_Exclude_EmailList | Computed<AccessSingleResponse17_Exclude_EmailList>;
  linkedAppToken?: AccessSingleResponse17_Exclude_LinkedAppToken | Computed<AccessSingleResponse17_Exclude_LinkedAppToken>;
  loginMethod?: AccessSingleResponse17_Exclude_EmailList | Computed<AccessSingleResponse17_Exclude_EmailList>;
  oidc?: AccessSingleResponse17_Exclude_Oidc | Computed<AccessSingleResponse17_Exclude_Oidc>;
  okta?: AccessSingleResponse17_Exclude_Okta | Computed<AccessSingleResponse17_Exclude_Okta>;
  saml?: AccessSingleResponse17_Exclude_Saml | Computed<AccessSingleResponse17_Exclude_Saml>;
  serviceToken?: AccessSingleResponse17_Exclude_ServiceToken | Computed<AccessSingleResponse17_Exclude_ServiceToken>;
  userRiskScore?: AccessSingleResponse17_Exclude_UserRiskScore | Computed<AccessSingleResponse17_Exclude_UserRiskScore>;
}

const AccessSingleResponse17_Exclude_AuthContextFields: FieldMap = {
  acId: "ac_id",
  id: "id",
  identityProviderId: "identity_provider_id",
};

const AccessSingleResponse17_Exclude_AuthMethodFields: FieldMap = {
  authMethod: "auth_method",
};

const AccessSingleResponse17_Exclude_AzureAdFields: FieldMap = {
  id: "id",
  identityProviderId: "identity_provider_id",
};

const AccessSingleResponse17_Exclude_CloudflareAccountMemberFields: FieldMap = {
  accountId: "account_id",
};

const AccessSingleResponse17_Exclude_CommonNameFields: FieldMap = {
  commonName: "common_name",
};

const AccessSingleResponse17_Exclude_DevicePostureFields: FieldMap = {
  integrationUid: "integration_uid",
};

const AccessSingleResponse17_Exclude_EmailFields: FieldMap = {
  email: "email",
};

const AccessSingleResponse17_Exclude_EmailDomainFields: FieldMap = {
  domain: "domain",
};

const AccessSingleResponse17_Exclude_EmailListFields: FieldMap = {
  id: "id",
};

const AccessSingleResponse17_Exclude_ExternalEvaluationFields: FieldMap = {
  evaluateUrl: "evaluate_url",
  keysUrl: "keys_url",
};

const AccessSingleResponse17_Exclude_GeoFields: FieldMap = {
  countryCode: "country_code",
};

const AccessSingleResponse17_Exclude_GithubOrganizationFields: FieldMap = {
  identityProviderId: "identity_provider_id",
  name: "name",
  team: "team",
};

const AccessSingleResponse17_Exclude_GsuiteFields: FieldMap = {
  email: "email",
  identityProviderId: "identity_provider_id",
};

const AccessSingleResponse17_Exclude_IpFields: FieldMap = {
  ip: "ip",
};

const AccessSingleResponse17_Exclude_LinkedAppTokenFields: FieldMap = {
  appUid: "app_uid",
};

const AccessSingleResponse17_Exclude_OidcFields: FieldMap = {
  claimName: "claim_name",
  claimValue: "claim_value",
  identityProviderId: "identity_provider_id",
};

const AccessSingleResponse17_Exclude_OktaFields: FieldMap = {
  identityProviderId: "identity_provider_id",
  name: "name",
};

const AccessSingleResponse17_Exclude_SamlFields: FieldMap = {
  attributeName: "attribute_name",
  attributeValue: "attribute_value",
  identityProviderId: "identity_provider_id",
};

const AccessSingleResponse17_Exclude_ServiceTokenFields: FieldMap = {
  tokenId: "token_id",
};

const AccessSingleResponse17_Exclude_UserRiskScoreFields: FieldMap = {
  userRiskScore: "user_risk_score",
};

const AccessSingleResponse17_ExcludeFields: FieldMap = {
  anyValidServiceToken: "any_valid_service_token",
  authContext: {
    wireName: "auth_context",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_AuthContextFields,
  },
  authMethod: {
    wireName: "auth_method",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_AuthMethodFields,
  },
  azureAd: {
    wireName: "azure_ad",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_AzureAdFields,
  },
  certificate: "certificate",
  cloudflareAccountMember: {
    wireName: "cloudflare_account_member",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_CloudflareAccountMemberFields,
  },
  commonName: {
    wireName: "common_name",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_CommonNameFields,
  },
  devicePosture: {
    wireName: "device_posture",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_DevicePostureFields,
  },
  email: {
    wireName: "email",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_EmailFields,
  },
  emailDomain: {
    wireName: "email_domain",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_EmailDomainFields,
  },
  emailList: {
    wireName: "email_list",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_EmailListFields,
  },
  everyone: "everyone",
  externalEvaluation: {
    wireName: "external_evaluation",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_ExternalEvaluationFields,
  },
  geo: {
    wireName: "geo",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_GeoFields,
  },
  githubOrganization: {
    wireName: "github_organization",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_GithubOrganizationFields,
  },
  group: {
    wireName: "group",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_EmailListFields,
  },
  gsuite: {
    wireName: "gsuite",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_GsuiteFields,
  },
  ip: {
    wireName: "ip",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_IpFields,
  },
  ipList: {
    wireName: "ip_list",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_EmailListFields,
  },
  linkedAppToken: {
    wireName: "linked_app_token",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_LinkedAppTokenFields,
  },
  loginMethod: {
    wireName: "login_method",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_EmailListFields,
  },
  oidc: {
    wireName: "oidc",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_OidcFields,
  },
  okta: {
    wireName: "okta",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_OktaFields,
  },
  saml: {
    wireName: "saml",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_SamlFields,
  },
  serviceToken: {
    wireName: "service_token",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_ServiceTokenFields,
  },
  userRiskScore: {
    wireName: "user_risk_score",
    kind: "object",
    fields: AccessSingleResponse17_Exclude_UserRiskScoreFields,
  },
};

export interface AccessSingleResponse17Config {
  /** Rules evaluated with a NOT logical operator. To match a policy, a user cannot meet any of the Exclude rules. */
  exclude?: AccessSingleResponse17_Exclude[] | Computed<AccessSingleResponse17_Exclude[]>;
  /** Rules evaluated with an OR logical operator. A user needs to meet only one of the Include rules. */
  include: AccessSingleResponse17_Exclude[] | Computed<AccessSingleResponse17_Exclude[]>;
  /** The name of the Access group. */
  name: string | Computed<string>;
  /** Rules evaluated with an AND logical operator. To match a policy, a user must meet all of the Require rules. */
  require?: AccessSingleResponse17_Exclude[] | Computed<AccessSingleResponse17_Exclude[]>;
  /** path parameter, not part of the API's own resource representation */
  zoneId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  groupId: string | Computed<string>;
}

export interface AccessSingleResponse17Attrs {
  /** Rules evaluated with a NOT logical operator. To match a policy, a user cannot meet any of the Exclude rules. */
  exclude: AccessSingleResponse17_Exclude[];
  /** Rules evaluated with an OR logical operator. A user needs to meet only one of the Include rules. */
  include: AccessSingleResponse17_Exclude[];
  /** The name of the Access group. */
  name: string;
  /** Rules evaluated with an AND logical operator. To match a policy, a user must meet all of the Require rules. */
  require: AccessSingleResponse17_Exclude[];
  /** path parameter, not part of the API's own resource representation */
  zoneId: string;
  /** path parameter, not part of the API's own resource representation */
  groupId: string;
}

export const AccessSingleResponse17: ResourceBinding<AccessSingleResponse17Config, AccessSingleResponse17Attrs> = {
  wireType: "cloudflare_access_single_response_17",
  fields: {
    exclude: {
      wireName: "exclude",
      kind: "list",
      fields: AccessSingleResponse17_ExcludeFields,
    },
    include: {
      wireName: "include",
      kind: "list",
      fields: AccessSingleResponse17_ExcludeFields,
    },
    name: "name",
    require: {
      wireName: "require",
      kind: "list",
      fields: AccessSingleResponse17_ExcludeFields,
    },
    zoneId: "zone_id",
    groupId: "group_id",
  },
};
