# Code generated by `ubx sdk gen` from cloudflare_origin_max_http_version. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OriginMaxHttpVersionConfig:
    pass

@dataclasses.dataclass
class OriginMaxHttpVersionAttrs:
    # Identifier.
    zone_id: Any = None

OriginMaxHttpVersion = ubx.DataSourceBinding(
    wire_type="cloudflare_origin_max_http_version",
    fields={
    },
)
