// Code generated by `ubx sdk gen` from cloudflare_intel_sinkholes_ingress_single_response. DO NOT EDIT.
package sinkholeconfig

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IntelSinkholesIngressSingleResponse_Errors_Source struct {
	Pointer any
}

type IntelSinkholesIngressSingleResponse_Errors struct {
	Code             any
	DocumentationUrl any
	Message          any
	Source           any
}

type IntelSinkholesIngressSingleResponse_Result struct {
	// The CIDR block for the ingress rule.
	Cidr any
	// The date and time when the ingress rule was created.
	CreatedOn any
	// The unique identifier for the ingress rule.
	Id any
	// The date and time when the ingress rule was last modified.
	ModifiedOn any
	// The sinkhole this ingress rule belongs to.
	SinkholeId any
	// The zone tag associated with this ingress rule.
	ZoneTag any
}

type IntelSinkholesIngressSingleResponseConfig struct {
	// The CIDR block for the ingress rule in IPv4 or IPv6 notation (e.g., 192.0.2.0/24). Provide a Cloudflare BYOIP CIDR that your account owns.
	Cidr any
	// path parameter, not part of the API's own resource representation
	ZoneId any
	// path parameter, not part of the API's own resource representation
	SinkholeId any
	// path parameter, not part of the API's own resource representation
	IngressId any
}

type IntelSinkholesIngressSingleResponseAttrs struct {
	// The CIDR block for the ingress rule in IPv4 or IPv6 notation (e.g., 192.0.2.0/24). Provide a Cloudflare BYOIP CIDR that your account owns.
	Cidr any
	// Errors returned by the API call, empty when the call succeeds. (AI-inferred)
	Errors any
	// Informational messages returned alongside the API call's own result. (AI-inferred)
	Messages any
	Result   any
	// Whether the API call was successful.
	Success any
	// path parameter, not part of the API's own resource representation
	ZoneId any
	// path parameter, not part of the API's own resource representation
	SinkholeId any
	// path parameter, not part of the API's own resource representation
	IngressId any
}

var IntelSinkholesIngressSingleResponse = ubx.ResourceBinding{
	WireType: "cloudflare_intel_sinkholes_ingress_single_response",
	Fields: ubx.FieldMap{
		"Cidr":       ubx.FieldSpec{WireName: "cidr"},
		"ZoneId":     ubx.FieldSpec{WireName: "zone_id"},
		"SinkholeId": ubx.FieldSpec{WireName: "sinkhole_id"},
		"IngressId":  ubx.FieldSpec{WireName: "ingress_id"},
	},
}
