// Code generated by `ubx sdk gen` from cloudflare_argo_analytics_response_single. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ArgoAnalyticsResponseSingleConfig {
  bins?: string | Computed<string>;
}

export interface ArgoAnalyticsResponseSingleAttrs {
  bins: string;
  /** Identifier */
  zoneId: string;
}

export const ArgoAnalyticsResponseSingle: DataSourceBinding<ArgoAnalyticsResponseSingleConfig, ArgoAnalyticsResponseSingleAttrs> = {
  wireType: "cloudflare_argo_analytics_response_single",
  fields: {
    bins: "bins",
  },
};
