// Code generated by `ubx sdk gen` from cloudflare_bulk. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Bulk_Result_ActionParams {
  destination?: string | Computed<string>;
  expectedDisposition?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Bulk_Result_SearchParams {
  /** Deprecated, use `GET /investigate/{investigate_id}/action_log` instead. End of life: November 1, 2026. */
  actionLog?: boolean | Computed<boolean>;
  alertId?: string | Computed<string>;
  /** Delivery status of the message. */
  deliveryStatus?: string | Computed<string>;
  detectionsOnly?: boolean | Computed<boolean>;
  domain?: string | Computed<string>;
  /** End of search date range. */
  end?: string | Computed<string>;
  exactSubject?: string | Computed<string>;
  finalDisposition?: string | Computed<string>;
  messageAction?: string | Computed<string>;
  messageId?: string | Computed<string>;
  metric?: string | Computed<string>;
  query?: string | Computed<string>;
  recipient?: string | Computed<string>;
  sender?: string | Computed<string>;
  /** Matches messages whose SMTP HELO server IP address equals this value. */
  smtpHeloIp?: string | Computed<string>;
  /** Beginning of search date range. */
  start?: string | Computed<string>;
  subject?: string | Computed<string>;
  submissions?: boolean | Computed<boolean>;
}

export interface Bulk_Result {
  actionParams: Bulk_Result_ActionParams | Computed<Bulk_Result_ActionParams>;
  actionType: string | Computed<string>;
  comment?: string | Computed<string>;
  completedAt?: string | Computed<string>;
  createdAt: string | Computed<string>;
  jobId: string | Computed<string>;
  messagesFailed: number | Computed<number>;
  messagesPending: number | Computed<number>;
  messagesSuccessful: number | Computed<number>;
  searchParams: Bulk_Result_SearchParams | Computed<Bulk_Result_SearchParams>;
  startedAt?: string | Computed<string>;
  status: string | Computed<string>;
  statusMessage?: string | Computed<string>;
  totalMessagesDiscovered: number | Computed<number>;
}

const Bulk_Result_SearchParamsFields: FieldMap = {
  actionLog: "action_log",
  alertId: "alert_id",
  deliveryStatus: "delivery_status",
  detectionsOnly: "detections_only",
  domain: "domain",
  end: "end",
  exactSubject: "exact_subject",
  finalDisposition: "final_disposition",
  messageAction: "message_action",
  messageId: "message_id",
  metric: "metric",
  query: "query",
  recipient: "recipient",
  sender: "sender",
  smtpHeloIp: "smtp_helo_ip",
  start: "start",
  subject: "subject",
  submissions: "submissions",
};

export interface BulkConfig {
  action: string | Computed<string>;
  comment?: string | Computed<string>;
  destination?: string | Computed<string>;
  expectedDisposition?: string | Computed<string>;
  searchParams: Bulk_Result_SearchParams | Computed<Bulk_Result_SearchParams>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  jobId: string | Computed<string>;
}

export interface BulkAttrs {
  action: string;
  comment: string;
  destination: string;
  expectedDisposition: string;
  result: Bulk_Result;
  searchParams: Bulk_Result_SearchParams;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  jobId: string;
}

export const Bulk: ResourceBinding<BulkConfig, BulkAttrs> = {
  wireType: "cloudflare_bulk",
  fields: {
    action: "action",
    comment: "comment",
    destination: "destination",
    expectedDisposition: "expected_disposition",
    searchParams: {
      wireName: "search_params",
      kind: "object",
      fields: Bulk_Result_SearchParamsFields,
    },
    accountId: "account_id",
    jobId: "job_id",
  },
};
