# Code generated by `ubx sdk gen` from cloudflare_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class KeyConfig:
    # Opaque token indicating the position from which to continue when requesting the next set of records if the amount of list results was limited by the limit parameter. A valid value for the cursor can be obtained from the `cursors` object in the `result_info` structure.
    cursor: Any = None
    # Limits the number of keys returned in the response. The cursor attribute may be used to iterate over the next batch of keys if there are more than the limit.
    limit: Any = None
    # Filters returned keys by a name prefix. Exact matches and any key names that begin with the prefix will be returned.
    prefix: Any = None

@dataclasses.dataclass
class KeyAttrs:
    # Identifier.
    account_id: Any = None
    # Opaque token indicating the position from which to continue when requesting the next set of records if the amount of list results was limited by the limit parameter. A valid value for the cursor can be obtained from the `cursors` object in the `result_info` structure.
    cursor: Any = None
    # Limits the number of keys returned in the response. The cursor attribute may be used to iterate over the next batch of keys if there are more than the limit.
    limit: Any = None
    # Namespace identifier tag.
    namespace_id: Any = None
    # Filters returned keys by a name prefix. Exact matches and any key names that begin with the prefix will be returned.
    prefix: Any = None

Key = ubx.DataSourceBinding(
    wire_type="cloudflare_key",
    fields={
        "cursor": ubx.FieldSpec(wire_name="cursor"),
        "limit": ubx.FieldSpec(wire_name="limit"),
        "prefix": ubx.FieldSpec(wire_name="prefix"),
    },
)
