// Code generated by `ubx sdk gen` from cloudflare_suppression. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Suppression_Result {
  createdAt?: string | Computed<string>;
  email?: string | Computed<string>;
  expiresAt?: string | Computed<string>;
  id?: string | Computed<string>;
  reason?: string | Computed<string>;
  zones?: string[] | Computed<string[]>;
}

export interface SuppressionConfig {
  accountId: string | Computed<string>;
  direction?: string | Computed<string>;
  order?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface SuppressionAttrs {
  accountId: string;
  direction: string;
  order: string;
  page: number;
  perPage: number;
  result: Suppression_Result[];
  total: number;
}

export const Suppression: DataSourceBinding<SuppressionConfig, SuppressionAttrs> = {
  wireType: "cloudflare_suppression",
  fields: {
    accountId: "account_id",
    direction: "direction",
    order: "order",
    page: "page",
    perPage: "per_page",
  },
};
