// Code generated by `ubx sdk gen` from cloudflare_tunnel_cfd_tunnel_response_single. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface TunnelCfdTunnelResponseSingleConfig {
  /** Indicates if this is a locally or remotely configured tunnel. If `local`, manage the tunnel using a YAML file on the origin machine. If `cloudflare`, manage the tunnel on the Zero Trust dashboard. */
  configSrc?: string | Computed<string>;
  /** A user-friendly name for a tunnel. */
  name: string | Computed<string>;
  /** Sets the password required to run a locally-managed tunnel. Must be at least 32 bytes and encoded as a base64 string. */
  tunnelSecret?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  tunnelId: string | Computed<string>;
}

export interface TunnelCfdTunnelResponseSingleAttrs {
  /** Indicates if this is a locally or remotely configured tunnel. If `local`, manage the tunnel using a YAML file on the origin machine. If `cloudflare`, manage the tunnel on the Zero Trust dashboard. */
  configSrc: string;
  /** A user-friendly name for a tunnel. */
  name: string;
  /** Sets the password required to run a locally-managed tunnel. Must be at least 32 bytes and encoded as a base64 string. */
  tunnelSecret: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  tunnelId: string;
}

export const TunnelCfdTunnelResponseSingle: ResourceBinding<TunnelCfdTunnelResponseSingleConfig, TunnelCfdTunnelResponseSingleAttrs> = {
  wireType: "cloudflare_tunnel_cfd_tunnel_response_single",
  fields: {
    configSrc: "config_src",
    name: "name",
    tunnelSecret: "tunnel_secret",
    accountId: "account_id",
    tunnelId: "tunnel_id",
  },
};
