# Code generated by `ubx sdk gen` from cloudflare_teams_devices_components_schemas_response_collection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TeamsDevicesComponentsSchemasResponseCollectionConfig:
    account_id: Any = None

@dataclasses.dataclass
class TeamsDevicesComponentsSchemasResponseCollectionAttrs:
    account_id: Any = None

TeamsDevicesComponentsSchemasResponseCollection = ubx.DataSourceBinding(
    wire_type="cloudflare_teams_devices_components_schemas_response_collection",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
