# Code generated by `ubx sdk gen` from cloudflare_group. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Group_Members:
    account_id: Any = None
    account_tag: Any = None
    created_at: Any = None
    updated_at: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GroupConfig:
    description: Any = None
    name: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    group_id: Any = None

@dataclasses.dataclass
class GroupAttrs:
    created_at: Any = None
    description: Any = None
    members: Any = None
    name: Any = None
    updated_at: Any = None
    uuid: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    group_id: Any = None

Group = ubx.ResourceBinding(
    wire_type="cloudflare_group",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "name": ubx.FieldSpec(wire_name="name"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "group_id": ubx.FieldSpec(wire_name="group_id"),
    },
)
