// Code generated by `ubx sdk gen` from cloudflare_member. DO NOT EDIT.
package accountusergroupmembers

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Member_Result_User struct {
	// The contact email address of the user.
	Email any
	// User's first name.
	FirstName any
	// User identifier tag.
	Id any
	// User's last name.
	LastName any
}

type Member_Result struct {
	// When the member was added to the user group.
	CreatedAt any
	// The contact email address of the user.
	Email any
	// Account member identifier.
	Id any
	// The member's status in the account.
	Status any
	// Details of the user associated with this membership.
	User any
}

type MemberConfig struct {
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	UserGroupId any
	// path parameter, not part of the API's own resource representation
	MemberId any
}

type MemberAttrs struct {
	// Detailed member information for a User Group member.
	Result any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	UserGroupId any
	// path parameter, not part of the API's own resource representation
	MemberId any
}

var Member = ubx.ResourceBinding{
	WireType: "cloudflare_member",
	Fields: ubx.FieldMap{
		"AccountId":   ubx.FieldSpec{WireName: "account_id"},
		"UserGroupId": ubx.FieldSpec{WireName: "user_group_id"},
		"MemberId":    ubx.FieldSpec{WireName: "member_id"},
	},
}
