// Code generated by `ubx sdk gen` from cloudflare_tls_certificates_and_hostnames_custom_trust_store_response_collection. DO NOT EDIT.
package customorigintruststore

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TlsCertificatesAndHostnamesCustomTrustStoreResponseCollectionConfig struct {
	// Limit to the number of records returned.
	Limit any
	// Offset the results.
	Offset any
	// Page number of paginated results.
	Page any
	// Number of records per page.
	PerPage any
	// Identifier.
	ZoneId any
}

type TlsCertificatesAndHostnamesCustomTrustStoreResponseCollectionAttrs struct {
	// Limit to the number of records returned.
	Limit any
	// Offset the results.
	Offset any
	// Page number of paginated results.
	Page any
	// Number of records per page.
	PerPage any
	// Identifier.
	ZoneId any
}

var TlsCertificatesAndHostnamesCustomTrustStoreResponseCollection = ubx.DataSourceBinding{
	WireType: "cloudflare_tls_certificates_and_hostnames_custom_trust_store_response_collection",
	Fields: ubx.FieldMap{
		"Limit": ubx.FieldSpec{WireName: "limit"},
		"Offset": ubx.FieldSpec{WireName: "offset"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
	},
}
