# Code generated by `ubx sdk gen` from cloudflare_access_response_collection_9. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AccessResponseCollection9Config:
    # Identifier.
    account_id: Any = None
    # Page number of results.
    page: Any = None
    # Number of results per page.
    per_page: Any = None

@dataclasses.dataclass
class AccessResponseCollection9Attrs:
    # Identifier.
    account_id: Any = None
    # Page number of results.
    page: Any = None
    # Number of results per page.
    per_page: Any = None

AccessResponseCollection9 = ubx.DataSourceBinding(
    wire_type="cloudflare_access_response_collection_9",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
