// Code generated by `ubx sdk gen` from cloudflare_dkim. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Dkim_Result_Meta_ConfidenceInfo_Annotations {
  dataSource?: string | Computed<string>;
  description?: string | Computed<string>;
  endDate?: string | Computed<string>;
  eventType?: string | Computed<string>;
  isInstantaneous?: boolean | Computed<boolean>;
  linkedUrl?: string | Computed<string>;
  startDate?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
}

export interface Dkim_Result_Meta_ConfidenceInfo {
  annotations: Dkim_Result_Meta_ConfidenceInfo_Annotations[] | Computed<Dkim_Result_Meta_ConfidenceInfo_Annotations[]>;
  /** Provides an indication of how much confidence Cloudflare has in the data. */
  level: number | Computed<number>;
}

export interface Dkim_Result_Meta_DateRange {
  endTime?: string | Computed<string>;
  startTime?: string | Computed<string>;
}

export interface Dkim_Result_Meta_Units {
  name?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface Dkim_Result_Meta {
  confidenceInfo: Dkim_Result_Meta_ConfidenceInfo | Computed<Dkim_Result_Meta_ConfidenceInfo>;
  dateRange: Dkim_Result_Meta_DateRange[] | Computed<Dkim_Result_Meta_DateRange[]>;
  /** Timestamp of the last dataset update. */
  lastUpdated: string | Computed<string>;
  /** Normalization method applied to the results. Refer to [Normalization methods](https://developers.cloudflare.com/radar/concepts/normalization/). */
  normalization: string | Computed<string>;
  /** Measurement units for the results. */
  units: Dkim_Result_Meta_Units[] | Computed<Dkim_Result_Meta_Units[]>;
}

export interface Dkim_Result_Summary0 {
  /** A numeric string. */
  fail: string | Computed<string>;
  /** A numeric string. */
  none: string | Computed<string>;
  /** A numeric string. */
  pass: string | Computed<string>;
}

export interface Dkim_Result {
  /** Metadata for the results. */
  meta: Dkim_Result_Meta | Computed<Dkim_Result_Meta>;
  summary0: Dkim_Result_Summary0 | Computed<Dkim_Result_Summary0>;
}

export interface DkimConfig {
  /** Filters results by ARC (Authenticated Received Chain) validation. */
  arc?: string[] | Computed<string[]>;
  /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
  dateEnd?: string[] | Computed<string[]>;
  /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
  dateRange?: string[] | Computed<string[]>;
  /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
  dateStart?: string[] | Computed<string[]>;
  /** Filters results by DMARC (Domain-based Message Authentication, Reporting and Conformance) validation status. */
  dmarc?: string[] | Computed<string[]>;
  /** Filters results by encryption status (encrypted vs. not-encrypted). */
  encrypted?: string[] | Computed<string[]>;
  /** Format in which results will be returned. */
  format?: string | Computed<string>;
  /** Filters results by IP version (Ipv4 vs. IPv6). */
  ipVersion?: string[] | Computed<string[]>;
  /** Array of names used to label the series in the response. */
  name?: string[] | Computed<string[]>;
  /** Filters results by SPF (Sender Policy Framework) validation status. */
  spf?: string[] | Computed<string[]>;
}

export interface DkimAttrs {
  /** Filters results by ARC (Authenticated Received Chain) validation. */
  arc: string[];
  /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
  dateEnd: string[];
  /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
  dateRange: string[];
  /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
  dateStart: string[];
  /** Filters results by DMARC (Domain-based Message Authentication, Reporting and Conformance) validation status. */
  dmarc: string[];
  /** Filters results by encryption status (encrypted vs. not-encrypted). */
  encrypted: string[];
  /** Format in which results will be returned. */
  format: string;
  /** Filters results by IP version (Ipv4 vs. IPv6). */
  ipVersion: string[];
  /** Array of names used to label the series in the response. */
  name: string[];
  result: Dkim_Result;
  /** Filters results by SPF (Sender Policy Framework) validation status. */
  spf: string[];
  success: boolean;
}

export const Dkim: DataSourceBinding<DkimConfig, DkimAttrs> = {
  wireType: "cloudflare_dkim",
  fields: {
    arc: "arc",
    dateEnd: "date_end",
    dateRange: "date_range",
    dateStart: "date_start",
    dmarc: "dmarc",
    encrypted: "encrypted",
    format: "format",
    ipVersion: "ip_version",
    name: "name",
    spf: "spf",
  },
};
