// Code generated by `ubx sdk gen` from cloudflare_access_single_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AccessSingleResponse_Result_CreatedAt {
}

export interface AccessSingleResponse_Result_CustomPages {
  /** The uid of the custom page to use when a user is denied access after failing a non-identity rule. */
  forbidden?: string | Computed<string>;
  /** The uid of the custom page to use when a user is denied access. */
  identityDenied?: string | Computed<string>;
}

export interface AccessSingleResponse_Result_LoginDesign {
  /** The background color on your login page. */
  backgroundColor?: string | Computed<string>;
  /** The text at the bottom of your login page. */
  footerText?: string | Computed<string>;
  /** The text at the top of your login page. */
  headerText?: string | Computed<string>;
  /** The URL of the logo on your login page. */
  logoPath?: string | Computed<string>;
  /** The text color on your login page. */
  textColor?: string | Computed<string>;
}

export interface AccessSingleResponse_Result_MfaConfig {
  /** Lists the MFA methods that users can authenticate with. The `piv_key` and `ssh_fido2_key` values are supported only for infrastructure applications. */
  allowedAuthenticators?: string[] | Computed<string[]>;
  /** Allows a user to skip MFA via Authentication Method Reference (AMR) matching when the AMR claim provided by the IdP the user used to authenticate contains "mfa". Must be in minutes (m) or hours (h). Minimum: 0m. Maximum: 720h (30 days). */
  amrMatchingSessionDuration?: string | Computed<string>;
  /** Specifies a Cloudflare List of required FIDO2 authenticator device AAGUIDs. */
  requiredAaguids?: string | Computed<string>;
  /** Defines the duration of an MFA session. Must be in minutes (m) or hours (h). Minimum: 0m. Maximum: 720h (30 days). Examples:`5m` or `24h`. */
  sessionDuration?: string | Computed<string>;
}

export interface AccessSingleResponse_Result_MfaPivKeyRequirements {
  /** Defines when a PIN is required to use the SSH key. Valid values: `never` (no PIN required), `once` (PIN required once per session), `always` (PIN required for each use). */
  pinPolicy?: string | Computed<string>;
  /** Requires the PIV key to be stored on a FIPS 140-2 Level 1 or higher validated device. */
  requireFipsDevice?: boolean | Computed<boolean>;
  /** Specifies the allowed SSH key sizes in bits. Valid sizes depend on key type. Ed25519 has a fixed key size and does not accept this parameter. */
  sshKeySize?: number[] | Computed<number[]>;
  /** Specifies the allowed SSH key types. Valid values are `ecdsa`, `ed25519`, and `rsa`. */
  sshKeyType?: string[] | Computed<string[]>;
  /** Defines when physical touch is required to use the SSH key. Valid values: `never` (no touch required), `always` (touch required for each use), `cached` (touch cached for 15 seconds). */
  touchPolicy?: string | Computed<string>;
}

export interface AccessSingleResponse_Result {
  /** When set to true, users can authenticate via WARP for any application in your organization. Application settings will take precedence over this value. */
  allowAuthenticateViaWarp?: boolean | Computed<boolean>;
  /** The unique subdomain assigned to your Zero Trust organization. */
  authDomain?: string | Computed<string>;
  /** When set to `true`, users skip the identity provider selection step during login. */
  autoRedirectToIdentity?: boolean | Computed<boolean>;
  createdAt?: AccessSingleResponse_Result_CreatedAt | Computed<AccessSingleResponse_Result_CreatedAt>;
  customPages?: AccessSingleResponse_Result_CustomPages | Computed<AccessSingleResponse_Result_CustomPages>;
  /** Determines whether to deny all requests to Cloudflare-protected resources that lack an associated Access application. If enabled, you must explicitly configure an Access application and policy to allow traffic to your Cloudflare-protected resources. For domains you want to be public across all subdomains, add the domain to the `deny_unmatched_requests_exempted_zone_names` array. */
  denyUnmatchedRequests?: boolean | Computed<boolean>;
  /** Contains zone names to exempt from the `deny_unmatched_requests` feature. Requests to a subdomain in an exempted zone will block unauthenticated traffic by default if there is a configured Access application and policy that matches the request. */
  denyUnmatchedRequestsExemptedZoneNames?: string[] | Computed<string[]>;
  /** Lock all settings as Read-Only in the Dashboard, regardless of user permission. Updates may only be made via the API or Terraform for this account when enabled. */
  isUiReadOnly?: boolean | Computed<boolean>;
  loginDesign?: AccessSingleResponse_Result_LoginDesign | Computed<AccessSingleResponse_Result_LoginDesign>;
  /** Configures multi-factor authentication (MFA) settings for an organization. */
  mfaConfig?: AccessSingleResponse_Result_MfaConfig | Computed<AccessSingleResponse_Result_MfaConfig>;
  /** Configures PIV key requirements for MFA using hardware security keys. */
  mfaPivKeyRequirements?: AccessSingleResponse_Result_MfaPivKeyRequirements | Computed<AccessSingleResponse_Result_MfaPivKeyRequirements>;
  /** Determines whether global MFA settings apply to applications by default. The organization must have MFA enabled with at least one authentication method and a session duration configured. Note: 'allowed_authenticators' cannot contain only the infrastructure SSH authenticators ('piv_key' and 'ssh_fido2_key') if the organization has any non-infrastructure applications. */
  mfaRequiredForAllApps?: boolean | Computed<boolean>;
  /** The name of your Zero Trust organization. */
  name?: string | Computed<string>;
  /** The amount of time that tokens issued for applications will be valid. Must be in the format `300ms` or `2h45m`. Valid time units are: ns, us (or µs), ms, s, m, h. */
  sessionDuration?: string | Computed<string>;
  /** A description of the reason why the UI read only field is being toggled. */
  uiReadOnlyToggleReason?: string | Computed<string>;
  updatedAt?: AccessSingleResponse_Result_CreatedAt | Computed<AccessSingleResponse_Result_CreatedAt>;
  /** The amount of time a user seat is inactive before it expires. When the user seat exceeds the set time of inactivity, the user is removed as an active seat and no longer counts against your Teams seat count. Minimum value for this setting is 1 month (730h). Must be in the format `300ms` or `2h45m`. Valid time units are: `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. */
  userSeatExpirationInactiveTime?: string | Computed<string>;
  /** When enabled, unsuccessful WARP authentication requests with a non-HTML Accept header return a 401 response instead of redirecting to the login page. */
  warpAuthNonBrowser401?: boolean | Computed<boolean>;
  /** The amount of time that tokens issued for applications will be valid. Must be in the format `30m` or `2h45m`. Valid time units are: m, h. */
  warpAuthSessionDuration?: string | Computed<string>;
}

export interface AccessSingleResponseConfig {
  /** Identifier. */
  accountId: string | Computed<string>;
}

export interface AccessSingleResponseAttrs {
  /** Identifier. */
  accountId: string;
  result: AccessSingleResponse_Result;
}

export const AccessSingleResponse: DataSourceBinding<AccessSingleResponseConfig, AccessSingleResponseAttrs> = {
  wireType: "cloudflare_access_single_response",
  fields: {
    accountId: "account_id",
  },
};
