// Code generated by `ubx sdk gen` from cloudflare_route. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Route_Result_Deployment {
  createdAt: string | Computed<string>;
  deploymentId: string | Computed<string>;
  versionId: string | Computed<string>;
}

export interface Route_Result_Elements_Outputs_Next {
  elementId?: string | Computed<string>;
}

export interface Route_Result_Elements_Outputs {
  next?: Route_Result_Elements_Outputs_Next | Computed<Route_Result_Elements_Outputs_Next>;
}

export interface Route_Result_Elements_Properties {
  conditions?: unknown | Computed<unknown>;
}

export interface Route_Result_Elements {
  id?: string | Computed<string>;
  outputs?: Route_Result_Elements_Outputs | Computed<Route_Result_Elements_Outputs>;
  properties?: Route_Result_Elements_Properties | Computed<Route_Result_Elements_Properties>;
  type?: string | Computed<string>;
}

export interface Route_Result_Version {
  active: string | Computed<string>;
  createdAt: string | Computed<string>;
  data: string | Computed<string>;
  isValid?: boolean | Computed<boolean>;
  versionId: string | Computed<string>;
}

export interface Route_Result {
  createdAt: string | Computed<string>;
  deployment: Route_Result_Deployment | Computed<Route_Result_Deployment>;
  elements: Route_Result_Elements[] | Computed<Route_Result_Elements[]>;
  gatewayId: string | Computed<string>;
  id: string | Computed<string>;
  modifiedAt: string | Computed<string>;
  name: string | Computed<string>;
  version: Route_Result_Version | Computed<Route_Result_Version>;
}

export interface RouteConfig {
  /** Whether requests to this AI Gateway require authentication. (AI-inferred) */
  authentication?: boolean | Computed<boolean>;
  /** Whether to invalidate cached responses when the underlying data changes. (AI-inferred) */
  cacheInvalidateOnUpdate: boolean | Computed<boolean>;
  /** How long a cached response remains valid, in seconds. (AI-inferred) */
  cacheTtl: number | Computed<number>;
  /** Whether to collect request/response logs for this gateway. (AI-inferred) */
  collectLogs: boolean | Computed<boolean>;
  /** gateway id */
  id: string | Computed<string>;
  /** How long collected logs are retained and how they're managed. (AI-inferred) */
  logManagement?: number | Computed<number>;
  /** The strategy used for log retention (e.g. time-based, storage-based). (AI-inferred) */
  logManagementStrategy?: string | Computed<string>;
  /** Whether to push this gateway's own logs to a configured Logpush destination. (AI-inferred) */
  logpush?: boolean | Computed<boolean>;
  /** The public key used to encrypt logs pushed via Logpush. (AI-inferred) */
  logpushPublicKey?: string | Computed<string>;
  /** The time window, in seconds, over which the rate limit is applied. (AI-inferred) */
  rateLimitingInterval: number | Computed<number>;
  /** The maximum number of requests allowed within the configured rate-limiting interval. (AI-inferred) */
  rateLimitingLimit: number | Computed<number>;
  /** The algorithm used to enforce the rate limit (e.g. fixed window, sliding window). (AI-inferred) */
  rateLimitingTechnique?: string | Computed<string>;
  /** Backoff strategy for retry delays */
  retryBackoff?: string | Computed<string>;
  /** Delay between retry attempts in milliseconds (0-5000) */
  retryDelay?: number | Computed<number>;
  /** Maximum number of retry attempts for failed requests (1-5) */
  retryMaxAttempts?: number | Computed<number>;
  /** The identifier of the Secrets Store this gateway's own credentials are stored in. (AI-inferred) */
  storeId?: string | Computed<string>;
  /** Controls how Workers AI inference calls routed through this gateway are billed. 'postpaid' bills the account directly through Workers AI; 'unified' deducts credits via AI Gateway using neuron-based pricing and delegates billing to AI Gateway. */
  workersAiBillingMode?: string | Computed<string>;
  /** Whether Zero Data Retention is enabled, so request/response content is never persisted. (AI-inferred) */
  zdr?: boolean | Computed<boolean>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  gatewayId: string | Computed<string>;
}

export interface RouteAttrs {
  /** Whether requests to this AI Gateway require authentication. (AI-inferred) */
  authentication: boolean;
  /** Whether to invalidate cached responses when the underlying data changes. (AI-inferred) */
  cacheInvalidateOnUpdate: boolean;
  /** How long a cached response remains valid, in seconds. (AI-inferred) */
  cacheTtl: number;
  /** Whether to collect request/response logs for this gateway. (AI-inferred) */
  collectLogs: boolean;
  /** gateway id */
  id: string;
  /** How long collected logs are retained and how they're managed. (AI-inferred) */
  logManagement: number;
  /** The strategy used for log retention (e.g. time-based, storage-based). (AI-inferred) */
  logManagementStrategy: string;
  /** Whether to push this gateway's own logs to a configured Logpush destination. (AI-inferred) */
  logpush: boolean;
  /** The public key used to encrypt logs pushed via Logpush. (AI-inferred) */
  logpushPublicKey: string;
  /** The time window, in seconds, over which the rate limit is applied. (AI-inferred) */
  rateLimitingInterval: number;
  /** The maximum number of requests allowed within the configured rate-limiting interval. (AI-inferred) */
  rateLimitingLimit: number;
  /** The algorithm used to enforce the rate limit (e.g. fixed window, sliding window). (AI-inferred) */
  rateLimitingTechnique: string;
  /** The requested resource or collection of resources. (AI-inferred) */
  result: Route_Result;
  /** Backoff strategy for retry delays */
  retryBackoff: string;
  /** Delay between retry attempts in milliseconds (0-5000) */
  retryDelay: number;
  /** Maximum number of retry attempts for failed requests (1-5) */
  retryMaxAttempts: number;
  /** The identifier of the Secrets Store this gateway's own credentials are stored in. (AI-inferred) */
  storeId: string;
  /** Whether the API call was successful. (AI-inferred) */
  success: boolean;
  /** Controls how Workers AI inference calls routed through this gateway are billed. 'postpaid' bills the account directly through Workers AI; 'unified' deducts credits via AI Gateway using neuron-based pricing and delegates billing to AI Gateway. */
  workersAiBillingMode: string;
  /** Whether Zero Data Retention is enabled, so request/response content is never persisted. (AI-inferred) */
  zdr: boolean;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  gatewayId: string;
}

export const Route: ResourceBinding<RouteConfig, RouteAttrs> = {
  wireType: "cloudflare_route",
  fields: {
    authentication: "authentication",
    cacheInvalidateOnUpdate: "cache_invalidate_on_update",
    cacheTtl: "cache_ttl",
    collectLogs: "collect_logs",
    id: "id",
    logManagement: "log_management",
    logManagementStrategy: "log_management_strategy",
    logpush: "logpush",
    logpushPublicKey: "logpush_public_key",
    rateLimitingInterval: "rate_limiting_interval",
    rateLimitingLimit: "rate_limiting_limit",
    rateLimitingTechnique: "rate_limiting_technique",
    retryBackoff: "retry_backoff",
    retryDelay: "retry_delay",
    retryMaxAttempts: "retry_max_attempts",
    storeId: "store_id",
    workersAiBillingMode: "workers_ai_billing_mode",
    zdr: "zdr",
    accountId: "account_id",
    gatewayId: "gateway_id",
  },
};
