// Code generated by `ubx sdk gen` from cloudflare_version. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Version_Result_Elements_Outputs_Next {
  elementId?: string | Computed<string>;
}

export interface Version_Result_Elements_Outputs {
  next?: Version_Result_Elements_Outputs_Next | Computed<Version_Result_Elements_Outputs_Next>;
}

export interface Version_Result_Elements_Properties {
  conditions?: unknown | Computed<unknown>;
}

export interface Version_Result_Elements {
  id?: string | Computed<string>;
  outputs?: Version_Result_Elements_Outputs | Computed<Version_Result_Elements_Outputs>;
  properties?: Version_Result_Elements_Properties | Computed<Version_Result_Elements_Properties>;
  type?: string | Computed<string>;
}

export interface Version_Result {
  active: string | Computed<string>;
  createdAt: string | Computed<string>;
  data: string | Computed<string>;
  elements: Version_Result_Elements[] | Computed<Version_Result_Elements[]>;
  gatewayId: string | Computed<string>;
  id: string | Computed<string>;
  isValid?: boolean | Computed<boolean>;
  modifiedAt: string | Computed<string>;
  name: string | Computed<string>;
  versionId: string | Computed<string>;
}

export interface VersionConfig {
  authentication?: boolean | Computed<boolean>;
  cacheInvalidateOnUpdate: boolean | Computed<boolean>;
  cacheTtl: number | Computed<number>;
  collectLogs: boolean | Computed<boolean>;
  /** gateway id */
  id: string | Computed<string>;
  logManagement?: number | Computed<number>;
  logManagementStrategy?: string | Computed<string>;
  logpush?: boolean | Computed<boolean>;
  logpushPublicKey?: string | Computed<string>;
  rateLimitingInterval: number | Computed<number>;
  rateLimitingLimit: number | Computed<number>;
  rateLimitingTechnique?: string | Computed<string>;
  /** Backoff strategy for retry delays */
  retryBackoff?: string | Computed<string>;
  /** Delay between retry attempts in milliseconds (0-5000) */
  retryDelay?: number | Computed<number>;
  /** Maximum number of retry attempts for failed requests (1-5) */
  retryMaxAttempts?: number | Computed<number>;
  storeId?: string | Computed<string>;
  /** Controls how Workers AI inference calls routed through this gateway are billed. 'postpaid' bills the account directly through Workers AI; 'unified' deducts credits via AI Gateway using neuron-based pricing and delegates billing to AI Gateway. */
  workersAiBillingMode?: string | Computed<string>;
  zdr?: boolean | Computed<boolean>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  gatewayId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  versionId: string | Computed<string>;
}

export interface VersionAttrs {
  authentication: boolean;
  cacheInvalidateOnUpdate: boolean;
  cacheTtl: number;
  collectLogs: boolean;
  /** gateway id */
  id: string;
  logManagement: number;
  logManagementStrategy: string;
  logpush: boolean;
  logpushPublicKey: string;
  rateLimitingInterval: number;
  rateLimitingLimit: number;
  rateLimitingTechnique: string;
  result: Version_Result;
  /** Backoff strategy for retry delays */
  retryBackoff: string;
  /** Delay between retry attempts in milliseconds (0-5000) */
  retryDelay: number;
  /** Maximum number of retry attempts for failed requests (1-5) */
  retryMaxAttempts: number;
  storeId: string;
  success: boolean;
  /** Controls how Workers AI inference calls routed through this gateway are billed. 'postpaid' bills the account directly through Workers AI; 'unified' deducts credits via AI Gateway using neuron-based pricing and delegates billing to AI Gateway. */
  workersAiBillingMode: string;
  zdr: boolean;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  gatewayId: string;
  /** path parameter, not part of the API's own resource representation */
  versionId: string;
}

export const Version: ResourceBinding<VersionConfig, VersionAttrs> = {
  wireType: "cloudflare_version",
  fields: {
    authentication: "authentication",
    cacheInvalidateOnUpdate: "cache_invalidate_on_update",
    cacheTtl: "cache_ttl",
    collectLogs: "collect_logs",
    id: "id",
    logManagement: "log_management",
    logManagementStrategy: "log_management_strategy",
    logpush: "logpush",
    logpushPublicKey: "logpush_public_key",
    rateLimitingInterval: "rate_limiting_interval",
    rateLimitingLimit: "rate_limiting_limit",
    rateLimitingTechnique: "rate_limiting_technique",
    retryBackoff: "retry_backoff",
    retryDelay: "retry_delay",
    retryMaxAttempts: "retry_max_attempts",
    storeId: "store_id",
    workersAiBillingMode: "workers_ai_billing_mode",
    zdr: "zdr",
    accountId: "account_id",
    gatewayId: "gateway_id",
    versionId: "version_id",
  },
};
