// Code generated by `ubx sdk gen` from cloudflare_regional_hostname. DO NOT EDIT.
package dlsregionalservices

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RegionalHostnameConfig struct {
	// DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g `*.example.com`
	Hostname any
	// Identifying key for the region
	RegionKey any
	// Configure which routing method to use for the regional hostname
	Routing any
	// path parameter, not part of the API's own resource representation
	ZoneId any
}

type RegionalHostnameAttrs struct {
	// DNS hostname to be regionalized, must be a subdomain of the zone. Wildcards are supported for one level, e.g `*.example.com`
	Hostname any
	// Identifying key for the region
	RegionKey any
	// Configure which routing method to use for the regional hostname
	Routing any
	// path parameter, not part of the API's own resource representation
	ZoneId any
}

var RegionalHostname = ubx.ResourceBinding{
	WireType: "cloudflare_regional_hostname",
	Fields: ubx.FieldMap{
		"Hostname": ubx.FieldSpec{WireName: "hostname"},
		"RegionKey": ubx.FieldSpec{WireName: "region_key"},
		"Routing": ubx.FieldSpec{WireName: "routing"},
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
	},
}
