// Code generated by `ubx sdk gen` from cloudflare_session. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SessionConfig {
  /** Account ID. */
  accountId: string | Computed<string>;
  limit?: number | Computed<number>;
  offset?: number | Computed<number>;
}

export interface SessionAttrs {
  /** Account ID. */
  accountId: string;
  limit: number;
  offset: number;
}

export const Session: DataSourceBinding<SessionConfig, SessionAttrs> = {
  wireType: "cloudflare_session",
  fields: {
    accountId: "account_id",
    limit: "limit",
    offset: "offset",
  },
};
