// Code generated by `ubx sdk gen` from cloudflare_item. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Item_PublicEndpointParams_ChatCompletionsEndpoint {
  /** Disable chat completions endpoint for this public endpoint */
  disabled?: boolean | Computed<boolean>;
}

export interface Item_PublicEndpointParams_Mcp {
  description?: string | Computed<string>;
  /** Disable MCP endpoint for this public endpoint */
  disabled?: boolean | Computed<boolean>;
}

export interface Item_PublicEndpointParams_RateLimit {
  periodMs?: number | Computed<number>;
  requests?: number | Computed<number>;
  technique?: string | Computed<string>;
}

export interface Item_PublicEndpointParams {
  authorizedHosts?: string[] | Computed<string[]>;
  chatCompletionsEndpoint?: Item_PublicEndpointParams_ChatCompletionsEndpoint | Computed<Item_PublicEndpointParams_ChatCompletionsEndpoint>;
  /** Custom domain hostnames that alias this public endpoint. GET and create responses return the current set; on update (PUT) this field is only echoed back when supplied in the request body, otherwise it is null (omit it to leave domains unchanged). */
  customDomains?: string[] | Computed<string[]>;
  /** When false, the instance is reachable only via a registered custom domain and the default <public_endpoint_id>.search.ai.cloudflare.com host returns 404. Requires at least one custom domain. Defaults to true. public_endpoint_params is replaced wholesale on update, so resend default_domain_enabled on every update to keep the default host off — omitting it resets to true. */
  defaultDomainEnabled?: boolean | Computed<boolean>;
  enabled?: boolean | Computed<boolean>;
  /** Instance IDs exposed through the namespace public endpoint. Empty means nothing is searchable. Every ID must be an existing instance in this namespace, and the list cannot exceed the account's multi-instance search limit. */
  instancesAllowed?: string[] | Computed<string[]>;
  mcp?: Item_PublicEndpointParams_Mcp | Computed<Item_PublicEndpointParams_Mcp>;
  rateLimit?: Item_PublicEndpointParams_RateLimit | Computed<Item_PublicEndpointParams_RateLimit>;
  searchEndpoint?: Item_PublicEndpointParams_ChatCompletionsEndpoint | Computed<Item_PublicEndpointParams_ChatCompletionsEndpoint>;
}

export interface Item_Result {
  checksum?: string | Computed<string>;
  chunksCount?: number | Computed<number>;
  createdAt?: string | Computed<string>;
  error?: string | Computed<string>;
  fileSize?: number | Computed<number>;
  id?: string | Computed<string>;
  key?: string | Computed<string>;
  lastSeenAt?: string | Computed<string>;
  /** Built-in, configured filterable, and retained source metadata for the item. */
  metadata?: Record<string, unknown> | Computed<Record<string, unknown>>;
  namespace?: string | Computed<string>;
  nextAction?: string | Computed<string>;
  /** Identifies which data source this item belongs to. "builtin" for uploaded files, "{type}:{source}" for external sources, null for legacy items. */
  sourceId?: string | Computed<string>;
  status?: string | Computed<string>;
}

const Item_PublicEndpointParams_ChatCompletionsEndpointFields: FieldMap = {
  disabled: "disabled",
};

const Item_PublicEndpointParams_McpFields: FieldMap = {
  description: "description",
  disabled: "disabled",
};

const Item_PublicEndpointParams_RateLimitFields: FieldMap = {
  periodMs: "period_ms",
  requests: "requests",
  technique: "technique",
};

const Item_PublicEndpointParamsFields: FieldMap = {
  authorizedHosts: "authorized_hosts",
  chatCompletionsEndpoint: {
    wireName: "chat_completions_endpoint",
    kind: "object",
    fields: Item_PublicEndpointParams_ChatCompletionsEndpointFields,
  },
  customDomains: "custom_domains",
  defaultDomainEnabled: "default_domain_enabled",
  enabled: "enabled",
  instancesAllowed: "instances_allowed",
  mcp: {
    wireName: "mcp",
    kind: "object",
    fields: Item_PublicEndpointParams_McpFields,
  },
  rateLimit: {
    wireName: "rate_limit",
    kind: "object",
    fields: Item_PublicEndpointParams_RateLimitFields,
  },
  searchEndpoint: {
    wireName: "search_endpoint",
    kind: "object",
    fields: Item_PublicEndpointParams_ChatCompletionsEndpointFields,
  },
};

export interface ItemConfig {
  /** Optional description for the namespace. Max 256 characters. */
  description?: string | Computed<string>;
  name: string | Computed<string>;
  publicEndpointParams?: Item_PublicEndpointParams | Computed<Item_PublicEndpointParams>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  id: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  itemId: string | Computed<string>;
}

export interface ItemAttrs {
  /** Optional description for the namespace. Max 256 characters. */
  description: string;
  name: string;
  publicEndpointParams: Item_PublicEndpointParams;
  result: Item_Result;
  success: boolean;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  id: string;
  /** path parameter, not part of the API's own resource representation */
  itemId: string;
}

export const Item: ResourceBinding<ItemConfig, ItemAttrs> = {
  wireType: "cloudflare_item",
  fields: {
    description: "description",
    name: "name",
    publicEndpointParams: {
      wireName: "public_endpoint_params",
      kind: "object",
      fields: Item_PublicEndpointParamsFields,
    },
    accountId: "account_id",
    id: "id",
    itemId: "item_id",
  },
};
