# Code generated by `ubx sdk gen` from cloudflare_dnssec_dnssec_response_single. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DnssecResponseSingle_Result:
    # Algorithm key code.
    algorithm: Any = None
    # Digest hash.
    digest: Any = None
    # Type of digest algorithm.
    digest_algorithm: Any = None
    # Coded type for digest algorithm.
    digest_type: Any = None
    # If true, multi-signer DNSSEC is enabled on the zone, allowing multiple providers to serve a DNSSEC-signed zone at the same time. This is required for DNSKEY records (except those automatically generated by Cloudflare) to be added to the zone. See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
    dnssec_multi_signer: Any = None
    # If true, allows Cloudflare to transfer in a DNSSEC-signed zone including signatures from an external provider, without requiring Cloudflare to sign any records on the fly. Note that this feature has some limitations. See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
    dnssec_presigned: Any = None
    # If true, enables the use of NSEC3 together with DNSSEC on the zone. Combined with setting dnssec_presigned to true, this enables the use of NSEC3 records when transferring in from an external provider. If dnssec_presigned is instead set to false (default), NSEC3 records will be generated and signed at request time. See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
    dnssec_use_nsec3: Any = None
    # Full DS record.
    ds: Any = None
    # Flag for DNSSEC record.
    flags: Any = None
    # Code for key tag.
    key_tag: Any = None
    # Algorithm key type.
    key_type: Any = None
    # When DNSSEC was last modified.
    modified_on: Any = None
    # Public key for DS record.
    public_key: Any = None
    # Status of DNSSEC, based on user-desired state and presence of necessary records.
    status: Any = None

@dataclasses.dataclass
class DnssecResponseSingleConfig:
    # Identifier.
    zone_id: Any = None

@dataclasses.dataclass
class DnssecResponseSingleAttrs:
    result: Any = None
    # Identifier.
    zone_id: Any = None

DnssecResponseSingle = ubx.DataSourceBinding(
    wire_type="cloudflare_dnssec_dnssec_response_single",
    fields={
        "zone_id": ubx.FieldSpec(wire_name="zone_id"),
    },
)
