// Code generated by `ubx sdk gen` from cloudflare_cache_auto_origin_tls_kex_response. DO NOT EDIT.
package origintls

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CacheAutoOriginTlsKexResponse_Errors struct {
	Code any
	Message any
}

type CacheAutoOriginTlsKexResponse_Result_Enabled struct {
}

type CacheAutoOriginTlsKexResponse_Result struct {
	// Whether Auto-Origin TLS KEX selection is enabled for the zone.
	Enabled any
	Id any
	// Last time this setting was modified.
	ModifiedOn any
}

type CacheAutoOriginTlsKexResponseConfig struct {
	ZoneId any
}

type CacheAutoOriginTlsKexResponseAttrs struct {
	Errors any
	Messages any
	Result any
	// Indicates the API call's success or failure.
	Success any
	ZoneId any
}

var CacheAutoOriginTlsKexResponse = ubx.DataSourceBinding{
	WireType: "cloudflare_cache_auto_origin_tls_kex_response",
	Fields: ubx.FieldMap{
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
	},
}
