// Code generated by `ubx sdk gen` from cloudflare_reference_id. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ReferenceId_Result {
  /** The Cloudflare account tag. */
  accountTag: string | Computed<string>;
  /** Whether this integration is enabled and should export changes in risk score. */
  active: boolean | Computed<boolean>;
  /** When the integration was created in RFC3339 format. */
  createdAt: string | Computed<string>;
  /** The id of the integration, a UUIDv4. */
  id: string | Computed<string>;
  integrationType: string | Computed<string>;
  /** A reference ID defined by the client. Should be set to the Access-Okta IDP integration ID. Useful when the risk-score integration needs to be associated with a secondary asset and recalled using that ID. */
  referenceId: string | Computed<string>;
  /** The base URL for the tenant. E.g. "https://tenant.okta.com". */
  tenantUrl: string | Computed<string>;
  /** The URL for the Shared Signals Framework configuration, e.g. "/.well-known/sse-configuration/{integration_uuid}/". https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.6.2.1. */
  wellKnownUrl: string | Computed<string>;
}

export interface ReferenceIdConfig {
  accountId: string | Computed<string>;
  referenceId: string | Computed<string>;
}

export interface ReferenceIdAttrs {
  accountId: string;
  referenceId: string;
  result: ReferenceId_Result;
}

export const ReferenceId: DataSourceBinding<ReferenceIdConfig, ReferenceIdAttrs> = {
  wireType: "cloudflare_reference_id",
  fields: {
    accountId: "account_id",
    referenceId: "reference_id",
  },
};
