# Code generated by `ubx sdk gen` from cloudflare_letter. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Letter_Fields:
    discovery_date: Any = None
    domain: Any = None
    generation_date: Any = None
    jurisdiction: Any = None
    registrant_email: Any = None
    registrar: Any = None
    registrar_email: Any = None
    resolution_by_date: Any = None
    sender_company: Any = None
    sender_email: Any = None
    sender_name: Any = None
    sender_title: Any = None
    trademark_name: Any = None
    trademark_number: Any = None
    trademark_owner: Any = None

_Letter_FieldsFields = {
    "discovery_date": ubx.FieldSpec(wire_name="discovery_date"),
    "domain": ubx.FieldSpec(wire_name="domain"),
    "generation_date": ubx.FieldSpec(wire_name="generation_date"),
    "jurisdiction": ubx.FieldSpec(wire_name="jurisdiction"),
    "registrant_email": ubx.FieldSpec(wire_name="registrant_email"),
    "registrar": ubx.FieldSpec(wire_name="registrar"),
    "registrar_email": ubx.FieldSpec(wire_name="registrar_email"),
    "resolution_by_date": ubx.FieldSpec(wire_name="resolution_by_date"),
    "sender_company": ubx.FieldSpec(wire_name="sender_company"),
    "sender_email": ubx.FieldSpec(wire_name="sender_email"),
    "sender_name": ubx.FieldSpec(wire_name="sender_name"),
    "sender_title": ubx.FieldSpec(wire_name="sender_title"),
    "trademark_name": ubx.FieldSpec(wire_name="trademark_name"),
    "trademark_number": ubx.FieldSpec(wire_name="trademark_number"),
    "trademark_owner": ubx.FieldSpec(wire_name="trademark_owner"),
}

@dataclasses.dataclass
class LetterConfig:
    fields: Any = None
    template_id: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    notice_id: Any = None
    # path parameter, not part of the API's own resource representation
    letter_id: Any = None

@dataclasses.dataclass
class LetterAttrs:
    created_at: Any = None
    fields: Any = None
    id: Any = None
    letter_text: Any = None
    letter_type: Any = None
    takedown_notice_id: Any = None
    template_id: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    notice_id: Any = None
    # path parameter, not part of the API's own resource representation
    letter_id: Any = None

Letter = ubx.ResourceBinding(
    wire_type="cloudflare_letter",
    fields={
        "fields": ubx.FieldSpec(
            wire_name="fields",
            kind="object",
            fields=_Letter_FieldsFields,
        ),
        "template_id": ubx.FieldSpec(wire_name="template_id"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "notice_id": ubx.FieldSpec(wire_name="notice_id"),
        "letter_id": ubx.FieldSpec(wire_name="letter_id"),
    },
)
