# Code generated by `ubx sdk gen` from cloudflare_upload_token. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class UploadTokenConfig:
    # Identifier.
    account_id: Any = None
    # Name of the project.
    project_name: Any = None

@dataclasses.dataclass
class UploadTokenAttrs:
    # Identifier.
    account_id: Any = None
    # Name of the project.
    project_name: Any = None

UploadToken = ubx.DataSourceBinding(
    wire_type="cloudflare_upload_token",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "project_name": ubx.FieldSpec(wire_name="project_name"),
    },
)
