// Code generated by `ubx sdk gen` from cloudflare_zero_trust_gateway_gateway_account. DO NOT EDIT.
package zerotrustaccounts

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ZeroTrustGatewayGatewayAccount_Result struct {
	// Specify the gateway internal ID.
	GatewayTag any
	// Specify the Cloudflare account ID.
	Id any
	// Specify the provider name (usually Cloudflare).
	ProviderName any
}

type ZeroTrustGatewayGatewayAccountConfig_ struct {
	AccountId any
}

type ZeroTrustGatewayGatewayAccountAttrs struct {
	AccountId any
	Result    any
}

var ZeroTrustGatewayGatewayAccount = ubx.DataSourceBinding{
	WireType: "cloudflare_zero_trust_gateway_gateway_account",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
