// Code generated by `ubx sdk gen` from cloudflare_investigate. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Investigate_Errors_Source {
  pointer?: string | Computed<string>;
}

export interface Investigate_Errors {
  code?: number | Computed<number>;
  documentationUrl?: string | Computed<string>;
  message?: string | Computed<string>;
  source?: Investigate_Errors_Source | Computed<Investigate_Errors_Source>;
}

export interface Investigate_Result_ActionLog_Properties {
  folder?: string | Computed<string>;
  requestedBy?: string | Computed<string>;
}

export interface Investigate_Result_ActionLog {
  completedAt?: string | Computed<string>;
  completedTimestamp?: string | Computed<string>;
  operation?: string | Computed<string>;
  properties?: Investigate_Result_ActionLog_Properties | Computed<Investigate_Result_ActionLog_Properties>;
  status?: string | Computed<string>;
}

export interface Investigate_Result_Findings {
  attachment?: string | Computed<string>;
  detail?: string | Computed<string>;
  detection?: string | Computed<string>;
  field?: string | Computed<string>;
  name?: string | Computed<string>;
  portion?: string | Computed<string>;
  reason?: string | Computed<string>;
  score?: number | Computed<number>;
  value?: string | Computed<string>;
}

export interface Investigate_Result_Id {
}

export interface Investigate_Result_Properties {
  allowlistedPattern?: string | Computed<string>;
  allowlistedPatternType?: string | Computed<string>;
  blocklistedMessage?: boolean | Computed<boolean>;
  blocklistedPattern?: string | Computed<string>;
  whitelistedPatternType?: string | Computed<string>;
}

export interface Investigate_Result_Validation {
  comment?: string | Computed<string>;
  dkim?: string | Computed<string>;
  dmarc?: string | Computed<string>;
  spf?: string | Computed<string>;
}

export interface Investigate_Result {
  actionLog?: Investigate_Result_ActionLog[] | Computed<Investigate_Result_ActionLog[]>;
  alertId?: string | Computed<string>;
  clientRecipients?: string[] | Computed<string[]>;
  deliveryMode?: string | Computed<string>;
  deliveryStatus?: string[] | Computed<string[]>;
  detectionReasons?: string[] | Computed<string[]>;
  edfHash?: string | Computed<string>;
  envelopeFrom?: string | Computed<string>;
  envelopeTo?: string[] | Computed<string[]>;
  finalDisposition?: string | Computed<string>;
  findings?: Investigate_Result_Findings[] | Computed<Investigate_Result_Findings[]>;
  from?: string | Computed<string>;
  fromName?: string | Computed<string>;
  htmltextStructureHash?: string | Computed<string>;
  id?: Investigate_Result_Id | Computed<Investigate_Result_Id>;
  isPhishSubmission?: boolean | Computed<boolean>;
  isQuarantined?: boolean | Computed<boolean>;
  messageId?: string | Computed<string>;
  postDeliveryOperations?: string[] | Computed<string[]>;
  postfixId?: string | Computed<string>;
  postfixIdOutbound?: string | Computed<string>;
  properties?: Investigate_Result_Properties | Computed<Investigate_Result_Properties>;
  replyto?: string | Computed<string>;
  scannedAt?: string | Computed<string>;
  sentAt?: string | Computed<string>;
  sentDate?: string | Computed<string>;
  smtpHeloServerIp?: string | Computed<string>;
  smtpPreviousHopIp?: string | Computed<string>;
  subject?: string | Computed<string>;
  threatCategories?: string[] | Computed<string[]>;
  to?: string[] | Computed<string[]>;
  toName?: string[] | Computed<string[]>;
  ts?: string | Computed<string>;
  validation?: Investigate_Result_Validation | Computed<Investigate_Result_Validation>;
  xOriginatingIp?: string | Computed<string>;
}

export interface Investigate_ResultInfo {
  /** Number of items in current page. */
  count: number | Computed<number>;
  /** Cursor for next page. */
  next?: string | Computed<string>;
  /** Deprecated: Always returns 0. End of life: November 1, 2026. */
  page?: number | Computed<number>;
  /** Number of items per page. */
  perPage: number | Computed<number>;
  /** Cursor for previous page. */
  previous?: string | Computed<string>;
  /** Deprecated: Always returns 0. End of life: November 1, 2026. */
  totalCount: number | Computed<number>;
}

export interface InvestigateConfig {
  alertId?: string | Computed<string>;
  cursor?: string | Computed<string>;
  /** Delivery status of the message. */
  deliveryStatus?: string | Computed<string>;
  detectionsOnly?: boolean | Computed<boolean>;
  domain?: string | Computed<string>;
  end?: string | Computed<string>;
  finalDisposition?: string | Computed<string>;
  messageAction?: string | Computed<string>;
  messageId?: string | Computed<string>;
  metric?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  query?: string | Computed<string>;
  recipient?: string | Computed<string>;
  sender?: string | Computed<string>;
  smtpHeloIp?: string | Computed<string>;
  start?: string | Computed<string>;
  subject?: string | Computed<string>;
}

export interface InvestigateAttrs {
  alertId: string;
  cursor: string;
  /** Delivery status of the message. */
  deliveryStatus: string;
  detectionsOnly: boolean;
  domain: string;
  end: string;
  errors: Investigate_Errors[];
  finalDisposition: string;
  messageAction: string;
  messageId: string;
  messages: Investigate_Errors[];
  metric: string;
  page: number;
  perPage: number;
  query: string;
  recipient: string;
  result: Investigate_Result[];
  resultInfo: Investigate_ResultInfo;
  sender: string;
  smtpHeloIp: string;
  start: string;
  subject: string;
  /** Whether the API call was successful. */
  success: boolean;
}

export const Investigate: DataSourceBinding<InvestigateConfig, InvestigateAttrs> = {
  wireType: "cloudflare_investigate",
  fields: {
    alertId: "alert_id",
    cursor: "cursor",
    deliveryStatus: "delivery_status",
    detectionsOnly: "detections_only",
    domain: "domain",
    end: "end",
    finalDisposition: "final_disposition",
    messageAction: "message_action",
    messageId: "message_id",
    metric: "metric",
    page: "page",
    perPage: "per_page",
    query: "query",
    recipient: "recipient",
    sender: "sender",
    smtpHeloIp: "smtp_helo_ip",
    start: "start",
    subject: "subject",
  },
};
