// Code generated by `ubx sdk gen` from cloudflare_subdomain. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SubdomainConfig {
  /** Identifier. */
  accountId: string | Computed<string>;
  /** Name of the script, used in URLs and route configuration. */
  scriptName: string | Computed<string>;
}

export interface SubdomainAttrs {
  /** Identifier. */
  accountId: string;
  /** Name of the script, used in URLs and route configuration. */
  scriptName: string;
}

export const Subdomain: DataSourceBinding<SubdomainConfig, SubdomainAttrs> = {
  wireType: "cloudflare_subdomain",
  fields: {
    accountId: "account_id",
    scriptName: "script_name",
  },
};
