// Code generated by `ubx sdk gen` from cloudflare_workers_script_response_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface WorkersScriptResponseCollection_Errors_Source {
  pointer?: string | Computed<string>;
}

export interface WorkersScriptResponseCollection_Errors {
  code?: number | Computed<number>;
  documentationUrl?: string | Computed<string>;
  message?: string | Computed<string>;
  source?: WorkersScriptResponseCollection_Errors_Source | Computed<WorkersScriptResponseCollection_Errors_Source>;
}

export interface WorkersScriptResponseCollection_Result_CacheOptions {
  crossVersionCache?: boolean | Computed<boolean>;
  enabled?: boolean | Computed<boolean>;
}

export interface WorkersScriptResponseCollection_Result_Exports {
}

export interface WorkersScriptResponseCollection_Result_NamedHandlers {
  handlers?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
}

export interface WorkersScriptResponseCollection_Result_Observability_Logs {
  destinations?: string[] | Computed<string[]>;
  enabled?: boolean | Computed<boolean>;
  headSamplingRate?: number | Computed<number>;
  invocationLogs?: boolean | Computed<boolean>;
  persist?: boolean | Computed<boolean>;
}

export interface WorkersScriptResponseCollection_Result_Observability_Traces {
  destinations?: string[] | Computed<string[]>;
  enabled?: boolean | Computed<boolean>;
  headSamplingRate?: number | Computed<number>;
  persist?: boolean | Computed<boolean>;
  propagationPolicy?: string | Computed<string>;
}

export interface WorkersScriptResponseCollection_Result_Observability {
  enabled?: boolean | Computed<boolean>;
  headSamplingRate?: number | Computed<number>;
  logs?: WorkersScriptResponseCollection_Result_Observability_Logs | Computed<WorkersScriptResponseCollection_Result_Observability_Logs>;
  redactQueryString?: boolean | Computed<boolean>;
  traces?: WorkersScriptResponseCollection_Result_Observability_Traces | Computed<WorkersScriptResponseCollection_Result_Observability_Traces>;
}

export interface WorkersScriptResponseCollection_Result_Placement {
  lastAnalyzedAt?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface WorkersScriptResponseCollection_Result_Routes {
  id?: WorkersScriptResponseCollection_Result_Exports | Computed<WorkersScriptResponseCollection_Result_Exports>;
  pattern?: string | Computed<string>;
  script?: string | Computed<string>;
}

export interface WorkersScriptResponseCollection_Result_TailConsumers {
  environment?: string | Computed<string>;
  namespace?: string | Computed<string>;
  service?: string | Computed<string>;
}

export interface WorkersScriptResponseCollection_Result {
  cacheOptions?: WorkersScriptResponseCollection_Result_CacheOptions | Computed<WorkersScriptResponseCollection_Result_CacheOptions>;
  compatibilityDate?: string | Computed<string>;
  compatibilityFlags?: string[] | Computed<string[]>;
  createdOn?: string | Computed<string>;
  etag?: string | Computed<string>;
  exports?: WorkersScriptResponseCollection_Result_Exports | Computed<WorkersScriptResponseCollection_Result_Exports>;
  handlers?: string[] | Computed<string[]>;
  hasAssets?: boolean | Computed<boolean>;
  hasModules?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  lastDeployedFrom?: string | Computed<string>;
  logpush?: boolean | Computed<boolean>;
  migrationTag?: string | Computed<string>;
  modifiedOn?: string | Computed<string>;
  namedHandlers?: WorkersScriptResponseCollection_Result_NamedHandlers[] | Computed<WorkersScriptResponseCollection_Result_NamedHandlers[]>;
  observability?: WorkersScriptResponseCollection_Result_Observability | Computed<WorkersScriptResponseCollection_Result_Observability>;
  placement?: WorkersScriptResponseCollection_Result_Placement | Computed<WorkersScriptResponseCollection_Result_Placement>;
  placementMode?: WorkersScriptResponseCollection_Result_Exports | Computed<WorkersScriptResponseCollection_Result_Exports>;
  placementStatus?: WorkersScriptResponseCollection_Result_Exports | Computed<WorkersScriptResponseCollection_Result_Exports>;
  routes?: WorkersScriptResponseCollection_Result_Routes[] | Computed<WorkersScriptResponseCollection_Result_Routes[]>;
  tag?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  tailConsumers?: WorkersScriptResponseCollection_Result_TailConsumers[] | Computed<WorkersScriptResponseCollection_Result_TailConsumers[]>;
  usageModel?: string | Computed<string>;
}

export interface WorkersScriptResponseCollectionConfig {
  /** Identifier. */
  accountId: string | Computed<string>;
  tags?: string | Computed<string>;
}

export interface WorkersScriptResponseCollectionAttrs {
  /** Identifier. */
  accountId: string;
  errors: WorkersScriptResponseCollection_Errors[];
  messages: WorkersScriptResponseCollection_Errors[];
  result: WorkersScriptResponseCollection_Result[];
  /** Whether the API call was successful. */
  success: boolean;
  tags: string;
}

export const WorkersScriptResponseCollection: DataSourceBinding<WorkersScriptResponseCollectionConfig, WorkersScriptResponseCollectionAttrs> = {
  wireType: "cloudflare_workers_script_response_collection",
  fields: {
    accountId: "account_id",
    tags: "tags",
  },
};
