# Code generated by `ubx sdk gen` from cloudflare_info. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class InfoConfig:
    index_name: Any = None

@dataclasses.dataclass
class InfoAttrs:
    # Identifier
    account_id: Any = None
    index_name: Any = None

Info = ubx.DataSourceBinding(
    wire_type="cloudflare_info",
    fields={
        "index_name": ubx.FieldSpec(wire_name="index_name"),
    },
)
