// Code generated by `ubx sdk gen` from cloudflare_ip. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IpConfig {
  networks?: string | Computed<string>;
}

export interface IpAttrs {
  networks: string;
}

export const Ip: DataSourceBinding<IpConfig, IpAttrs> = {
  wireType: "cloudflare_ip",
  fields: {
    networks: "networks",
  },
};
