// Code generated by `ubx sdk gen` from cloudflare_zero_trust_gateway_response_collection. DO NOT EDIT.
package zerotrustcertificates

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ZeroTrustGatewayResponseCollection_Result struct {
	BindingStatus any
	Certificate   any
	CreatedAt     any
	ExpiresOn     any
	Fingerprint   any
	Id            any
	InUse         any
	IssuerOrg     any
	IssuerRaw     any
	Type          any
	UpdatedAt     any
	UploadedOn    any
}

type ZeroTrustGatewayResponseCollectionConfig struct {
	AccountId any
}

type ZeroTrustGatewayResponseCollectionAttrs struct {
	AccountId any
	Result    any
}

var ZeroTrustGatewayResponseCollection = ubx.DataSourceBinding{
	WireType: "cloudflare_zero_trust_gateway_response_collection",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
