// Code generated by `ubx sdk gen` from cloudflare_magic_wan_single_response. DO NOT EDIT.
package magicsitewans

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MagicWanSingleResponse_Result_StaticAddressing struct {
	// A valid CIDR notation representing an IP range.
	Address any
	// A valid IPv4 address.
	GatewayAddress any
	// A valid CIDR notation representing an IP range.
	SecondaryAddress any
}

type MagicWanSingleResponse_Result struct {
	// Magic WAN health check rate for tunnels created on this link. The default value is `mid`.
	HealthCheckRate any
	// Identifier
	Id       any
	Name     any
	Physport any
	// Priority of WAN for traffic loadbalancing.
	Priority any
	// Identifier
	SiteId any
	// (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode.
	StaticAddressing any
	// VLAN ID. Use zero for untagged.
	VlanTag any
}

var MagicWanSingleResponse_Result_StaticAddressingFields = ubx.FieldMap{
	"Address":          ubx.FieldSpec{WireName: "address"},
	"GatewayAddress":   ubx.FieldSpec{WireName: "gateway_address"},
	"SecondaryAddress": ubx.FieldSpec{WireName: "secondary_address"},
}

type MagicWanSingleResponseConfig struct {
	// The name of the WAN interface. (AI-inferred)
	Name any
	// The physical port this WAN interface is attached to. (AI-inferred)
	Physport any
	// The priority of this WAN interface relative to other WAN interfaces on the site. (AI-inferred)
	Priority any
	// (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode.
	StaticAddressing any
	// VLAN ID. Use zero for untagged.
	VlanTag any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	SiteId any
	// path parameter, not part of the API's own resource representation
	WanId any
}

type MagicWanSingleResponseAttrs struct {
	// The name of the WAN interface. (AI-inferred)
	Name any
	// The physical port this WAN interface is attached to. (AI-inferred)
	Physport any
	// The priority of this WAN interface relative to other WAN interfaces on the site. (AI-inferred)
	Priority any
	// The requested resource, present when the API call succeeds. (AI-inferred)
	Result any
	// (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode.
	StaticAddressing any
	// VLAN ID. Use zero for untagged.
	VlanTag any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	SiteId any
	// path parameter, not part of the API's own resource representation
	WanId any
}

var MagicWanSingleResponse = ubx.ResourceBinding{
	WireType: "cloudflare_magic_wan_single_response",
	Fields: ubx.FieldMap{
		"Name":     ubx.FieldSpec{WireName: "name"},
		"Physport": ubx.FieldSpec{WireName: "physport"},
		"Priority": ubx.FieldSpec{WireName: "priority"},
		"StaticAddressing": ubx.FieldSpec{
			WireName: "static_addressing",
			Kind:     "object",
			Fields:   MagicWanSingleResponse_Result_StaticAddressingFields,
		},
		"VlanTag":   ubx.FieldSpec{WireName: "vlan_tag"},
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"SiteId":    ubx.FieldSpec{WireName: "site_id"},
		"WanId":     ubx.FieldSpec{WireName: "wan_id"},
	},
}
