// Code generated by `ubx sdk gen` from cloudflare_access_response_collection_hostnames_2. DO NOT EDIT.
package zonelevelaccessmtlsauthentication

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AccessResponseCollectionHostnames2Config struct {
	// Identifier.
	ZoneId any
}

type AccessResponseCollectionHostnames2Attrs struct {
	// Identifier.
	ZoneId any
}

var AccessResponseCollectionHostnames2 = ubx.DataSourceBinding{
	WireType: "cloudflare_access_response_collection_hostnames_2",
	Fields: ubx.FieldMap{
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
	},
}
