// Code generated by `ubx sdk gen` from cloudflare_tunnel_cfd_tunnel_response_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TunnelCfdTunnelResponseCollection_Result_Connections_OriginIp {
}

export interface TunnelCfdTunnelResponseCollection_Result_Connections {
  clientId?: string | Computed<string>;
  clientVersion?: string | Computed<string>;
  coloName?: string | Computed<string>;
  id?: string | Computed<string>;
  isPendingReconnect?: boolean | Computed<boolean>;
  openedAt?: string | Computed<string>;
  originIp?: TunnelCfdTunnelResponseCollection_Result_Connections_OriginIp | Computed<TunnelCfdTunnelResponseCollection_Result_Connections_OriginIp>;
  uuid?: string | Computed<string>;
}

export interface TunnelCfdTunnelResponseCollection_Result {
  accountTag?: string | Computed<string>;
  configSrc?: string | Computed<string>;
  connections?: TunnelCfdTunnelResponseCollection_Result_Connections[] | Computed<TunnelCfdTunnelResponseCollection_Result_Connections[]>;
  connsActiveAt?: string | Computed<string>;
  connsInactiveAt?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  id?: string | Computed<string>;
  metadata?: unknown | Computed<unknown>;
  name?: string | Computed<string>;
  remoteConfig?: boolean | Computed<boolean>;
  status?: string | Computed<string>;
  tunType?: string | Computed<string>;
}

export interface TunnelCfdTunnelResponseCollectionConfig {
  excludePrefix?: string | Computed<string>;
  /** If provided, include only resources that were created (and not deleted) before this time. URL encoded. */
  existedAt?: string | Computed<string>;
  includePrefix?: string | Computed<string>;
  /** If `true`, only include deleted tunnels. If `false`, exclude deleted tunnels. If empty, all tunnels will be included. */
  isDeleted?: boolean | Computed<boolean>;
  /** A user-friendly name for a tunnel. */
  name?: string | Computed<string>;
  /** Page number of paginated results. */
  page?: number | Computed<number>;
  /** Number of results to display. */
  perPage?: number | Computed<number>;
  /** The status of the tunnel. Valid values are `inactive` (tunnel has never been run), `degraded` (tunnel is active and able to serve traffic but in an unhealthy state), `healthy` (tunnel is active and able to serve traffic), or `down` (tunnel can not serve traffic as it has no connections to the Cloudflare Edge). */
  status?: string | Computed<string>;
  wasActiveAt?: string | Computed<string>;
  wasInactiveAt?: string | Computed<string>;
}

export interface TunnelCfdTunnelResponseCollectionAttrs {
  /** Cloudflare account ID */
  accountId: string;
  excludePrefix: string;
  /** If provided, include only resources that were created (and not deleted) before this time. URL encoded. */
  existedAt: string;
  includePrefix: string;
  /** If `true`, only include deleted tunnels. If `false`, exclude deleted tunnels. If empty, all tunnels will be included. */
  isDeleted: boolean;
  /** A user-friendly name for a tunnel. */
  name: string;
  /** Page number of paginated results. */
  page: number;
  /** Number of results to display. */
  perPage: number;
  result: TunnelCfdTunnelResponseCollection_Result[];
  /** The status of the tunnel. Valid values are `inactive` (tunnel has never been run), `degraded` (tunnel is active and able to serve traffic but in an unhealthy state), `healthy` (tunnel is active and able to serve traffic), or `down` (tunnel can not serve traffic as it has no connections to the Cloudflare Edge). */
  status: string;
  /** UUID of the tunnel. */
  uuid: string;
  wasActiveAt: string;
  wasInactiveAt: string;
}

export const TunnelCfdTunnelResponseCollection: DataSourceBinding<TunnelCfdTunnelResponseCollectionConfig, TunnelCfdTunnelResponseCollectionAttrs> = {
  wireType: "cloudflare_tunnel_cfd_tunnel_response_collection",
  fields: {
    excludePrefix: "exclude_prefix",
    existedAt: "existed_at",
    includePrefix: "include_prefix",
    isDeleted: "is_deleted",
    name: "name",
    page: "page",
    perPage: "per_page",
    status: "status",
    wasActiveAt: "was_active_at",
    wasInactiveAt: "was_inactive_at",
  },
};
