// Code generated by `ubx sdk gen` from cloudflare_hold. DO NOT EDIT.
package zoneholds

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type HoldConfig struct {
	// path parameter, not part of the API's own resource representation
	ZoneId any
	// path parameter, not part of the API's own resource representation
	ZoneName any
}

type HoldAttrs struct {
	// Whether the hostname is currently subject to a zone hold.
	Hold any
	// The RFC3339-formatted timestamp at which the hold will be automatically re-enabled, if the hold was temporarily disabled. Null if the hold is permanently enabled or not set.
	HoldAfter any
	// Whether the hold extends to block subdomains of the held zone.
	IncludeSubdomains any
	// path parameter, not part of the API's own resource representation
	ZoneId any
	// path parameter, not part of the API's own resource representation
	ZoneName any
}

var Hold = ubx.ResourceBinding{
	WireType: "cloudflare_hold",
	Fields: ubx.FieldMap{
		"ZoneId":   ubx.FieldSpec{WireName: "zone_id"},
		"ZoneName": ubx.FieldSpec{WireName: "zone_name"},
	},
}
