// Code generated by `ubx sdk gen` from cloudflare_smartshield_response_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SmartshieldResponseCollectionConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface SmartshieldResponseCollectionAttrs {
  page: number;
  perPage: number;
  /** Identifier. */
  zoneId: string;
}

export const SmartshieldResponseCollection: DataSourceBinding<SmartshieldResponseCollectionConfig, SmartshieldResponseCollectionAttrs> = {
  wireType: "cloudflare_smartshield_response_collection",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
