# Code generated by `ubx sdk gen` from cloudflare_item. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Item_Result:
    checksum: Any = None
    chunks_count: Any = None
    created_at: Any = None
    error: Any = None
    file_size: Any = None
    id: Any = None
    key: Any = None
    last_seen_at: Any = None
    metadata: Any = None
    namespace: Any = None
    next_action: Any = None
    source_id: Any = None
    status: Any = None

@dataclasses.dataclass
class Item_ResultInfo:
    count: Any = None
    page: Any = None
    per_page: Any = None
    total_count: Any = None

@dataclasses.dataclass
class ItemConfig:
    account_id: Any = None
    # AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores.
    id: Any = None
    # Filter items by their unique ID. Returns at most one item.
    item_id: Any = None
    # Filter items by their exact key (object key / filename). Keys are unique per source, so combine with `source` to disambiguate across data sources.
    key: Any = None
    # JSON-encoded metadata filter using Vectorize filter syntax. Examples: {"folder":"reports/"}, {"timestamp":{"$gte":1700000000000}}, {"folder":{"$in":["docs/","reports/"]}}
    metadata_filter: Any = None
    name: Any = None
    page: Any = None
    per_page: Any = None
    search: Any = None
    # Sort order for items. "status" (default) sorts by status priority then last_seen_at. "modified_at" sorts by file modification time (most recent first), falling back to created_at.
    sort_by: Any = None
    # Filter items by source_id. Use "builtin" for uploaded files, or a source identifier like "web-crawler:https://example.com".
    source: Any = None
    status: Any = None

@dataclasses.dataclass
class ItemAttrs:
    account_id: Any = None
    # AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores.
    id: Any = None
    # Filter items by their unique ID. Returns at most one item.
    item_id: Any = None
    # Filter items by their exact key (object key / filename). Keys are unique per source, so combine with `source` to disambiguate across data sources.
    key: Any = None
    # JSON-encoded metadata filter using Vectorize filter syntax. Examples: {"folder":"reports/"}, {"timestamp":{"$gte":1700000000000}}, {"folder":{"$in":["docs/","reports/"]}}
    metadata_filter: Any = None
    name: Any = None
    page: Any = None
    per_page: Any = None
    result: Any = None
    result_info: Any = None
    search: Any = None
    # Sort order for items. "status" (default) sorts by status priority then last_seen_at. "modified_at" sorts by file modification time (most recent first), falling back to created_at.
    sort_by: Any = None
    # Filter items by source_id. Use "builtin" for uploaded files, or a source identifier like "web-crawler:https://example.com".
    source: Any = None
    status: Any = None
    success: Any = None

Item = ubx.DataSourceBinding(
    wire_type="cloudflare_item",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "id": ubx.FieldSpec(wire_name="id"),
        "item_id": ubx.FieldSpec(wire_name="item_id"),
        "key": ubx.FieldSpec(wire_name="key"),
        "metadata_filter": ubx.FieldSpec(wire_name="metadata_filter"),
        "name": ubx.FieldSpec(wire_name="name"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "search": ubx.FieldSpec(wire_name="search"),
        "sort_by": ubx.FieldSpec(wire_name="sort_by"),
        "source": ubx.FieldSpec(wire_name="source"),
        "status": ubx.FieldSpec(wire_name="status"),
    },
)
