// Code generated by `ubx sdk gen` from cloudflare_intel_components_schemas_single_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IntelComponentsSchemasSingleResponse_StartEndParams {
  /** Defaults to the current date. */
  end?: string | Computed<string>;
  /** Defaults to 30 days before the end parameter value. */
  start?: string | Computed<string>;
}

const IntelComponentsSchemasSingleResponse_StartEndParamsFields: FieldMap = {
  end: "end",
  start: "start",
};

export interface IntelComponentsSchemasSingleResponseConfig {
  ipv4?: string | Computed<string>;
  /** Requested page within paginated list of results. */
  page?: number | Computed<number>;
  /** Maximum number of results requested. */
  perPage?: number | Computed<number>;
  startEndParams?: IntelComponentsSchemasSingleResponse_StartEndParams | Computed<IntelComponentsSchemasSingleResponse_StartEndParams>;
}

export interface IntelComponentsSchemasSingleResponseAttrs {
  /** Identifier. */
  accountId: string;
  ipv4: string;
  /** Requested page within paginated list of results. */
  page: number;
  /** Maximum number of results requested. */
  perPage: number;
  startEndParams: IntelComponentsSchemasSingleResponse_StartEndParams;
}

export const IntelComponentsSchemasSingleResponse: DataSourceBinding<IntelComponentsSchemasSingleResponseConfig, IntelComponentsSchemasSingleResponseAttrs> = {
  wireType: "cloudflare_intel_components_schemas_single_response",
  fields: {
    ipv4: "ipv4",
    page: "page",
    perPage: "per_page",
    startEndParams: {
      wireName: "start_end_params",
      kind: "object",
      fields: IntelComponentsSchemasSingleResponse_StartEndParamsFields,
    },
  },
};
