# Code generated by `ubx sdk gen` from cloudflare_effective_redirect_uri. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class EffectiveRedirectUri_Result:
    redirect_uri: Any = None
    source: Any = None

@dataclasses.dataclass
class EffectiveRedirectUriConfig:
    account_id: Any = None
    # Unique identifier for the MCP portal.
    portal_id: Any = None
    # Unique identifier for the MCP server.
    server_id: Any = None

@dataclasses.dataclass
class EffectiveRedirectUriAttrs:
    account_id: Any = None
    # Unique identifier for the MCP portal.
    portal_id: Any = None
    result: Any = None
    # Unique identifier for the MCP server.
    server_id: Any = None
    success: Any = None

EffectiveRedirectUri = ubx.DataSourceBinding(
    wire_type="cloudflare_effective_redirect_uri",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "portal_id": ubx.FieldSpec(wire_name="portal_id"),
        "server_id": ubx.FieldSpec(wire_name="server_id"),
    },
)
