# Code generated by `ubx sdk gen` from cloudflare_images_image_variant_list_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ImagesImageVariantListResponseConfig:
    pass

@dataclasses.dataclass
class ImagesImageVariantListResponseAttrs:
    # Account identifier tag.
    account_id: Any = None

ImagesImageVariantListResponse = ubx.DataSourceBinding(
    wire_type="cloudflare_images_image_variant_list_response",
    fields={
    },
)
