# Code generated by `ubx sdk gen` from cloudflare_tls_certificates_and_hostnames_ssl_verification_response_collection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TlsCertificatesAndHostnamesSslVerificationResponseCollectionConfig:
    # Immediately retry SSL Verification.
    retry: Any = None
    # Identifier.
    zone_id: Any = None

@dataclasses.dataclass
class TlsCertificatesAndHostnamesSslVerificationResponseCollectionAttrs:
    # Immediately retry SSL Verification.
    retry: Any = None
    # Identifier.
    zone_id: Any = None

TlsCertificatesAndHostnamesSslVerificationResponseCollection = ubx.DataSourceBinding(
    wire_type="cloudflare_tls_certificates_and_hostnames_ssl_verification_response_collection",
    fields={
        "retry": ubx.FieldSpec(wire_name="retry"),
        "zone_id": ubx.FieldSpec(wire_name="zone_id"),
    },
)
