// Code generated by `ubx sdk gen` from cloudflare_aaa_schemas_response_collection. DO NOT EDIT.
package notificationmechanismeligibility

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AaaSchemasResponseCollectionConfig struct {
}

type AaaSchemasResponseCollectionAttrs struct {
	// The account id
	AccountId any
}

var AaaSchemasResponseCollection = ubx.DataSourceBinding{
	WireType: "cloudflare_aaa_schemas_response_collection",
	Fields: ubx.FieldMap{
	},
}
