// Code generated by `ubx sdk gen` from cloudflare_managed. DO NOT EDIT.
package rules

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Managed_Metadata struct {
	FetchedAt any
	TotalRules any
}

type Managed_Rules struct {
	Description any
	Name any
}

type ManagedConfig struct {
	AccountId any
}

type ManagedAttrs struct {
	AccountId any
	Metadata any
	Rules any
}

var Managed = ubx.DataSourceBinding{
	WireType: "cloudflare_managed",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
