// Code generated by `ubx sdk gen` from cloudflare_attacker. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Attacker_Items {
  type: string | Computed<string>;
}

export interface AttackerConfig {
  /** Account ID. */
  accountId: string | Computed<string>;
  /** Array of dataset IDs to query attackers from. If not provided, uses the default dataset. */
  datasetIds?: string[] | Computed<string[]>;
}

export interface AttackerAttrs {
  /** Account ID. */
  accountId: string;
  /** Array of dataset IDs to query attackers from. If not provided, uses the default dataset. */
  datasetIds: string[];
  items: Attacker_Items;
  type: string;
}

export const Attacker: DataSourceBinding<AttackerConfig, AttackerAttrs> = {
  wireType: "cloudflare_attacker",
  fields: {
    accountId: "account_id",
    datasetIds: "dataset_ids",
  },
};
