// Code generated by `ubx sdk gen` from cloudflare_mcn_get_onramp_response. DO NOT EDIT.
package onramps

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type McnGetOnrampResponseConfig struct {
	AdoptedHubId any
	AttachedHubs any
	AttachedVpcs any
	// Sets the cloud-side ASN. If unset or zero, the cloud's default ASN takes effect.
	CloudAsn any
	CloudType any
	Description any
	// Enables BGP routing. When enabling this feature, set both install_routes_in_cloud and install_routes_in_magic_wan to false.
	DynamicRouting any
	HubProviderId any
	InstallRoutesInCloud any
	InstallRoutesInMagicWan any
	ManageHubToHubAttachments any
	ManageVpcToHubAttachments any
	Name any
	Region any
	Type any
	Vpc any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	OnrampId any
}

type McnGetOnrampResponseAttrs struct {
	AdoptedHubId any
	AttachedHubs any
	AttachedVpcs any
	// Sets the cloud-side ASN. If unset or zero, the cloud's default ASN takes effect.
	CloudAsn any
	CloudType any
	Description any
	// Enables BGP routing. When enabling this feature, set both install_routes_in_cloud and install_routes_in_magic_wan to false.
	DynamicRouting any
	HubProviderId any
	InstallRoutesInCloud any
	InstallRoutesInMagicWan any
	ManageHubToHubAttachments any
	ManageVpcToHubAttachments any
	Name any
	Region any
	Type any
	Vpc any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	OnrampId any
}

var McnGetOnrampResponse = ubx.ResourceBinding{
	WireType: "cloudflare_mcn_get_onramp_response",
	Fields: ubx.FieldMap{
		"AdoptedHubId": ubx.FieldSpec{WireName: "adopted_hub_id"},
		"AttachedHubs": ubx.FieldSpec{WireName: "attached_hubs"},
		"AttachedVpcs": ubx.FieldSpec{WireName: "attached_vpcs"},
		"CloudAsn": ubx.FieldSpec{WireName: "cloud_asn"},
		"CloudType": ubx.FieldSpec{WireName: "cloud_type"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"DynamicRouting": ubx.FieldSpec{WireName: "dynamic_routing"},
		"HubProviderId": ubx.FieldSpec{WireName: "hub_provider_id"},
		"InstallRoutesInCloud": ubx.FieldSpec{WireName: "install_routes_in_cloud"},
		"InstallRoutesInMagicWan": ubx.FieldSpec{WireName: "install_routes_in_magic_wan"},
		"ManageHubToHubAttachments": ubx.FieldSpec{WireName: "manage_hub_to_hub_attachments"},
		"ManageVpcToHubAttachments": ubx.FieldSpec{WireName: "manage_vpc_to_hub_attachments"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"Type": ubx.FieldSpec{WireName: "type"},
		"Vpc": ubx.FieldSpec{WireName: "vpc"},
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"OnrampId": ubx.FieldSpec{WireName: "onramp_id"},
	},
}
