// Code generated by `ubx sdk gen` from cloudflare_load_balancing_monitor_response_single. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LoadBalancingMonitorResponseSingle_Result {
  allowInsecure?: boolean | Computed<boolean>;
  consecutiveDown?: number | Computed<number>;
  consecutiveUp?: number | Computed<number>;
  createdOn?: string | Computed<string>;
  description?: string | Computed<string>;
  expectedBody?: string | Computed<string>;
  expectedCodes?: string | Computed<string>;
  followRedirects?: boolean | Computed<boolean>;
  header?: Record<string, string[]> | Computed<Record<string, string[]>>;
  id?: string | Computed<string>;
  interval?: number | Computed<number>;
  method?: string | Computed<string>;
  modifiedOn?: string | Computed<string>;
  path?: string | Computed<string>;
  port?: number | Computed<number>;
  probeZone?: string | Computed<string>;
  retries?: number | Computed<number>;
  timeout?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface LoadBalancingMonitorResponseSingleConfig {
  /** Do not validate the certificate when monitor use HTTPS. This parameter is currently only valid for HTTP and HTTPS monitors. */
  allowInsecure?: boolean | Computed<boolean>;
  /** To be marked unhealthy the monitored origin must fail this healthcheck N consecutive times. */
  consecutiveDown?: number | Computed<number>;
  /** To be marked healthy the monitored origin must pass this healthcheck N consecutive times. */
  consecutiveUp?: number | Computed<number>;
  /** Object description. */
  description?: string | Computed<string>;
  /** A case-insensitive sub-string to look for in the response body. If this string is not found, the origin will be marked as unhealthy. This parameter is only valid for HTTP and HTTPS monitors. */
  expectedBody?: string | Computed<string>;
  /** The expected HTTP response code or code range of the health check. This parameter is only valid for HTTP and HTTPS monitors. */
  expectedCodes?: string | Computed<string>;
  /** Follow redirects if returned by the origin. This parameter is only valid for HTTP and HTTPS monitors. */
  followRedirects?: boolean | Computed<boolean>;
  /** The HTTP request headers to send in the health check. It is recommended you set a Host header by default. The User-Agent header cannot be overridden. This parameter is only valid for HTTP and HTTPS monitors. */
  header?: Record<string, string[]> | Computed<Record<string, string[]>>;
  /** The interval between each health check. Shorter intervals may improve failover time, but will increase load on the origins as we check from multiple locations. */
  interval?: number | Computed<number>;
  /** The method to use for the health check. This defaults to 'GET' for HTTP/HTTPS based checks and 'connection_established' for TCP based health checks. */
  method?: string | Computed<string>;
  /** The endpoint path you want to conduct a health check against. This parameter is only valid for HTTP and HTTPS monitors. */
  path?: string | Computed<string>;
  /** The port number to connect to for the health check. Required for TCP, UDP, and SMTP checks. HTTP and HTTPS checks should only define the port when using a non-standard port (HTTP: default 80, HTTPS: default 443). */
  port?: number | Computed<number>;
  /** Assign this monitor to emulate the specified zone while probing. This parameter is only valid for HTTP and HTTPS monitors. */
  probeZone?: string | Computed<string>;
  /** The number of retries to attempt in case of a timeout before marking the origin as unhealthy. Retries are attempted immediately. */
  retries?: number | Computed<number>;
  /** The timeout (in seconds) before marking the health check as failed. */
  timeout?: number | Computed<number>;
  /** The protocol to use for the health check. Currently supported protocols are 'HTTP','HTTPS', 'TCP', 'ICMP-PING', 'UDP-ICMP', and 'SMTP'. */
  type?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  monitorId: string | Computed<string>;
}

export interface LoadBalancingMonitorResponseSingleAttrs {
  /** Do not validate the certificate when monitor use HTTPS. This parameter is currently only valid for HTTP and HTTPS monitors. */
  allowInsecure: boolean;
  /** To be marked unhealthy the monitored origin must fail this healthcheck N consecutive times. */
  consecutiveDown: number;
  /** To be marked healthy the monitored origin must pass this healthcheck N consecutive times. */
  consecutiveUp: number;
  /** Object description. */
  description: string;
  /** A case-insensitive sub-string to look for in the response body. If this string is not found, the origin will be marked as unhealthy. This parameter is only valid for HTTP and HTTPS monitors. */
  expectedBody: string;
  /** The expected HTTP response code or code range of the health check. This parameter is only valid for HTTP and HTTPS monitors. */
  expectedCodes: string;
  /** Follow redirects if returned by the origin. This parameter is only valid for HTTP and HTTPS monitors. */
  followRedirects: boolean;
  /** The HTTP request headers to send in the health check. It is recommended you set a Host header by default. The User-Agent header cannot be overridden. This parameter is only valid for HTTP and HTTPS monitors. */
  header: Record<string, string[]>;
  /** The interval between each health check. Shorter intervals may improve failover time, but will increase load on the origins as we check from multiple locations. */
  interval: number;
  /** The method to use for the health check. This defaults to 'GET' for HTTP/HTTPS based checks and 'connection_established' for TCP based health checks. */
  method: string;
  /** The endpoint path you want to conduct a health check against. This parameter is only valid for HTTP and HTTPS monitors. */
  path: string;
  /** The port number to connect to for the health check. Required for TCP, UDP, and SMTP checks. HTTP and HTTPS checks should only define the port when using a non-standard port (HTTP: default 80, HTTPS: default 443). */
  port: number;
  /** Assign this monitor to emulate the specified zone while probing. This parameter is only valid for HTTP and HTTPS monitors. */
  probeZone: string;
  /** The requested resource, present when the API call succeeds. (AI-inferred) */
  result: LoadBalancingMonitorResponseSingle_Result;
  /** The number of retries to attempt in case of a timeout before marking the origin as unhealthy. Retries are attempted immediately. */
  retries: number;
  /** The timeout (in seconds) before marking the health check as failed. */
  timeout: number;
  /** The protocol to use for the health check. Currently supported protocols are 'HTTP','HTTPS', 'TCP', 'ICMP-PING', 'UDP-ICMP', and 'SMTP'. */
  type: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  monitorId: string;
}

export const LoadBalancingMonitorResponseSingle: ResourceBinding<LoadBalancingMonitorResponseSingleConfig, LoadBalancingMonitorResponseSingleAttrs> = {
  wireType: "cloudflare_load_balancing_monitor_response_single",
  fields: {
    allowInsecure: "allow_insecure",
    consecutiveDown: "consecutive_down",
    consecutiveUp: "consecutive_up",
    description: "description",
    expectedBody: "expected_body",
    expectedCodes: "expected_codes",
    followRedirects: "follow_redirects",
    header: "header",
    interval: "interval",
    method: "method",
    path: "path",
    port: "port",
    probeZone: "probe_zone",
    retries: "retries",
    timeout: "timeout",
    type: "type",
    accountId: "account_id",
    monitorId: "monitor_id",
  },
};
