// Code generated by `ubx sdk gen` from cloudflare_magic_lan_single_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MagicLanSingleResponse_Nat {
  /** A valid CIDR notation representing an IP range. */
  staticPrefix?: string | Computed<string>;
}

export interface MagicLanSingleResponse_Result_RoutedSubnets {
  nat?: MagicLanSingleResponse_Nat | Computed<MagicLanSingleResponse_Nat>;
  nextHop?: string | Computed<string>;
  prefix?: string | Computed<string>;
}

export interface MagicLanSingleResponse_Result_StaticAddressing_DhcpRelay {
  /** List of DHCP server IPs. */
  serverAddresses?: string[] | Computed<string[]>;
}

export interface MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptions {
  code?: number | Computed<number>;
  type?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface MagicLanSingleResponse_Result_StaticAddressing_DhcpServer {
  /** Optional list of custom DHCP options to include in DHCP responses. Only valid when DHCP server is enabled. */
  dhcpOptions?: MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptions[] | Computed<MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptions[]>;
  /** A valid IPv4 address. */
  dhcpPoolEnd?: string | Computed<string>;
  /** A valid IPv4 address. */
  dhcpPoolStart?: string | Computed<string>;
  /** A valid IPv4 address. */
  dnsServer?: string | Computed<string>;
  dnsServers?: string[] | Computed<string[]>;
  /** Mapping of MAC addresses to IP addresses */
  reservations?: Record<string, string> | Computed<Record<string, string>>;
}

export interface MagicLanSingleResponse_Result_StaticAddressing {
  /** A valid CIDR notation representing an IP range. */
  address: string | Computed<string>;
  dhcpRelay?: MagicLanSingleResponse_Result_StaticAddressing_DhcpRelay | Computed<MagicLanSingleResponse_Result_StaticAddressing_DhcpRelay>;
  dhcpServer?: MagicLanSingleResponse_Result_StaticAddressing_DhcpServer | Computed<MagicLanSingleResponse_Result_StaticAddressing_DhcpServer>;
  /** A valid CIDR notation representing an IP range. */
  secondaryAddress?: string | Computed<string>;
  /** A valid CIDR notation representing an IP range. */
  virtualAddress?: string | Computed<string>;
}

export interface MagicLanSingleResponse_Result {
  bondId?: number | Computed<number>;
  /** mark true to use this LAN for HA probing. only works for site with HA turned on. only one LAN can be set as the ha_link. */
  haLink?: boolean | Computed<boolean>;
  /** Identifier */
  id?: string | Computed<string>;
  /** mark true to use this LAN for source-based breakout traffic */
  isBreakout?: boolean | Computed<boolean>;
  /** mark true to use this LAN for source-based prioritized traffic */
  isPrioritized?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
  nat?: MagicLanSingleResponse_Nat | Computed<MagicLanSingleResponse_Nat>;
  physport?: number | Computed<number>;
  routedSubnets?: MagicLanSingleResponse_Result_RoutedSubnets[] | Computed<MagicLanSingleResponse_Result_RoutedSubnets[]>;
  /** Identifier */
  siteId?: string | Computed<string>;
  /** If the site is not configured in high availability mode, this configuration is optional (if omitted, use DHCP). However, if in high availability mode, static_address is required along with secondary and virtual address. */
  staticAddressing?: MagicLanSingleResponse_Result_StaticAddressing | Computed<MagicLanSingleResponse_Result_StaticAddressing>;
  /** VLAN ID. Use zero for untagged. */
  vlanTag?: number | Computed<number>;
}

const MagicLanSingleResponse_NatFields: FieldMap = {
  staticPrefix: "static_prefix",
};

const MagicLanSingleResponse_Result_RoutedSubnetsFields: FieldMap = {
  nat: {
    wireName: "nat",
    kind: "object",
    fields: MagicLanSingleResponse_NatFields,
  },
  nextHop: "next_hop",
  prefix: "prefix",
};

const MagicLanSingleResponse_Result_StaticAddressing_DhcpRelayFields: FieldMap = {
  serverAddresses: "server_addresses",
};

const MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptionsFields: FieldMap = {
  code: "code",
  type: "type",
  value: "value",
};

const MagicLanSingleResponse_Result_StaticAddressing_DhcpServerFields: FieldMap = {
  dhcpOptions: {
    wireName: "dhcp_options",
    kind: "list",
    fields: MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptionsFields,
  },
  dhcpPoolEnd: "dhcp_pool_end",
  dhcpPoolStart: "dhcp_pool_start",
  dnsServer: "dns_server",
  dnsServers: "dns_servers",
  reservations: "reservations",
};

const MagicLanSingleResponse_Result_StaticAddressingFields: FieldMap = {
  address: "address",
  dhcpRelay: {
    wireName: "dhcp_relay",
    kind: "object",
    fields: MagicLanSingleResponse_Result_StaticAddressing_DhcpRelayFields,
  },
  dhcpServer: {
    wireName: "dhcp_server",
    kind: "object",
    fields: MagicLanSingleResponse_Result_StaticAddressing_DhcpServerFields,
  },
  secondaryAddress: "secondary_address",
  virtualAddress: "virtual_address",
};

export interface MagicLanSingleResponseConfig {
  /** The bonded interface this LAN is attached to, if any. (AI-inferred) */
  bondId?: number | Computed<number>;
  /** mark true to use this LAN for HA probing. only works for site with HA turned on. only one LAN can be set as the ha_link. */
  haLink?: boolean | Computed<boolean>;
  /** mark true to use this LAN for source-based breakout traffic */
  isBreakout?: boolean | Computed<boolean>;
  /** mark true to use this LAN for source-based prioritized traffic */
  isPrioritized?: boolean | Computed<boolean>;
  /** The name of the LAN interface. (AI-inferred) */
  name?: string | Computed<string>;
  nat?: MagicLanSingleResponse_Nat | Computed<MagicLanSingleResponse_Nat>;
  /** The physical port this LAN interface is attached to. (AI-inferred) */
  physport?: number | Computed<number>;
  /** The subnets routed through this LAN interface. (AI-inferred) */
  routedSubnets?: MagicLanSingleResponse_Result_RoutedSubnets[] | Computed<MagicLanSingleResponse_Result_RoutedSubnets[]>;
  /** If the site is not configured in high availability mode, this configuration is optional (if omitted, use DHCP). However, if in high availability mode, static_address is required along with secondary and virtual address. */
  staticAddressing?: MagicLanSingleResponse_Result_StaticAddressing | Computed<MagicLanSingleResponse_Result_StaticAddressing>;
  /** VLAN ID. Use zero for untagged. */
  vlanTag?: number | Computed<number>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  siteId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  lanId: string | Computed<string>;
}

export interface MagicLanSingleResponseAttrs {
  /** The bonded interface this LAN is attached to, if any. (AI-inferred) */
  bondId: number;
  /** mark true to use this LAN for HA probing. only works for site with HA turned on. only one LAN can be set as the ha_link. */
  haLink: boolean;
  /** mark true to use this LAN for source-based breakout traffic */
  isBreakout: boolean;
  /** mark true to use this LAN for source-based prioritized traffic */
  isPrioritized: boolean;
  /** The name of the LAN interface. (AI-inferred) */
  name: string;
  nat: MagicLanSingleResponse_Nat;
  /** The physical port this LAN interface is attached to. (AI-inferred) */
  physport: number;
  /** The requested resource, present when the API call succeeds. (AI-inferred) */
  result: MagicLanSingleResponse_Result;
  /** The subnets routed through this LAN interface. (AI-inferred) */
  routedSubnets: MagicLanSingleResponse_Result_RoutedSubnets[];
  /** If the site is not configured in high availability mode, this configuration is optional (if omitted, use DHCP). However, if in high availability mode, static_address is required along with secondary and virtual address. */
  staticAddressing: MagicLanSingleResponse_Result_StaticAddressing;
  /** VLAN ID. Use zero for untagged. */
  vlanTag: number;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  siteId: string;
  /** path parameter, not part of the API's own resource representation */
  lanId: string;
}

export const MagicLanSingleResponse: ResourceBinding<MagicLanSingleResponseConfig, MagicLanSingleResponseAttrs> = {
  wireType: "cloudflare_magic_lan_single_response",
  fields: {
    bondId: "bond_id",
    haLink: "ha_link",
    isBreakout: "is_breakout",
    isPrioritized: "is_prioritized",
    name: "name",
    nat: {
      wireName: "nat",
      kind: "object",
      fields: MagicLanSingleResponse_NatFields,
    },
    physport: "physport",
    routedSubnets: {
      wireName: "routed_subnets",
      kind: "list",
      fields: MagicLanSingleResponse_Result_RoutedSubnetsFields,
    },
    staticAddressing: {
      wireName: "static_addressing",
      kind: "object",
      fields: MagicLanSingleResponse_Result_StaticAddressingFields,
    },
    vlanTag: "vlan_tag",
    accountId: "account_id",
    siteId: "site_id",
    lanId: "lan_id",
  },
};
