# Code generated by `ubx sdk gen` from cloudflare_zero_trust_gateway_single_response_4. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Expiration_ExpiresAt:
    pass

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Expiration:
    # Defines the default duration a policy active in minutes. Must set in order to use the `reset_expiration` endpoint on this rule.
    duration: Any = None
    # Indicates whether the policy is expired.
    expired: Any = None
    expires_at: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_AuditSsh:
    # Enable SSH command logging.
    command_logging: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_BisoAdminControls:
    # Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
    copy: Any = None
    # Set to false to enable copy-pasting. Only applies when `version == "v1"`.
    dcp: Any = None
    # Set to false to enable downloading. Only applies when `version == "v1"`.
    dd: Any = None
    # Set to false to enable keyboard usage. Only applies when `version == "v1"`.
    dk: Any = None
    # Configure download behavior. When set to remote_only, users can view downloads but cannot save them. If this field is absent, downloading remains enabled. Applies only when version == "v2".
    download: Any = None
    # Set to false to enable printing. Only applies when `version == "v1"`.
    dp: Any = None
    # Set to false to enable uploading. Only applies when `version == "v1"`.
    du: Any = None
    # Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
    keyboard: Any = None
    # Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
    paste: Any = None
    # Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
    printing: Any = None
    # Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
    upload: Any = None
    # Indicate which version of the browser isolation controls should apply.
    version: Any = None
    # Specify the watermark ID (UUID) to apply to the isolated browser session. When present, enables watermark rendering in the isolated browser.
    wm_id: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_BlockPage:
    # Specify whether to pass the context information as query parameters.
    include_context: Any = None
    # Specify the URI to which the user is redirected.
    target_uri: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_CheckSession:
    # Sets the required session freshness threshold. The API returns a normalized version of this value.
    duration: Any = None
    # Enable session enforcement.
    enforce: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolvers_Ipv4:
    ip: Any = None
    port: Any = None
    route_through_private_network: Any = None
    vnet_id: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolvers:
    ipv4: Any = None
    ipv6: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_Egress:
    # Specify the IPv4 address to use for egress.
    ipv4: Any = None
    # Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
    ipv4_fallback: Any = None
    # Specify the IPv6 range to use for egress.
    ipv6: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ForensicCopy:
    # Enable sending the copy to storage.
    enabled: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_L4override:
    # Defines the IPv4 or IPv6 address.
    ip: Any = None
    # Defines a port number to use for TCP/UDP overrides.
    port: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_NotificationSettings:
    # Enable notification.
    enabled: Any = None
    # Indicates whether to pass the context information as query parameters.
    include_context: Any = None
    # Customize the message shown in the notification.
    msg: Any = None
    # Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
    support_url: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_Quarantine:
    # Specify the types of files to sandbox.
    file_types: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_Redirect:
    # Specify whether to pass the context information as query parameters.
    include_context: Any = None
    # Specify whether to append the path and query parameters from the original request to target_uri.
    preserve_path_and_query: Any = None
    # Specify the URI to which the user is redirected.
    target_uri: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ResolveDnsInternally:
    # Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
    fallback: Any = None
    # Specify the internal DNS view identifier to pass to the internal DNS service.
    view_id: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings_UntrustedCert:
    # Defines the action performed when an untrusted certificate seen. The default action an error with HTTP code 526.
    action: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_RuleSettings:
    # Add custom headers to allowed requests as key-value pairs. Use header names as keys that map to arrays of header values. Header values may contain `@{selector.name}` variable references that are interpolated at the edge. Use `@@{` to escape a literal `@{`. A maximum of 20 header operations (add + set + delete) is allowed per policy. Each header name may not exceed 256 bytes and each header value may not exceed 4 KB. Settable only for `http` rules with the action set to `allow`.
    add_headers: Any = None
    # Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
    allow_child_bypass: Any = None
    # Define the settings for the Audit SSH action. Settable only for `l4` rules with `audit_ssh` action.
    audit_ssh: Any = None
    # Configure browser isolation behavior. Settable only for `http` rules with the action set to `isolate`.
    biso_admin_controls: Any = None
    # Configure custom block page settings. If missing or null, use the account settings. Settable only for `http` rules with the action set to `block`.
    block_page: Any = None
    # Enable the custom block page. Settable only for `dns` rules with action `block`.
    block_page_enabled: Any = None
    # Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for `dns`, `l4`, and `http` rules when the action set to `block`.
    block_reason: Any = None
    # Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
    bypass_parent_rule: Any = None
    # Configure session check behavior. Settable only for `l4` and `http` rules with the action set to `allow`.
    check_session: Any = None
    # Remove headers from allowed requests by name. A maximum of 20 header operations (add + set + delete) is allowed per policy. Each header name may not exceed 256 bytes. Settable only for `http` rules with the action set to `allow`.
    delete_headers: Any = None
    # Configure custom resolvers to route queries that match the resolver policy. Unused with 'resolve_dns_through_cloudflare' or 'resolve_dns_internally' settings. DNS queries get routed to the address closest to their origin. Only valid when a rule's action set to 'resolve'. Settable only for `dns_resolver` rules.
    dns_resolvers: Any = None
    # Configure how Gateway Proxy traffic egresses. You can enable this setting for rules with Egress actions and filters, or omit it to indicate local egress via WARP IPs. Settable only for `egress` rules.
    egress: Any = None
    # Configure whether a copy of the HTTP request will be sent to storage when the rule matches.
    forensic_copy: Any = None
    # Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for `dns` and `dns_resolver` rules.
    ignore_cname_category_matches: Any = None
    # Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for `dns` rules.
    insecure_disable_dnssec_validation: Any = None
    # Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for `dns` and `dns_resolver` rules.
    ip_categories: Any = None
    # Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for `dns` and `dns_resolver` rules.
    ip_indicator_feeds: Any = None
    # Send matching traffic to the supplied destination IP address and port. Settable only for `l4` rules with the action set to `l4_override`.
    l4override: Any = None
    # Configure a notification to display on the user's device when this rule matched. Settable for all types of rules with the action set to `block`.
    notification_settings: Any = None
    # Defines a hostname for override, for the matching DNS queries. Settable only for `dns` rules with the action set to `override`.
    override_host: Any = None
    # Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for `dns` rules with the action set to `override`.
    override_ips: Any = None
    # Configure DLP payload logging. Settable only for `http` rules.
    payload_log: Any = None
    # Configure settings that apply to quarantine rules. Settable only for `http` rules.
    quarantine: Any = None
    # Apply settings to redirect rules. Settable only for `http` rules with the action set to `redirect`.
    redirect: Any = None
    # Configure to forward the query to the internal DNS service, passing the specified 'view_id' as input. Not used when 'dns_resolvers' is specified or 'resolve_dns_through_cloudflare' is set. Only valid when a rule's action set to 'resolve'. Settable only for `dns_resolver` rules.
    resolve_dns_internally: Any = None
    # Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for `dns_resolver` rules.
    resolve_dns_through_cloudflare: Any = None
    # Replace existing headers on allowed requests with the specified key-value pairs. If a header does not exist, it is added. Header values may contain `@{selector.name}` variable references that are interpolated at the edge. Use `@@{` to escape a literal `@{`. A maximum of 20 header operations (add + set + delete) is allowed per policy. Each header name may not exceed 256 bytes and each header value may not exceed 4 KB. Settable only for `http` rules with the action set to `allow`.
    set_headers: Any = None
    # Configure behavior when an upstream certificate is invalid or an SSL error occurs. Settable only for `http` rules with the action set to `allow`.
    untrusted_cert: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result_Schedule:
    # Specify the time intervals when the rule is active on Fridays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Fridays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    fri: Any = None
    # Specify the time intervals when the rule is active on Mondays, in the increasing order from 00:00-24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    mon: Any = None
    # Specify the time intervals when the rule is active on Saturdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Saturdays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    sat: Any = None
    # Specify the time intervals when the rule is active on Sundays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Sundays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    sun: Any = None
    # Specify the time intervals when the rule is active on Thursdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Thursdays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    thu: Any = None
    # Specify the time zone for rule evaluation. When a [valid time zone city name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
    time_zone: Any = None
    # Specify the time intervals when the rule is active on Tuesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Tuesdays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    tue: Any = None
    # Specify the time intervals when the rule is active on Wednesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Wednesdays. API returns a formatted version of this string, which may cause Terraform drift if a unformatted value is used.
    wed: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4_Result:
    # Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to `true`.
    action: Any = None
    created_at: Any = None
    # Indicate the date of deletion, if any.
    deleted_at: Any = None
    # Specify the rule description.
    description: Any = None
    # Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    device_posture: Any = None
    # Specify whether the rule is enabled.
    enabled: Any = None
    # Defines the expiration time stamp and default duration of a DNS policy. Takes precedence over the policy's `schedule` configuration, if any. This does not apply to HTTP or network policies. Settable only for `dns` rules.
    expiration: Any = None
    # Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
    filters: Any = None
    # Identify the API resource with a UUID.
    id: Any = None
    # Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    identity: Any = None
    # Specify the rule name.
    name: Any = None
    # Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value. Refer to [Order of enforcement](http://developers.cloudflare.com/learning-paths/secure-internet-traffic/understand-policies/order-of-enforcement/#manage-precedence-with-terraform) to manage precedence via Terraform.
    precedence: Any = None
    # Indicate that this rule is shared via the Orgs API and read only.
    read_only: Any = None
    # Defines settings for this rule. Settings apply only to specific rule types and must use compatible selectors. If Terraform detects drift, confirm the setting supports your rule type and check whether the API modifies the value. Use API-returned values in your configuration to prevent drift.
    rule_settings: Any = None
    # Defines the schedule for activating DNS policies. Settable only for `dns` and `dns_resolver` rules.
    schedule: Any = None
    # Indicate that this rule is sharable via the Orgs API.
    sharable: Any = None
    # Provide the account tag of the account that created the rule.
    source_account: Any = None
    # Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    traffic: Any = None
    updated_at: Any = None
    # Indicate the version number of the rule(read-only).
    version: Any = None
    # Indicate a warning for a misconfigured rule, if any.
    warning_status: Any = None

_ZeroTrustGatewaySingleResponse4_Expiration_ExpiresAtFields = {
}

_ZeroTrustGatewaySingleResponse4_ExpirationFields = {
    "duration": ubx.FieldSpec(wire_name="duration"),
    "expired": ubx.FieldSpec(wire_name="expired"),
    "expires_at": ubx.FieldSpec(
        wire_name="expires_at",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Expiration_ExpiresAtFields,
    ),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_AuditSshFields = {
    "command_logging": ubx.FieldSpec(wire_name="command_logging"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_BisoAdminControlsFields = {
    "copy": ubx.FieldSpec(wire_name="copy"),
    "dcp": ubx.FieldSpec(wire_name="dcp"),
    "dd": ubx.FieldSpec(wire_name="dd"),
    "dk": ubx.FieldSpec(wire_name="dk"),
    "download": ubx.FieldSpec(wire_name="download"),
    "dp": ubx.FieldSpec(wire_name="dp"),
    "du": ubx.FieldSpec(wire_name="du"),
    "keyboard": ubx.FieldSpec(wire_name="keyboard"),
    "paste": ubx.FieldSpec(wire_name="paste"),
    "printing": ubx.FieldSpec(wire_name="printing"),
    "upload": ubx.FieldSpec(wire_name="upload"),
    "version": ubx.FieldSpec(wire_name="version"),
    "wm_id": ubx.FieldSpec(wire_name="wm_id"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_BlockPageFields = {
    "include_context": ubx.FieldSpec(wire_name="include_context"),
    "target_uri": ubx.FieldSpec(wire_name="target_uri"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_CheckSessionFields = {
    "duration": ubx.FieldSpec(wire_name="duration"),
    "enforce": ubx.FieldSpec(wire_name="enforce"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolvers_Ipv4Fields = {
    "ip": ubx.FieldSpec(wire_name="ip"),
    "port": ubx.FieldSpec(wire_name="port"),
    "route_through_private_network": ubx.FieldSpec(wire_name="route_through_private_network"),
    "vnet_id": ubx.FieldSpec(wire_name="vnet_id"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolversFields = {
    "ipv4": ubx.FieldSpec(
        wire_name="ipv4",
        kind="list",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolvers_Ipv4Fields,
    ),
    "ipv6": ubx.FieldSpec(
        wire_name="ipv6",
        kind="list",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolvers_Ipv4Fields,
    ),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_EgressFields = {
    "ipv4": ubx.FieldSpec(wire_name="ipv4"),
    "ipv4_fallback": ubx.FieldSpec(wire_name="ipv4_fallback"),
    "ipv6": ubx.FieldSpec(wire_name="ipv6"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ForensicCopyFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_L4overrideFields = {
    "ip": ubx.FieldSpec(wire_name="ip"),
    "port": ubx.FieldSpec(wire_name="port"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_NotificationSettingsFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "include_context": ubx.FieldSpec(wire_name="include_context"),
    "msg": ubx.FieldSpec(wire_name="msg"),
    "support_url": ubx.FieldSpec(wire_name="support_url"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_QuarantineFields = {
    "file_types": ubx.FieldSpec(wire_name="file_types"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_RedirectFields = {
    "include_context": ubx.FieldSpec(wire_name="include_context"),
    "preserve_path_and_query": ubx.FieldSpec(wire_name="preserve_path_and_query"),
    "target_uri": ubx.FieldSpec(wire_name="target_uri"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ResolveDnsInternallyFields = {
    "fallback": ubx.FieldSpec(wire_name="fallback"),
    "view_id": ubx.FieldSpec(wire_name="view_id"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_UntrustedCertFields = {
    "action": ubx.FieldSpec(wire_name="action"),
}

_ZeroTrustGatewaySingleResponse4_Result_RuleSettingsFields = {
    "add_headers": ubx.FieldSpec(wire_name="add_headers"),
    "allow_child_bypass": ubx.FieldSpec(wire_name="allow_child_bypass"),
    "audit_ssh": ubx.FieldSpec(
        wire_name="audit_ssh",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_AuditSshFields,
    ),
    "biso_admin_controls": ubx.FieldSpec(
        wire_name="biso_admin_controls",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_BisoAdminControlsFields,
    ),
    "block_page": ubx.FieldSpec(
        wire_name="block_page",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_BlockPageFields,
    ),
    "block_page_enabled": ubx.FieldSpec(wire_name="block_page_enabled"),
    "block_reason": ubx.FieldSpec(wire_name="block_reason"),
    "bypass_parent_rule": ubx.FieldSpec(wire_name="bypass_parent_rule"),
    "check_session": ubx.FieldSpec(
        wire_name="check_session",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_CheckSessionFields,
    ),
    "delete_headers": ubx.FieldSpec(wire_name="delete_headers"),
    "dns_resolvers": ubx.FieldSpec(
        wire_name="dns_resolvers",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_DnsResolversFields,
    ),
    "egress": ubx.FieldSpec(
        wire_name="egress",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_EgressFields,
    ),
    "forensic_copy": ubx.FieldSpec(
        wire_name="forensic_copy",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ForensicCopyFields,
    ),
    "ignore_cname_category_matches": ubx.FieldSpec(wire_name="ignore_cname_category_matches"),
    "insecure_disable_dnssec_validation": ubx.FieldSpec(wire_name="insecure_disable_dnssec_validation"),
    "ip_categories": ubx.FieldSpec(wire_name="ip_categories"),
    "ip_indicator_feeds": ubx.FieldSpec(wire_name="ip_indicator_feeds"),
    "l4override": ubx.FieldSpec(
        wire_name="l4override",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_L4overrideFields,
    ),
    "notification_settings": ubx.FieldSpec(
        wire_name="notification_settings",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_NotificationSettingsFields,
    ),
    "override_host": ubx.FieldSpec(wire_name="override_host"),
    "override_ips": ubx.FieldSpec(wire_name="override_ips"),
    "payload_log": ubx.FieldSpec(
        wire_name="payload_log",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ForensicCopyFields,
    ),
    "quarantine": ubx.FieldSpec(
        wire_name="quarantine",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_QuarantineFields,
    ),
    "redirect": ubx.FieldSpec(
        wire_name="redirect",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_RedirectFields,
    ),
    "resolve_dns_internally": ubx.FieldSpec(
        wire_name="resolve_dns_internally",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_ResolveDnsInternallyFields,
    ),
    "resolve_dns_through_cloudflare": ubx.FieldSpec(wire_name="resolve_dns_through_cloudflare"),
    "set_headers": ubx.FieldSpec(wire_name="set_headers"),
    "untrusted_cert": ubx.FieldSpec(
        wire_name="untrusted_cert",
        kind="object",
        fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettings_UntrustedCertFields,
    ),
}

_ZeroTrustGatewaySingleResponse4_Result_ScheduleFields = {
    "fri": ubx.FieldSpec(wire_name="fri"),
    "mon": ubx.FieldSpec(wire_name="mon"),
    "sat": ubx.FieldSpec(wire_name="sat"),
    "sun": ubx.FieldSpec(wire_name="sun"),
    "thu": ubx.FieldSpec(wire_name="thu"),
    "time_zone": ubx.FieldSpec(wire_name="time_zone"),
    "tue": ubx.FieldSpec(wire_name="tue"),
    "wed": ubx.FieldSpec(wire_name="wed"),
}

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4Config:
    # Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to `true`.
    action: Any = None
    # Specify the rule description.
    description: Any = None
    # Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    device_posture: Any = None
    # Specify whether the rule is enabled.
    enabled: Any = None
    # Defines the expiration time stamp and default duration of a DNS policy. Takes precedence over the policy's `schedule` configuration, if any. This does not apply to HTTP or network policies. Settable only for `dns` rules.
    expiration: Any = None
    # Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
    filters: Any = None
    # Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    identity: Any = None
    # Specify the rule name.
    name: Any = None
    # Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value. Refer to [Order of enforcement](http://developers.cloudflare.com/learning-paths/secure-internet-traffic/understand-policies/order-of-enforcement/#manage-precedence-with-terraform) to manage precedence via Terraform.
    precedence: Any = None
    # Defines settings for this rule. Settings apply only to specific rule types and must use compatible selectors. If Terraform detects drift, confirm the setting supports your rule type and check whether the API modifies the value. Use API-returned values in your configuration to prevent drift.
    rule_settings: Any = None
    # Defines the schedule for activating DNS policies. Settable only for `dns` and `dns_resolver` rules.
    schedule: Any = None
    # Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    traffic: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    rule_id: Any = None

@dataclasses.dataclass
class ZeroTrustGatewaySingleResponse4Attrs:
    # Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to `true`.
    action: Any = None
    # Specify the rule description.
    description: Any = None
    # Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    device_posture: Any = None
    # Specify whether the rule is enabled.
    enabled: Any = None
    # Defines the expiration time stamp and default duration of a DNS policy. Takes precedence over the policy's `schedule` configuration, if any. This does not apply to HTTP or network policies. Settable only for `dns` rules.
    expiration: Any = None
    # Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
    filters: Any = None
    # Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    identity: Any = None
    # Specify the rule name.
    name: Any = None
    # Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value. Refer to [Order of enforcement](http://developers.cloudflare.com/learning-paths/secure-internet-traffic/understand-policies/order-of-enforcement/#manage-precedence-with-terraform) to manage precedence via Terraform.
    precedence: Any = None
    result: Any = None
    # Defines settings for this rule. Settings apply only to specific rule types and must use compatible selectors. If Terraform detects drift, confirm the setting supports your rule type and check whether the API modifies the value. Use API-returned values in your configuration to prevent drift.
    rule_settings: Any = None
    # Defines the schedule for activating DNS policies. Settable only for `dns` and `dns_resolver` rules.
    schedule: Any = None
    # Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them. To prevent Terraform state drift, use the formatted expression returned in the API response.
    traffic: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    rule_id: Any = None

ZeroTrustGatewaySingleResponse4 = ubx.ResourceBinding(
    wire_type="cloudflare_zero_trust_gateway_single_response_4",
    fields={
        "action": ubx.FieldSpec(wire_name="action"),
        "description": ubx.FieldSpec(wire_name="description"),
        "device_posture": ubx.FieldSpec(wire_name="device_posture"),
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "expiration": ubx.FieldSpec(
            wire_name="expiration",
            kind="object",
            fields=_ZeroTrustGatewaySingleResponse4_ExpirationFields,
        ),
        "filters": ubx.FieldSpec(wire_name="filters"),
        "identity": ubx.FieldSpec(wire_name="identity"),
        "name": ubx.FieldSpec(wire_name="name"),
        "precedence": ubx.FieldSpec(wire_name="precedence"),
        "rule_settings": ubx.FieldSpec(
            wire_name="rule_settings",
            kind="object",
            fields=_ZeroTrustGatewaySingleResponse4_Result_RuleSettingsFields,
        ),
        "schedule": ubx.FieldSpec(
            wire_name="schedule",
            kind="object",
            fields=_ZeroTrustGatewaySingleResponse4_Result_ScheduleFields,
        ),
        "traffic": ubx.FieldSpec(wire_name="traffic"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "rule_id": ubx.FieldSpec(wire_name="rule_id"),
    },
)
