# Code generated by `ubx sdk gen` from cloudflare_organization. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Organization_Messages:
    code: Any = None
    message: Any = None

@dataclasses.dataclass
class Organization_Result_Id:
    pass

@dataclasses.dataclass
class Organization_Result_Meta_TenantFlags:
    account_creation: Any = None
    account_creation_applies_tenant_defaults: Any = None
    account_deletion: Any = None
    account_migration: Any = None
    account_mobility: Any = None
    enterprise_capability: Any = None
    member_management: Any = None
    sub_org_creation: Any = None

@dataclasses.dataclass
class Organization_Result_Meta:
    # Ordered chain of organization tags from the root organization down to (and including) this organization itself. Root organizations return a single-element array containing their own tag; sub-organizations return `[rootTag, ...intermediateTags, parentTag, selfTag]`. Useful for constructing authorization scopes that need to cover every ancestor in the hierarchy.
    hierarchy_tags: Any = None
    managed_by: Any = None
    tenant_flags: Any = None

@dataclasses.dataclass
class Organization_Result_Parent:
    id: Any = None
    name: Any = None

@dataclasses.dataclass
class Organization_Result_Profile:
    business_address: Any = None
    business_email: Any = None
    business_name: Any = None
    business_phone: Any = None
    external_metadata: Any = None

@dataclasses.dataclass
class Organization_Result:
    create_time: Any = None
    id: Any = None
    meta: Any = None
    name: Any = None
    parent: Any = None
    profile: Any = None

@dataclasses.dataclass
class OrganizationConfig:
    # Move these accounts to the destination organization.
    account_ids: Any = None
    # Move accounts to this organization ID.
    destination_organization_id: Any = None
    # path parameter, not part of the API's own resource representation
    organization_id: Any = None

@dataclasses.dataclass
class OrganizationAttrs:
    # Move these accounts to the destination organization.
    account_ids: Any = None
    # Move accounts to this organization ID.
    destination_organization_id: Any = None
    errors: Any = None
    messages: Any = None
    # References an Organization in the Cloudflare data model.
    result: Any = None
    success: Any = None
    # path parameter, not part of the API's own resource representation
    organization_id: Any = None

Organization = ubx.ResourceBinding(
    wire_type="cloudflare_organization",
    fields={
        "account_ids": ubx.FieldSpec(wire_name="account_ids"),
        "destination_organization_id": ubx.FieldSpec(wire_name="destination_organization_id"),
        "organization_id": ubx.FieldSpec(wire_name="organization_id"),
    },
)
