// Code generated by `ubx sdk gen` from cloudflare_firewall_filter_rules_single_response. DO NOT EDIT.
package firewallrules

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FirewallFilterRulesSingleResponse_Action_Response struct {
	Body        any
	ContentType any
}

type FirewallFilterRulesSingleResponse_Action struct {
	Mode     any
	Response any
	Timeout  any
}

type FirewallFilterRulesSingleResponse_Filter struct {
	// An informative summary of the filter.
	Description any
	// The filter expression. For more information, refer to [Expressions](https://developers.cloudflare.com/ruleset-engine/rules-language/expressions/).
	Expression any
	// The unique identifier of the filter.
	Id any
	// When true, indicates that the filter is currently paused.
	Paused any
	// A short reference tag. Allows you to select related filters.
	Ref any
}

type FirewallFilterRulesSingleResponse_Result_Filter struct {
	Deleted     any
	Description any
	Expression  any
	Id          any
	Paused      any
	Ref         any
}

type FirewallFilterRulesSingleResponse_Result struct {
	Action      any
	Description any
	Filter      any
	Id          any
	Paused      any
	Priority    any
	Products    any
	Ref         any
}

var FirewallFilterRulesSingleResponse_Action_ResponseFields = ubx.FieldMap{
	"Body":        ubx.FieldSpec{WireName: "body"},
	"ContentType": ubx.FieldSpec{WireName: "content_type"},
}

var FirewallFilterRulesSingleResponse_ActionFields = ubx.FieldMap{
	"Mode": ubx.FieldSpec{WireName: "mode"},
	"Response": ubx.FieldSpec{
		WireName: "response",
		Kind:     "object",
		Fields:   FirewallFilterRulesSingleResponse_Action_ResponseFields,
	},
	"Timeout": ubx.FieldSpec{WireName: "timeout"},
}

var FirewallFilterRulesSingleResponse_FilterFields = ubx.FieldMap{
	"Description": ubx.FieldSpec{WireName: "description"},
	"Expression":  ubx.FieldSpec{WireName: "expression"},
	"Id":          ubx.FieldSpec{WireName: "id"},
	"Paused":      ubx.FieldSpec{WireName: "paused"},
	"Ref":         ubx.FieldSpec{WireName: "ref"},
}

type FirewallFilterRulesSingleResponseConfig struct {
	// The action to perform when the threshold of matched traffic within the configured period is exceeded.
	Action any
	Filter any
	// path parameter, not part of the API's own resource representation
	ZoneId any
	// path parameter, not part of the API's own resource representation
	RuleId any
}

type FirewallFilterRulesSingleResponseAttrs struct {
	// The action to perform when the threshold of matched traffic within the configured period is exceeded.
	Action any
	Filter any
	// The unique identifier of the resource.
	Id     any
	Result any
	// path parameter, not part of the API's own resource representation
	ZoneId any
	// path parameter, not part of the API's own resource representation
	RuleId any
}

var FirewallFilterRulesSingleResponse = ubx.ResourceBinding{
	WireType: "cloudflare_firewall_filter_rules_single_response",
	Fields: ubx.FieldMap{
		"Action": ubx.FieldSpec{
			WireName: "action",
			Kind:     "object",
			Fields:   FirewallFilterRulesSingleResponse_ActionFields,
		},
		"Filter": ubx.FieldSpec{
			WireName: "filter",
			Kind:     "object",
			Fields:   FirewallFilterRulesSingleResponse_FilterFields,
		},
		"ZoneId": ubx.FieldSpec{WireName: "zone_id"},
		"RuleId": ubx.FieldSpec{WireName: "rule_id"},
	},
}
