// Code generated by `ubx sdk gen` from cloudflare_trigger. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Trigger_Errors {
  code?: number | Computed<number>;
  message?: string | Computed<string>;
}

export interface Trigger_Result_RepoConnection {
  createdOn?: string | Computed<string>;
  deletedOn?: string | Computed<string>;
  modifiedOn?: string | Computed<string>;
  providerAccountId?: string | Computed<string>;
  providerAccountName?: string | Computed<string>;
  providerType?: string | Computed<string>;
  repoConnectionUuid?: string | Computed<string>;
  repoId?: string | Computed<string>;
  repoName?: string | Computed<string>;
}

export interface Trigger_Result {
  branchExcludes?: string[] | Computed<string[]>;
  branchIncludes?: string[] | Computed<string[]>;
  buildCachingEnabled?: boolean | Computed<boolean>;
  buildCommand?: string | Computed<string>;
  buildTokenName?: string | Computed<string>;
  buildTokenUuid?: string | Computed<string>;
  createdOn?: string | Computed<string>;
  deletedOn?: string | Computed<string>;
  deployCommand?: string | Computed<string>;
  externalScriptId?: string | Computed<string>;
  modifiedOn?: string | Computed<string>;
  pathExcludes?: string[] | Computed<string[]>;
  pathIncludes?: string[] | Computed<string[]>;
  repoConnection?: Trigger_Result_RepoConnection | Computed<Trigger_Result_RepoConnection>;
  rootDirectory?: string | Computed<string>;
  triggerName?: string | Computed<string>;
  triggerUuid?: string | Computed<string>;
}

export interface Trigger_ResultInfo {
  count?: number | Computed<number>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  totalCount?: number | Computed<number>;
  totalPages?: number | Computed<number>;
}

export interface TriggerConfig {
  /** Account identifier. */
  accountId: string | Computed<string>;
  /** System-generated worker script tag. */
  externalScriptId: string | Computed<string>;
}

export interface TriggerAttrs {
  /** Account identifier. */
  accountId: string;
  errors: Trigger_Errors[];
  /** System-generated worker script tag. */
  externalScriptId: string;
  messages: string[];
  result: Trigger_Result[];
  resultInfo: Trigger_ResultInfo;
  success: boolean;
}

export const Trigger: DataSourceBinding<TriggerConfig, TriggerAttrs> = {
  wireType: "cloudflare_trigger",
  fields: {
    accountId: "account_id",
    externalScriptId: "external_script_id",
  },
};
