// Code generated by `ubx sdk gen` from cloudflare_magic_wan_single_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MagicWanSingleResponse_Result_StaticAddressing {
  /** A valid CIDR notation representing an IP range. */
  address: string | Computed<string>;
  /** A valid IPv4 address. */
  gatewayAddress: string | Computed<string>;
  /** A valid CIDR notation representing an IP range. */
  secondaryAddress?: string | Computed<string>;
}

export interface MagicWanSingleResponse_Result {
  /** Magic WAN health check rate for tunnels created on this link. The default value is `mid`. */
  healthCheckRate?: string | Computed<string>;
  /** Identifier */
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  physport?: number | Computed<number>;
  /** Priority of WAN for traffic loadbalancing. */
  priority?: number | Computed<number>;
  /** Identifier */
  siteId?: string | Computed<string>;
  /** (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode. */
  staticAddressing?: MagicWanSingleResponse_Result_StaticAddressing | Computed<MagicWanSingleResponse_Result_StaticAddressing>;
  /** VLAN ID. Use zero for untagged. */
  vlanTag?: number | Computed<number>;
}

const MagicWanSingleResponse_Result_StaticAddressingFields: FieldMap = {
  address: "address",
  gatewayAddress: "gateway_address",
  secondaryAddress: "secondary_address",
};

export interface MagicWanSingleResponseConfig {
  /** The name of the WAN interface. (AI-inferred) */
  name?: string | Computed<string>;
  /** The physical port this WAN interface is attached to. (AI-inferred) */
  physport: number | Computed<number>;
  /** The priority of this WAN interface relative to other WAN interfaces on the site. (AI-inferred) */
  priority?: number | Computed<number>;
  /** (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode. */
  staticAddressing?: MagicWanSingleResponse_Result_StaticAddressing | Computed<MagicWanSingleResponse_Result_StaticAddressing>;
  /** VLAN ID. Use zero for untagged. */
  vlanTag?: number | Computed<number>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  siteId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  wanId: string | Computed<string>;
}

export interface MagicWanSingleResponseAttrs {
  /** The name of the WAN interface. (AI-inferred) */
  name: string;
  /** The physical port this WAN interface is attached to. (AI-inferred) */
  physport: number;
  /** The priority of this WAN interface relative to other WAN interfaces on the site. (AI-inferred) */
  priority: number;
  /** The requested resource, present when the API call succeeds. (AI-inferred) */
  result: MagicWanSingleResponse_Result;
  /** (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode. */
  staticAddressing: MagicWanSingleResponse_Result_StaticAddressing;
  /** VLAN ID. Use zero for untagged. */
  vlanTag: number;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  siteId: string;
  /** path parameter, not part of the API's own resource representation */
  wanId: string;
}

export const MagicWanSingleResponse: ResourceBinding<MagicWanSingleResponseConfig, MagicWanSingleResponseAttrs> = {
  wireType: "cloudflare_magic_wan_single_response",
  fields: {
    name: "name",
    physport: "physport",
    priority: "priority",
    staticAddressing: {
      wireName: "static_addressing",
      kind: "object",
      fields: MagicWanSingleResponse_Result_StaticAddressingFields,
    },
    vlanTag: "vlan_tag",
    accountId: "account_id",
    siteId: "site_id",
    wanId: "wan_id",
  },
};
