# Code generated by `ubx sdk gen` from cloudflare_transformation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Transformation_Errors:
    code: Any = None
    message: Any = None

@dataclasses.dataclass
class Transformation_Result:
    cf_zone_tag: Any = None
    editable: Any = None
    id: Any = None
    modified_on: Any = None
    value: Any = None

@dataclasses.dataclass
class TransformationConfig:
    # Identifier.
    account_id: Any = None

@dataclasses.dataclass
class TransformationAttrs:
    # Identifier.
    account_id: Any = None
    errors: Any = None
    messages: Any = None
    result: Any = None
    # Whether the API call was successful.
    success: Any = None

Transformation = ubx.DataSourceBinding(
    wire_type="cloudflare_transformation",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
