// Code generated by `ubx sdk gen` from cloudflare_aggregate. DO NOT EDIT.
package event

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Aggregate_Aggregations struct {
	Count any
	Date any
}

type Aggregate_DateRange struct {
	EndDate any
	StartDate any
}

type AggregateConfig struct {
	// Account ID.
	AccountId any
	// Column(s) to aggregate by - single column or comma-separated list (e.g., 'attacker', 'targetIndustry', 'attacker,targetIndustry')
	AggregateBy any
	// Dataset ID(s) to filter by. Can be a single dataset ID, comma-separated list, or array. If not provided, uses default dataset
	DatasetId any
	// End date for filtering (ISO 8601 format, e.g., '2024-12-31')
	EndDate any
	// Whether to group results by date (daily aggregation)
	GroupByDate any
	// Maximum number of results to return
	Limit any
	// Start date for filtering (ISO 8601 format, e.g., '2024-01-01')
	StartDate any
}

type AggregateAttrs struct {
	// Account ID.
	AccountId any
	// Column(s) to aggregate by - single column or comma-separated list (e.g., 'attacker', 'targetIndustry', 'attacker,targetIndustry')
	AggregateBy any
	// Array of aggregation results with dynamic fields based on aggregateBy columns
	Aggregations any
	// Dataset ID(s) to filter by. Can be a single dataset ID, comma-separated list, or array. If not provided, uses default dataset
	DatasetId any
	// Date range used for filtering
	DateRange any
	// End date for filtering (ISO 8601 format, e.g., '2024-12-31')
	EndDate any
	// Whether to group results by date (daily aggregation)
	GroupByDate any
	// Maximum number of results to return
	Limit any
	// Start date for filtering (ISO 8601 format, e.g., '2024-01-01')
	StartDate any
	// Total number of events in the aggregation
	Total any
}

var Aggregate = ubx.DataSourceBinding{
	WireType: "cloudflare_aggregate",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"AggregateBy": ubx.FieldSpec{WireName: "aggregate_by"},
		"DatasetId": ubx.FieldSpec{WireName: "dataset_id"},
		"EndDate": ubx.FieldSpec{WireName: "end_date"},
		"GroupByDate": ubx.FieldSpec{WireName: "group_by_date"},
		"Limit": ubx.FieldSpec{WireName: "limit"},
		"StartDate": ubx.FieldSpec{WireName: "start_date"},
	},
}
