// Code generated by `ubx sdk gen` from cloudflare_ip_profile. DO NOT EDIT.
package ipprofiles

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IpProfile_Errors struct {
	Code    any
	Message any
}

type IpProfile_Result struct {
	// The RFC3339Nano timestamp when the Device IP profile was created.
	CreatedAt any
	// An optional description of the Device IP profile.
	Description any
	// Whether the Device IP profile is enabled.
	Enabled any
	// The ID of the Device IP profile.
	Id any
	// The wirefilter expression to match registrations. Available values: "identity.name", "identity.email", "identity.groups.id", "identity.groups.name", "identity.groups.email", "identity.saml_attributes".
	Match any
	// A user-friendly name for the Device IP profile.
	Name any
	// The precedence of the Device IP profile. Lower values indicate higher precedence. Device IP profile will be evaluated in ascending order of this field.
	Precedence any
	// The ID of the Subnet.
	SubnetId any
	// The RFC3339Nano timestamp when the Device IP profile was last updated.
	UpdatedAt any
}

type IpProfileConfig struct {
	// An optional description of the Device IP profile.
	Description any
	// Whether the Device IP profile will be applied to matching devices.
	Enabled any
	// The wirefilter expression to match registrations. Available values: "identity.name", "identity.email", "identity.groups.id", "identity.groups.name", "identity.groups.email", "identity.saml_attributes".
	Match any
	// A user-friendly name for the Device IP profile.
	Name any
	// The precedence of the Device IP profile. Lower values indicate higher precedence. Device IP profile will be evaluated in ascending order of this field.
	Precedence any
	// The ID of the Subnet.
	SubnetId any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	ProfileId any
}

type IpProfileAttrs struct {
	// An optional description of the Device IP profile.
	Description any
	// Whether the Device IP profile will be applied to matching devices.
	Enabled any
	// A list of errors returned by the API. Empty on a successful response. (AI-inferred)
	Errors any
	// The wirefilter expression to match registrations. Available values: "identity.name", "identity.email", "identity.groups.id", "identity.groups.name", "identity.groups.email", "identity.saml_attributes".
	Match any
	// A list of informational messages returned by the API, if any. (AI-inferred)
	Messages any
	// A user-friendly name for the Device IP profile.
	Name any
	// The precedence of the Device IP profile. Lower values indicate higher precedence. Device IP profile will be evaluated in ascending order of this field.
	Precedence any
	Result     any
	// The ID of the Subnet.
	SubnetId any
	// Whether the API call was successful.
	Success any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	ProfileId any
}

var IpProfile = ubx.ResourceBinding{
	WireType: "cloudflare_ip_profile",
	Fields: ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"Enabled":     ubx.FieldSpec{WireName: "enabled"},
		"Match":       ubx.FieldSpec{WireName: "match"},
		"Name":        ubx.FieldSpec{WireName: "name"},
		"Precedence":  ubx.FieldSpec{WireName: "precedence"},
		"SubnetId":    ubx.FieldSpec{WireName: "subnet_id"},
		"AccountId":   ubx.FieldSpec{WireName: "account_id"},
		"ProfileId":   ubx.FieldSpec{WireName: "profile_id"},
	},
}
