// Code generated by `ubx sdk gen` from cloudflare_resource_tagging_tag_key_summary_response_collection. DO NOT EDIT.
package resourcetagging

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TagKeySummaryResponseCollection_AccountId struct {
}

var TagKeySummaryResponseCollection_AccountIdFields = ubx.FieldMap{
	}

type TagKeySummaryResponseCollectionConfig struct {
	AccountId any
	Cursor any
}

type TagKeySummaryResponseCollectionAttrs struct {
	AccountId any
	Cursor any
}

var TagKeySummaryResponseCollection = ubx.DataSourceBinding{
	WireType: "cloudflare_resource_tagging_tag_key_summary_response_collection",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{
			WireName: "account_id",
			Kind: "object",
			Fields: TagKeySummaryResponseCollection_AccountIdFields,
		},
		"Cursor": ubx.FieldSpec{WireName: "cursor"},
	},
}
