// Code generated by `ubx sdk gen` from cloudflare_resource_tagging_tagged_resource_response_single. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TaggedResourceResponseSingle_AccountId {
}

export interface TaggedResourceResponseSingle_Errors_Source {
  pointer?: string | Computed<string>;
}

export interface TaggedResourceResponseSingle_Errors {
  code?: number | Computed<number>;
  documentationUrl?: string | Computed<string>;
  message?: string | Computed<string>;
  source?: TaggedResourceResponseSingle_Errors_Source | Computed<TaggedResourceResponseSingle_Errors_Source>;
}

const TaggedResourceResponseSingle_AccountIdFields: FieldMap = {
};

export interface TaggedResourceResponseSingleConfig {
  accountId: TaggedResourceResponseSingle_AccountId | Computed<TaggedResourceResponseSingle_AccountId>;
  /** Identifies the unique resource. */
  resourceId: string | Computed<string>;
  /** Identifies the type of account-level resource. */
  resourceType: string | Computed<string>;
  /** Worker ID is required only for worker_version resources */
  workerId?: string | Computed<string>;
}

export interface TaggedResourceResponseSingleAttrs {
  accountId: TaggedResourceResponseSingle_AccountId;
  errors: TaggedResourceResponseSingle_Errors[];
  messages: TaggedResourceResponseSingle_Errors[];
  /** Identifies the unique resource. */
  resourceId: string;
  /** Identifies the type of account-level resource. */
  resourceType: string;
  result: unknown;
  /** Whether the API call was successful. */
  success: boolean;
  /** Worker ID is required only for worker_version resources */
  workerId: string;
}

export const TaggedResourceResponseSingle: DataSourceBinding<TaggedResourceResponseSingleConfig, TaggedResourceResponseSingleAttrs> = {
  wireType: "cloudflare_resource_tagging_tagged_resource_response_single",
  fields: {
    accountId: {
      wireName: "account_id",
      kind: "object",
      fields: TaggedResourceResponseSingle_AccountIdFields,
    },
    resourceId: "resource_id",
    resourceType: "resource_type",
    workerId: "worker_id",
  },
};
