// Code generated by `ubx sdk gen` from cloudflare_workers_namespace_list_response. DO NOT EDIT.
package workersforplatforms

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type WorkersNamespaceListResponse_Errors_Source struct {
	Pointer any
}

type WorkersNamespaceListResponse_Errors struct {
	Code             any
	DocumentationUrl any
	Message          any
	Source           any
}

type WorkersNamespaceListResponse_Result struct {
	CreatedBy      any
	CreatedOn      any
	ModifiedBy     any
	ModifiedOn     any
	NamespaceId    any
	NamespaceName  any
	ScriptCount    any
	TrustedWorkers any
}

type WorkersNamespaceListResponseConfig struct {
	// Identifier.
	AccountId any
}

type WorkersNamespaceListResponseAttrs struct {
	// Identifier.
	AccountId any
	Errors    any
	Messages  any
	Result    any
	// Whether the API call was successful.
	Success any
}

var WorkersNamespaceListResponse = ubx.DataSourceBinding{
	WireType: "cloudflare_workers_namespace_list_response",
	Fields: ubx.FieldMap{
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
	},
}
