// Code generated by `ubx sdk gen` from cloudflare_registrar_api_domain_response_single. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegistrarApiDomainResponseSingleConfig {
  /** Auto-renew controls whether subscription is automatically renewed upon domain expiration. */
  autoRenew?: boolean | Computed<boolean>;
  /** Shows whether a registrar lock is in place for a domain. */
  locked?: boolean | Computed<boolean>;
  /** Privacy option controls redacting WHOIS information. */
  privacy?: boolean | Computed<boolean>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  domainName: string | Computed<string>;
}

export interface RegistrarApiDomainResponseSingleAttrs {
  /** Auto-renew controls whether subscription is automatically renewed upon domain expiration. */
  autoRenew: boolean;
  /** Shows whether a registrar lock is in place for a domain. */
  locked: boolean;
  /** Privacy option controls redacting WHOIS information. */
  privacy: boolean;
  /** The requested resource, present when the API call succeeds. (AI-inferred) */
  result: unknown;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  domainName: string;
}

export const RegistrarApiDomainResponseSingle: ResourceBinding<RegistrarApiDomainResponseSingleConfig, RegistrarApiDomainResponseSingleAttrs> = {
  wireType: "cloudflare_registrar_api_domain_response_single",
  fields: {
    autoRenew: "auto_renew",
    locked: "locked",
    privacy: "privacy",
    accountId: "account_id",
    domainName: "domain_name",
  },
};
