// Code generated by `ubx sdk gen` from cloudflare_mconn_customer_connectors_get_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MconnCustomerConnectorsGetResponse_Device {
  id?: string | Computed<string>;
  /** When true, create and provision a new licence key for the connector. */
  provisionLicense?: boolean | Computed<boolean>;
  serialNumber?: string | Computed<string>;
}

export interface MconnCustomerConnectorsGetResponse_Result_Device {
  id: string | Computed<string>;
  serialNumber?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface MconnCustomerConnectorsGetResponse_Result {
  activated: boolean | Computed<boolean>;
  device?: MconnCustomerConnectorsGetResponse_Result_Device | Computed<MconnCustomerConnectorsGetResponse_Result_Device>;
  id: string | Computed<string>;
  /** Allowed days of the week for upgrades. Default is all days. */
  interruptWindowDaysOfWeek: string[] | Computed<string[]>;
  interruptWindowDurationHours: number | Computed<number>;
  /** List of dates (YYYY-MM-DD) when upgrades are blocked. */
  interruptWindowEmbargoDates: string[] | Computed<string[]>;
  interruptWindowHourOfDay: number | Computed<number>;
  lastHeartbeat?: string | Computed<string>;
  lastSeenVersion?: string | Computed<string>;
  lastUpdated: string | Computed<string>;
  licenseKey?: string | Computed<string>;
  notes: string | Computed<string>;
  primary: boolean | Computed<boolean>;
  siteId?: string | Computed<string>;
  timezone: string | Computed<string>;
}

const MconnCustomerConnectorsGetResponse_DeviceFields: FieldMap = {
  id: "id",
  provisionLicense: "provision_license",
  serialNumber: "serial_number",
};

export interface MconnCustomerConnectorsGetResponseConfig {
  activated?: boolean | Computed<boolean>;
  /** Exactly one of id, serial_number, or provision_license must be provided. */
  device: MconnCustomerConnectorsGetResponse_Device | Computed<MconnCustomerConnectorsGetResponse_Device>;
  /** Allowed days of the week for upgrades. Default is all days. */
  interruptWindowDaysOfWeek?: string[] | Computed<string[]>;
  interruptWindowDurationHours?: number | Computed<number>;
  /** List of dates (YYYY-MM-DD) when upgrades are blocked. */
  interruptWindowEmbargoDates?: string[] | Computed<string[]>;
  interruptWindowHourOfDay?: number | Computed<number>;
  notes?: string | Computed<string>;
  primary?: boolean | Computed<boolean>;
  siteId?: string | Computed<string>;
  timezone?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  connectorId: string | Computed<string>;
}

export interface MconnCustomerConnectorsGetResponseAttrs {
  activated: boolean;
  /** Exactly one of id, serial_number, or provision_license must be provided. */
  device: MconnCustomerConnectorsGetResponse_Device;
  /** Allowed days of the week for upgrades. Default is all days. */
  interruptWindowDaysOfWeek: string[];
  interruptWindowDurationHours: number;
  /** List of dates (YYYY-MM-DD) when upgrades are blocked. */
  interruptWindowEmbargoDates: string[];
  interruptWindowHourOfDay: number;
  notes: string;
  primary: boolean;
  result: MconnCustomerConnectorsGetResponse_Result;
  siteId: string;
  timezone: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  connectorId: string;
}

export const MconnCustomerConnectorsGetResponse: ResourceBinding<MconnCustomerConnectorsGetResponseConfig, MconnCustomerConnectorsGetResponseAttrs> = {
  wireType: "cloudflare_mconn_customer_connectors_get_response",
  fields: {
    activated: "activated",
    device: {
      wireName: "device",
      kind: "object",
      fields: MconnCustomerConnectorsGetResponse_DeviceFields,
    },
    interruptWindowDaysOfWeek: "interrupt_window_days_of_week",
    interruptWindowDurationHours: "interrupt_window_duration_hours",
    interruptWindowEmbargoDates: "interrupt_window_embargo_dates",
    interruptWindowHourOfDay: "interrupt_window_hour_of_day",
    notes: "notes",
    primary: "primary",
    siteId: "site_id",
    timezone: "timezone",
    accountId: "account_id",
    connectorId: "connector_id",
  },
};
