// Code generated by `ubx sdk gen` from cloudflare_dns_firewall_dns_firewall_response_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DnsFirewallResponseCollectionConfig {
  /** Identifier. */
  accountId: string | Computed<string>;
  /** Page number of paginated results */
  page?: number | Computed<number>;
  /** Number of clusters per page */
  perPage?: number | Computed<number>;
}

export interface DnsFirewallResponseCollectionAttrs {
  /** Identifier. */
  accountId: string;
  /** Page number of paginated results */
  page: number;
  /** Number of clusters per page */
  perPage: number;
}

export const DnsFirewallResponseCollection: DataSourceBinding<DnsFirewallResponseCollectionConfig, DnsFirewallResponseCollectionAttrs> = {
  wireType: "cloudflare_dns_firewall_dns_firewall_response_collection",
  fields: {
    accountId: "account_id",
    page: "page",
    perPage: "per_page",
  },
};
