# Code generated by `ubx sdk gen` from cloudflare_configuration. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConfigurationConfig:
    # Account ID.
    account_id: Any = None
    # Name of the bucket.
    bucket_name: Any = None

@dataclasses.dataclass
class ConfigurationAttrs:
    # Account ID.
    account_id: Any = None
    # Name of the bucket.
    bucket_name: Any = None

Configuration = ubx.DataSourceBinding(
    wire_type="cloudflare_configuration",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "bucket_name": ubx.FieldSpec(wire_name="bucket_name"),
    },
)
