// Code generated by `ubx sdk gen` from cloudflare_magic_tunnel_single_response. DO NOT EDIT.
package magicgretunnels

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MagicTunnelSingleResponse_Bgp struct {
	// ASN used on the customer end of the BGP session
	CustomerAsn any
	// ID of the BGP filter profile applied to routes advertised to the customer.
	ExportFilterId any
	// Prefixes in this list will be advertised to the customer device, in addition to the routes in the Magic routing table.
	ExtraPrefixes any
	// ID of the BGP filter profile applied to routes received from the customer.
	ImportFilterId any
	// MD5 key to use for session authentication. Note that *this is not a security measure*. MD5 is not a valid security mechanism, and the key is not treated as a secret value. This is *only* supported for preventing misconfiguration, not for defending against malicious attacks. The MD5 key, if set, must be of non-zero length and consist only of the following types of character: * ASCII alphanumerics: `[a-zA-Z0-9]` * Special characters in the set `'!@#$%^&*()+[]{}<>/.,;:_-~`= \|` In other words, MD5 keys may contain any printable ASCII character aside from newline (0x0A), quotation mark (`"`), vertical tab (0x0B), carriage return (0x0D), tab (0x09), form feed (0x0C), and the question mark (`?`). Requests specifying an MD5 key with one or more of these disallowed characters will be rejected.
	Md5Key any
}

type MagicTunnelSingleResponse_HealthCheck struct {
	Direction any
	Enabled   any
	Rate      any
	Target    any
	Type      any
}

type MagicTunnelSingleResponse_Result_GreTunnel_BgpStatus struct {
	BgpState            any
	CfSpeakerIp         any
	CfSpeakerPort       any
	CustomerSpeakerIp   any
	CustomerSpeakerPort any
	State               any
	TcpEstablished      any
	UpdatedAt           any
}

type MagicTunnelSingleResponse_Result_GreTunnel struct {
	// True if automatic stateful return routing should be enabled for a tunnel, false otherwise. Requires the `coupler_integration` account flag to be enabled; requests setting this to `true` without that flag will be rejected.
	AutomaticReturnRouting any
	Bgp                    any
	BgpStatus              any
	// The IP address assigned to the Cloudflare side of the GRE tunnel.
	CloudflareGreEndpoint any
	// The date and time the tunnel was created.
	CreatedOn any
	// The IP address assigned to the customer side of the GRE tunnel.
	CustomerGreEndpoint any
	// An optional description of the GRE tunnel.
	Description any
	HealthCheck any
	// Identifier
	Id any
	// A 31-bit prefix (/31 in CIDR notation) supporting two hosts, one for each side of the tunnel. Select the subnet from the following private IP space: 10.0.0.0–10.255.255.255, 172.16.0.0–172.31.255.255, 192.168.0.0–192.168.255.255.
	InterfaceAddress any
	// A 127 bit IPV6 prefix from within the virtual_subnet6 prefix space with the address being the first IP of the subnet and not same as the address of virtual_subnet6. Eg if virtual_subnet6 is 2606:54c1:7:0:a9fe:12d2::/127 , interface_address6 could be 2606:54c1:7:0:a9fe:12d2:1:200/127
	InterfaceAddress6 any
	// The date and time the tunnel was last modified.
	ModifiedOn any
	// Maximum Transmission Unit (MTU) in bytes for the GRE tunnel. The minimum value is 576.
	Mtu any
	// The name of the tunnel. The name cannot contain spaces or special characters, must be 15 characters or less, and cannot share a name with another GRE tunnel.
	Name any
	// Time To Live (TTL) in number of hops of the GRE tunnel.
	Ttl any
}

type MagicTunnelSingleResponse_Result struct {
	GreTunnel any
}

var MagicTunnelSingleResponse_BgpFields = ubx.FieldMap{
	"CustomerAsn":    ubx.FieldSpec{WireName: "customer_asn"},
	"ExportFilterId": ubx.FieldSpec{WireName: "export_filter_id"},
	"ExtraPrefixes":  ubx.FieldSpec{WireName: "extra_prefixes"},
	"ImportFilterId": ubx.FieldSpec{WireName: "import_filter_id"},
	"Md5Key":         ubx.FieldSpec{WireName: "md5_key"},
}

var MagicTunnelSingleResponse_HealthCheckFields = ubx.FieldMap{
	"Direction": ubx.FieldSpec{WireName: "direction"},
	"Enabled":   ubx.FieldSpec{WireName: "enabled"},
	"Rate":      ubx.FieldSpec{WireName: "rate"},
	"Target":    ubx.FieldSpec{WireName: "target"},
	"Type":      ubx.FieldSpec{WireName: "type"},
}

type MagicTunnelSingleResponseConfig struct {
	// True if automatic stateful return routing should be enabled for a tunnel, false otherwise. Requires the `coupler_integration` account flag to be enabled; requests setting this to `true` without that flag will be rejected.
	AutomaticReturnRouting any
	Bgp                    any
	// The IP address assigned to the Cloudflare side of the GRE tunnel.
	CloudflareGreEndpoint any
	// The IP address assigned to the customer side of the GRE tunnel.
	CustomerGreEndpoint any
	// An optional description of the GRE tunnel.
	Description any
	HealthCheck any
	// A 31-bit prefix (/31 in CIDR notation) supporting two hosts, one for each side of the tunnel. Select the subnet from the following private IP space: 10.0.0.0–10.255.255.255, 172.16.0.0–172.31.255.255, 192.168.0.0–192.168.255.255.
	InterfaceAddress any
	// A 127 bit IPV6 prefix from within the virtual_subnet6 prefix space with the address being the first IP of the subnet and not same as the address of virtual_subnet6. Eg if virtual_subnet6 is 2606:54c1:7:0:a9fe:12d2::/127 , interface_address6 could be 2606:54c1:7:0:a9fe:12d2:1:200/127
	InterfaceAddress6 any
	// Maximum Transmission Unit (MTU) in bytes for the GRE tunnel. The minimum value is 576.
	Mtu any
	// The name of the tunnel. The name cannot contain spaces or special characters, must be 15 characters or less, and cannot share a name with another GRE tunnel.
	Name any
	// Time To Live (TTL) in number of hops of the GRE tunnel.
	Ttl any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	GreTunnelId any
}

type MagicTunnelSingleResponseAttrs struct {
	// True if automatic stateful return routing should be enabled for a tunnel, false otherwise. Requires the `coupler_integration` account flag to be enabled; requests setting this to `true` without that flag will be rejected.
	AutomaticReturnRouting any
	Bgp                    any
	// The IP address assigned to the Cloudflare side of the GRE tunnel.
	CloudflareGreEndpoint any
	// The IP address assigned to the customer side of the GRE tunnel.
	CustomerGreEndpoint any
	// An optional description of the GRE tunnel.
	Description any
	HealthCheck any
	// A 31-bit prefix (/31 in CIDR notation) supporting two hosts, one for each side of the tunnel. Select the subnet from the following private IP space: 10.0.0.0–10.255.255.255, 172.16.0.0–172.31.255.255, 192.168.0.0–192.168.255.255.
	InterfaceAddress any
	// A 127 bit IPV6 prefix from within the virtual_subnet6 prefix space with the address being the first IP of the subnet and not same as the address of virtual_subnet6. Eg if virtual_subnet6 is 2606:54c1:7:0:a9fe:12d2::/127 , interface_address6 could be 2606:54c1:7:0:a9fe:12d2:1:200/127
	InterfaceAddress6 any
	// Maximum Transmission Unit (MTU) in bytes for the GRE tunnel. The minimum value is 576.
	Mtu any
	// The name of the tunnel. The name cannot contain spaces or special characters, must be 15 characters or less, and cannot share a name with another GRE tunnel.
	Name   any
	Result any
	// Time To Live (TTL) in number of hops of the GRE tunnel.
	Ttl any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	GreTunnelId any
}

var MagicTunnelSingleResponse = ubx.ResourceBinding{
	WireType: "cloudflare_magic_tunnel_single_response",
	Fields: ubx.FieldMap{
		"AutomaticReturnRouting": ubx.FieldSpec{WireName: "automatic_return_routing"},
		"Bgp": ubx.FieldSpec{
			WireName: "bgp",
			Kind:     "object",
			Fields:   MagicTunnelSingleResponse_BgpFields,
		},
		"CloudflareGreEndpoint": ubx.FieldSpec{WireName: "cloudflare_gre_endpoint"},
		"CustomerGreEndpoint":   ubx.FieldSpec{WireName: "customer_gre_endpoint"},
		"Description":           ubx.FieldSpec{WireName: "description"},
		"HealthCheck": ubx.FieldSpec{
			WireName: "health_check",
			Kind:     "object",
			Fields:   MagicTunnelSingleResponse_HealthCheckFields,
		},
		"InterfaceAddress":  ubx.FieldSpec{WireName: "interface_address"},
		"InterfaceAddress6": ubx.FieldSpec{WireName: "interface_address6"},
		"Mtu":               ubx.FieldSpec{WireName: "mtu"},
		"Name":              ubx.FieldSpec{WireName: "name"},
		"Ttl":               ubx.FieldSpec{WireName: "ttl"},
		"AccountId":         ubx.FieldSpec{WireName: "account_id"},
		"GreTunnelId":       ubx.FieldSpec{WireName: "gre_tunnel_id"},
	},
}
