// Code generated by `ubx sdk gen` from cloudflare_dns_firewall_dns_firewall_single_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DnsFirewallSingleResponse_AttackMitigation {
  /** When enabled, automatically mitigate random-prefix attacks to protect upstream DNS servers */
  enabled?: boolean | Computed<boolean>;
  /** Only mitigate attacks when upstream servers seem unhealthy */
  onlyWhenUpstreamUnhealthy?: boolean | Computed<boolean>;
}

export interface DnsFirewallSingleResponse_Result {
  attackMitigation?: DnsFirewallSingleResponse_AttackMitigation | Computed<DnsFirewallSingleResponse_AttackMitigation>;
  deprecateAnyRequests?: boolean | Computed<boolean>;
  dnsFirewallIps?: string[] | Computed<string[]>;
  ecsFallback?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  maximumCacheTtl?: number | Computed<number>;
  minimumCacheTtl?: number | Computed<number>;
  modifiedOn?: string | Computed<string>;
  name?: string | Computed<string>;
  negativeCacheTtl?: number | Computed<number>;
  ratelimit?: number | Computed<number>;
  retries?: number | Computed<number>;
  upstreamIps?: string[] | Computed<string[]>;
}

const DnsFirewallSingleResponse_AttackMitigationFields: FieldMap = {
  enabled: "enabled",
  onlyWhenUpstreamUnhealthy: "only_when_upstream_unhealthy",
};

export interface DnsFirewallSingleResponseConfig {
  /** Attack mitigation settings */
  attackMitigation?: DnsFirewallSingleResponse_AttackMitigation | Computed<DnsFirewallSingleResponse_AttackMitigation>;
  /** Whether to refuse to answer queries for the ANY type */
  deprecateAnyRequests?: boolean | Computed<boolean>;
  /** Number of IPv4 addresses to assign to the DNS Firewall cluster. Only used during cluster creation and cannot be changed later. */
  dnsFirewallIpCount?: number | Computed<number>;
  /** Whether to forward client IP (resolver) subnet if no EDNS Client Subnet is sent */
  ecsFallback?: boolean | Computed<boolean>;
  /** By default, Cloudflare attempts to cache responses for as long as indicated by the TTL received from upstream nameservers. This setting sets an upper bound on this duration. For caching purposes, higher TTLs will be decreased to the maximum value defined by this setting. This setting does not affect the TTL value in the DNS response Cloudflare returns to clients. Cloudflare will always forward the TTL value received from upstream nameservers. */
  maximumCacheTtl?: number | Computed<number>;
  /** By default, Cloudflare attempts to cache responses for as long as indicated by the TTL received from upstream nameservers. This setting sets a lower bound on this duration. For caching purposes, lower TTLs will be increased to the minimum value defined by this setting. This setting does not affect the TTL value in the DNS response Cloudflare returns to clients. Cloudflare will always forward the TTL value received from upstream nameservers. Note that, even with this setting, there is no guarantee that a response will be cached for at least the specified duration. Cached responses may be removed earlier for capacity or other operational reasons. */
  minimumCacheTtl?: number | Computed<number>;
  /** DNS Firewall cluster name */
  name: string | Computed<string>;
  /** This setting controls how long DNS Firewall should cache negative responses (e.g., NXDOMAIN) from the upstream servers. This setting does not affect the TTL value in the DNS response Cloudflare returns to clients. Cloudflare will always forward the TTL value received from upstream nameservers. */
  negativeCacheTtl?: number | Computed<number>;
  /** Maximum number of DNS queries per second that will be forwarded to your upstream nameservers. The limit is enforced per server, where each server receives a fraction of the configured value. The actual aggregate rate for a data center may vary depending on how many servers are present. Responses served from cache do not count toward this limit. Set to null to disable rate limiting. */
  ratelimit?: number | Computed<number>;
  /** Number of retries for fetching DNS responses from upstream nameservers (not counting the initial attempt) */
  retries?: number | Computed<number>;
  upstreamIps: string[] | Computed<string[]>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  dnsFirewallId: string | Computed<string>;
}

export interface DnsFirewallSingleResponseAttrs {
  /** Attack mitigation settings */
  attackMitigation: DnsFirewallSingleResponse_AttackMitigation;
  /** Whether to refuse to answer queries for the ANY type */
  deprecateAnyRequests: boolean;
  /** Number of IPv4 addresses to assign to the DNS Firewall cluster. Only used during cluster creation and cannot be changed later. */
  dnsFirewallIpCount: number;
  /** Whether to forward client IP (resolver) subnet if no EDNS Client Subnet is sent */
  ecsFallback: boolean;
  /** By default, Cloudflare attempts to cache responses for as long as indicated by the TTL received from upstream nameservers. This setting sets an upper bound on this duration. For caching purposes, higher TTLs will be decreased to the maximum value defined by this setting. This setting does not affect the TTL value in the DNS response Cloudflare returns to clients. Cloudflare will always forward the TTL value received from upstream nameservers. */
  maximumCacheTtl: number;
  /** By default, Cloudflare attempts to cache responses for as long as indicated by the TTL received from upstream nameservers. This setting sets a lower bound on this duration. For caching purposes, lower TTLs will be increased to the minimum value defined by this setting. This setting does not affect the TTL value in the DNS response Cloudflare returns to clients. Cloudflare will always forward the TTL value received from upstream nameservers. Note that, even with this setting, there is no guarantee that a response will be cached for at least the specified duration. Cached responses may be removed earlier for capacity or other operational reasons. */
  minimumCacheTtl: number;
  /** DNS Firewall cluster name */
  name: string;
  /** This setting controls how long DNS Firewall should cache negative responses (e.g., NXDOMAIN) from the upstream servers. This setting does not affect the TTL value in the DNS response Cloudflare returns to clients. Cloudflare will always forward the TTL value received from upstream nameservers. */
  negativeCacheTtl: number;
  /** Maximum number of DNS queries per second that will be forwarded to your upstream nameservers. The limit is enforced per server, where each server receives a fraction of the configured value. The actual aggregate rate for a data center may vary depending on how many servers are present. Responses served from cache do not count toward this limit. Set to null to disable rate limiting. */
  ratelimit: number;
  result: DnsFirewallSingleResponse_Result;
  /** Number of retries for fetching DNS responses from upstream nameservers (not counting the initial attempt) */
  retries: number;
  upstreamIps: string[];
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  dnsFirewallId: string;
}

export const DnsFirewallSingleResponse: ResourceBinding<DnsFirewallSingleResponseConfig, DnsFirewallSingleResponseAttrs> = {
  wireType: "cloudflare_dns_firewall_dns_firewall_single_response",
  fields: {
    attackMitigation: {
      wireName: "attack_mitigation",
      kind: "object",
      fields: DnsFirewallSingleResponse_AttackMitigationFields,
    },
    deprecateAnyRequests: "deprecate_any_requests",
    dnsFirewallIpCount: "dns_firewall_ip_count",
    ecsFallback: "ecs_fallback",
    maximumCacheTtl: "maximum_cache_ttl",
    minimumCacheTtl: "minimum_cache_ttl",
    name: "name",
    negativeCacheTtl: "negative_cache_ttl",
    ratelimit: "ratelimit",
    retries: "retries",
    upstreamIps: "upstream_ips",
    accountId: "account_id",
    dnsFirewallId: "dns_firewall_id",
  },
};
