# Code generated by `ubx sdk gen` from cloudflare_magic_lan_single_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MagicLanSingleResponse_Nat:
    # A valid CIDR notation representing an IP range.
    static_prefix: Any = None

@dataclasses.dataclass
class MagicLanSingleResponse_Result_RoutedSubnets:
    nat: Any = None
    next_hop: Any = None
    prefix: Any = None

@dataclasses.dataclass
class MagicLanSingleResponse_Result_StaticAddressing_DhcpRelay:
    # List of DHCP server IPs.
    server_addresses: Any = None

@dataclasses.dataclass
class MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptions:
    code: Any = None
    type: Any = None
    value: Any = None

@dataclasses.dataclass
class MagicLanSingleResponse_Result_StaticAddressing_DhcpServer:
    # Optional list of custom DHCP options to include in DHCP responses. Only valid when DHCP server is enabled.
    dhcp_options: Any = None
    # A valid IPv4 address.
    dhcp_pool_end: Any = None
    # A valid IPv4 address.
    dhcp_pool_start: Any = None
    # A valid IPv4 address.
    dns_server: Any = None
    dns_servers: Any = None
    # Mapping of MAC addresses to IP addresses
    reservations: Any = None

@dataclasses.dataclass
class MagicLanSingleResponse_Result_StaticAddressing:
    # A valid CIDR notation representing an IP range.
    address: Any = None
    dhcp_relay: Any = None
    dhcp_server: Any = None
    # A valid CIDR notation representing an IP range.
    secondary_address: Any = None
    # A valid CIDR notation representing an IP range.
    virtual_address: Any = None

@dataclasses.dataclass
class MagicLanSingleResponse_Result:
    bond_id: Any = None
    # mark true to use this LAN for HA probing. only works for site with HA turned on. only one LAN can be set as the ha_link.
    ha_link: Any = None
    # Identifier
    id: Any = None
    # mark true to use this LAN for source-based breakout traffic
    is_breakout: Any = None
    # mark true to use this LAN for source-based prioritized traffic
    is_prioritized: Any = None
    name: Any = None
    nat: Any = None
    physport: Any = None
    routed_subnets: Any = None
    # Identifier
    site_id: Any = None
    # If the site is not configured in high availability mode, this configuration is optional (if omitted, use DHCP). However, if in high availability mode, static_address is required along with secondary and virtual address.
    static_addressing: Any = None
    # VLAN ID. Use zero for untagged.
    vlan_tag: Any = None

_MagicLanSingleResponse_NatFields = {
    "static_prefix": ubx.FieldSpec(wire_name="static_prefix"),
}

_MagicLanSingleResponse_Result_RoutedSubnetsFields = {
    "nat": ubx.FieldSpec(
        wire_name="nat",
        kind="object",
        fields=_MagicLanSingleResponse_NatFields,
    ),
    "next_hop": ubx.FieldSpec(wire_name="next_hop"),
    "prefix": ubx.FieldSpec(wire_name="prefix"),
}

_MagicLanSingleResponse_Result_StaticAddressing_DhcpRelayFields = {
    "server_addresses": ubx.FieldSpec(wire_name="server_addresses"),
}

_MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptionsFields = {
    "code": ubx.FieldSpec(wire_name="code"),
    "type": ubx.FieldSpec(wire_name="type"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_MagicLanSingleResponse_Result_StaticAddressing_DhcpServerFields = {
    "dhcp_options": ubx.FieldSpec(
        wire_name="dhcp_options",
        kind="list",
        fields=_MagicLanSingleResponse_Result_StaticAddressing_DhcpServer_DhcpOptionsFields,
    ),
    "dhcp_pool_end": ubx.FieldSpec(wire_name="dhcp_pool_end"),
    "dhcp_pool_start": ubx.FieldSpec(wire_name="dhcp_pool_start"),
    "dns_server": ubx.FieldSpec(wire_name="dns_server"),
    "dns_servers": ubx.FieldSpec(wire_name="dns_servers"),
    "reservations": ubx.FieldSpec(wire_name="reservations"),
}

_MagicLanSingleResponse_Result_StaticAddressingFields = {
    "address": ubx.FieldSpec(wire_name="address"),
    "dhcp_relay": ubx.FieldSpec(
        wire_name="dhcp_relay",
        kind="object",
        fields=_MagicLanSingleResponse_Result_StaticAddressing_DhcpRelayFields,
    ),
    "dhcp_server": ubx.FieldSpec(
        wire_name="dhcp_server",
        kind="object",
        fields=_MagicLanSingleResponse_Result_StaticAddressing_DhcpServerFields,
    ),
    "secondary_address": ubx.FieldSpec(wire_name="secondary_address"),
    "virtual_address": ubx.FieldSpec(wire_name="virtual_address"),
}

@dataclasses.dataclass
class MagicLanSingleResponseConfig:
    # The bonded interface this LAN is attached to, if any. (AI-inferred)
    bond_id: Any = None
    # mark true to use this LAN for HA probing. only works for site with HA turned on. only one LAN can be set as the ha_link.
    ha_link: Any = None
    # mark true to use this LAN for source-based breakout traffic
    is_breakout: Any = None
    # mark true to use this LAN for source-based prioritized traffic
    is_prioritized: Any = None
    # The name of the LAN interface. (AI-inferred)
    name: Any = None
    nat: Any = None
    # The physical port this LAN interface is attached to. (AI-inferred)
    physport: Any = None
    # The subnets routed through this LAN interface. (AI-inferred)
    routed_subnets: Any = None
    # If the site is not configured in high availability mode, this configuration is optional (if omitted, use DHCP). However, if in high availability mode, static_address is required along with secondary and virtual address.
    static_addressing: Any = None
    # VLAN ID. Use zero for untagged.
    vlan_tag: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    site_id: Any = None
    # path parameter, not part of the API's own resource representation
    lan_id: Any = None

@dataclasses.dataclass
class MagicLanSingleResponseAttrs:
    # The bonded interface this LAN is attached to, if any. (AI-inferred)
    bond_id: Any = None
    # mark true to use this LAN for HA probing. only works for site with HA turned on. only one LAN can be set as the ha_link.
    ha_link: Any = None
    # mark true to use this LAN for source-based breakout traffic
    is_breakout: Any = None
    # mark true to use this LAN for source-based prioritized traffic
    is_prioritized: Any = None
    # The name of the LAN interface. (AI-inferred)
    name: Any = None
    nat: Any = None
    # The physical port this LAN interface is attached to. (AI-inferred)
    physport: Any = None
    # The requested resource, present when the API call succeeds. (AI-inferred)
    result: Any = None
    # The subnets routed through this LAN interface. (AI-inferred)
    routed_subnets: Any = None
    # If the site is not configured in high availability mode, this configuration is optional (if omitted, use DHCP). However, if in high availability mode, static_address is required along with secondary and virtual address.
    static_addressing: Any = None
    # VLAN ID. Use zero for untagged.
    vlan_tag: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None
    # path parameter, not part of the API's own resource representation
    site_id: Any = None
    # path parameter, not part of the API's own resource representation
    lan_id: Any = None

MagicLanSingleResponse = ubx.ResourceBinding(
    wire_type="cloudflare_magic_lan_single_response",
    fields={
        "bond_id": ubx.FieldSpec(wire_name="bond_id"),
        "ha_link": ubx.FieldSpec(wire_name="ha_link"),
        "is_breakout": ubx.FieldSpec(wire_name="is_breakout"),
        "is_prioritized": ubx.FieldSpec(wire_name="is_prioritized"),
        "name": ubx.FieldSpec(wire_name="name"),
        "nat": ubx.FieldSpec(
            wire_name="nat",
            kind="object",
            fields=_MagicLanSingleResponse_NatFields,
        ),
        "physport": ubx.FieldSpec(wire_name="physport"),
        "routed_subnets": ubx.FieldSpec(
            wire_name="routed_subnets",
            kind="list",
            fields=_MagicLanSingleResponse_Result_RoutedSubnetsFields,
        ),
        "static_addressing": ubx.FieldSpec(
            wire_name="static_addressing",
            kind="object",
            fields=_MagicLanSingleResponse_Result_StaticAddressingFields,
        ),
        "vlan_tag": ubx.FieldSpec(wire_name="vlan_tag"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
        "site_id": ubx.FieldSpec(wire_name="site_id"),
        "lan_id": ubx.FieldSpec(wire_name="lan_id"),
    },
)
