// Code generated by `ubx sdk gen` from cloudflare_job. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Job_CustomMetadata {
  dataType?: string | Computed<string>;
  fieldName?: string | Computed<string>;
}

export interface Job_IndexMethod {
  /** Enable keyword (BM25) storage backend. */
  keyword: boolean | Computed<boolean>;
  /** Enable vector (embedding) storage backend. */
  vector: boolean | Computed<boolean>;
}

export interface Job_IndexingOptions {
  /** Tokenizer used for keyword search indexing. porter provides word-level tokenization with Porter stemming (good for natural language queries). trigram enables character-level substring matching (good for partial matches, code, identifiers). Changing this triggers a full re-index. Defaults to porter. */
  keywordTokenizer?: string | Computed<string>;
}

export interface Job_Metadata {
  createdFromAisearchWizard?: boolean | Computed<boolean>;
  workerDomain?: string | Computed<string>;
}

export interface Job_PublicEndpointParams_ChatCompletionsEndpoint {
  /** Disable chat completions endpoint for this public endpoint */
  disabled?: boolean | Computed<boolean>;
}

export interface Job_PublicEndpointParams_Mcp {
  description?: string | Computed<string>;
  /** Disable MCP endpoint for this public endpoint */
  disabled?: boolean | Computed<boolean>;
}

export interface Job_PublicEndpointParams_RateLimit {
  periodMs?: number | Computed<number>;
  requests?: number | Computed<number>;
  technique?: string | Computed<string>;
}

export interface Job_PublicEndpointParams {
  authorizedHosts?: string[] | Computed<string[]>;
  chatCompletionsEndpoint?: Job_PublicEndpointParams_ChatCompletionsEndpoint | Computed<Job_PublicEndpointParams_ChatCompletionsEndpoint>;
  /** Custom domain hostnames that alias this public endpoint. GET and create responses return the current set; on update (PUT) this field is only echoed back when supplied in the request body, otherwise it is null (omit it to leave domains unchanged). */
  customDomains?: string[] | Computed<string[]>;
  /** When false, the instance is reachable only via a registered custom domain and the default <public_endpoint_id>.search.ai.cloudflare.com host returns 404. Requires at least one custom domain. Defaults to true. public_endpoint_params is replaced wholesale on update, so resend default_domain_enabled on every update to keep the default host off — omitting it resets to true. */
  defaultDomainEnabled?: boolean | Computed<boolean>;
  enabled?: boolean | Computed<boolean>;
  mcp?: Job_PublicEndpointParams_Mcp | Computed<Job_PublicEndpointParams_Mcp>;
  rateLimit?: Job_PublicEndpointParams_RateLimit | Computed<Job_PublicEndpointParams_RateLimit>;
  searchEndpoint?: Job_PublicEndpointParams_ChatCompletionsEndpoint | Computed<Job_PublicEndpointParams_ChatCompletionsEndpoint>;
}

export interface Job_Result {
  description?: string | Computed<string>;
  endReason?: string | Computed<string>;
  endedAt?: string | Computed<string>;
  id: string | Computed<string>;
  lastSeenAt?: string | Computed<string>;
  source: string | Computed<string>;
  startedAt?: string | Computed<string>;
}

export interface Job_RetrievalOptions_BoostBy {
  direction?: string | Computed<string>;
  field?: string | Computed<string>;
}

export interface Job_RetrievalOptions {
  /** Metadata fields to boost search results by. Each entry specifies a metadata field and an optional direction. Direction defaults to 'asc' for numeric/datetime fields and 'exists' for text/boolean fields. Fields must match 'timestamp' or a defined custom_metadata field. */
  boostBy?: Job_RetrievalOptions_BoostBy[] | Computed<Job_RetrievalOptions_BoostBy[]>;
  /** Controls which documents are candidates for BM25 scoring. 'and' restricts candidates to documents containing all query terms; 'or' includes any document containing at least one term, ranked by BM25 relevance. When omitted on an update, the existing stored value is preserved; when never set, search falls back to 'and'. */
  keywordMatchMode?: string | Computed<string>;
}

export interface Job_SourceParams_WebCrawler_DiscoverOptions {
  /** Maximum link-follow depth from the seed URL. */
  depth?: number | Computed<number>;
  /** Follow links that point outside the source domain. Must stay `false` — discover crawls are restricted to the zone you own. */
  includeExternalLinks?: boolean | Computed<boolean>;
  /** Follow links to subdomains of the source host. */
  includeSubdomains?: boolean | Computed<boolean>;
  /** Maximum number of pages to crawl (1-100000). */
  limit?: number | Computed<number>;
  /** Maximum content age in seconds to accept (0–604800). */
  maxAge?: number | Computed<number>;
  /** Where the crawler looks for URLs: 'sitemaps' reads sitemap XML only, 'links' follows page links only, 'all' does both. */
  source?: string | Computed<string>;
}

export interface Job_SourceParams_WebCrawler_ParseOptions_ContentSelector {
  path?: string | Computed<string>;
  selector?: string | Computed<string>;
}

export interface Job_SourceParams_WebCrawler_ParseOptions {
  /** List of path-to-selector mappings for extracting specific content from crawled pages. Each entry pairs a URL glob pattern with a CSS selector. The first matching path wins. Only the matched HTML fragment is stored and indexed. Omit the field to disable content selection — empty arrays are rejected. */
  contentSelector?: Job_SourceParams_WebCrawler_ParseOptions_ContentSelector[] | Computed<Job_SourceParams_WebCrawler_ParseOptions_ContentSelector[]>;
  /** Up to 5 custom HTTP headers sent with each crawl request. Names must be RFC-7230 token characters (no spaces, colons, or control characters); values must be HTAB + printable ASCII (no CR/LF). */
  includeHeaders?: Record<string, string> | Computed<Record<string, string>>;
  includeImages?: boolean | Computed<boolean>;
  /** List of specific sitemap URLs to use for crawling. Only valid when parse_type is 'sitemap'. */
  specificSitemaps?: string[] | Computed<string[]>;
  useBrowserRendering?: boolean | Computed<boolean>;
}

export interface Job_SourceParams_WebCrawler {
  /** Options for parse_type 'discover', where Browser Run discovers URLs by link following and sitemaps. Ignored for 'sitemap'. */
  discoverOptions?: Job_SourceParams_WebCrawler_DiscoverOptions | Computed<Job_SourceParams_WebCrawler_DiscoverOptions>;
  parseOptions?: Job_SourceParams_WebCrawler_ParseOptions | Computed<Job_SourceParams_WebCrawler_ParseOptions>;
  /** How URLs are discovered. 'sitemap' reads XML sitemaps; 'discover' follows links recursively and requires the source to be a Verified zone on this account. */
  parseType?: string | Computed<string>;
}

export interface Job_SourceParams {
  /** List of path patterns to exclude. Uses micromatch glob syntax: * matches within a path segment, ** matches across path segments (e.g., /admin/** matches /admin/users and /admin/settings/advanced). Most accounts are limited to 10 rules; contact support to raise it. */
  excludeItems?: string[] | Computed<string[]>;
  /** List of path patterns to include. Uses micromatch glob syntax: * matches within a path segment, ** matches across path segments (e.g., /blog/** matches /blog/post and /blog/2024/post). Most accounts are limited to 10 rules; contact support to raise it. */
  includeItems?: string[] | Computed<string[]>;
  prefix?: string | Computed<string>;
  r2Jurisdiction?: string | Computed<string>;
  webCrawler?: Job_SourceParams_WebCrawler | Computed<Job_SourceParams_WebCrawler>;
}

const Job_CustomMetadataFields: FieldMap = {
  dataType: "data_type",
  fieldName: "field_name",
};

const Job_IndexMethodFields: FieldMap = {
  keyword: "keyword",
  vector: "vector",
};

const Job_IndexingOptionsFields: FieldMap = {
  keywordTokenizer: "keyword_tokenizer",
};

const Job_MetadataFields: FieldMap = {
  createdFromAisearchWizard: "created_from_aisearch_wizard",
  workerDomain: "worker_domain",
};

const Job_PublicEndpointParams_ChatCompletionsEndpointFields: FieldMap = {
  disabled: "disabled",
};

const Job_PublicEndpointParams_McpFields: FieldMap = {
  description: "description",
  disabled: "disabled",
};

const Job_PublicEndpointParams_RateLimitFields: FieldMap = {
  periodMs: "period_ms",
  requests: "requests",
  technique: "technique",
};

const Job_PublicEndpointParamsFields: FieldMap = {
  authorizedHosts: "authorized_hosts",
  chatCompletionsEndpoint: {
    wireName: "chat_completions_endpoint",
    kind: "object",
    fields: Job_PublicEndpointParams_ChatCompletionsEndpointFields,
  },
  customDomains: "custom_domains",
  defaultDomainEnabled: "default_domain_enabled",
  enabled: "enabled",
  mcp: {
    wireName: "mcp",
    kind: "object",
    fields: Job_PublicEndpointParams_McpFields,
  },
  rateLimit: {
    wireName: "rate_limit",
    kind: "object",
    fields: Job_PublicEndpointParams_RateLimitFields,
  },
  searchEndpoint: {
    wireName: "search_endpoint",
    kind: "object",
    fields: Job_PublicEndpointParams_ChatCompletionsEndpointFields,
  },
};

const Job_RetrievalOptions_BoostByFields: FieldMap = {
  direction: "direction",
  field: "field",
};

const Job_RetrievalOptionsFields: FieldMap = {
  boostBy: {
    wireName: "boost_by",
    kind: "list",
    fields: Job_RetrievalOptions_BoostByFields,
  },
  keywordMatchMode: "keyword_match_mode",
};

const Job_SourceParams_WebCrawler_DiscoverOptionsFields: FieldMap = {
  depth: "depth",
  includeExternalLinks: "include_external_links",
  includeSubdomains: "include_subdomains",
  limit: "limit",
  maxAge: "max_age",
  source: "source",
};

const Job_SourceParams_WebCrawler_ParseOptions_ContentSelectorFields: FieldMap = {
  path: "path",
  selector: "selector",
};

const Job_SourceParams_WebCrawler_ParseOptionsFields: FieldMap = {
  contentSelector: {
    wireName: "content_selector",
    kind: "list",
    fields: Job_SourceParams_WebCrawler_ParseOptions_ContentSelectorFields,
  },
  includeHeaders: "include_headers",
  includeImages: "include_images",
  specificSitemaps: "specific_sitemaps",
  useBrowserRendering: "use_browser_rendering",
};

const Job_SourceParams_WebCrawlerFields: FieldMap = {
  discoverOptions: {
    wireName: "discover_options",
    kind: "object",
    fields: Job_SourceParams_WebCrawler_DiscoverOptionsFields,
  },
  parseOptions: {
    wireName: "parse_options",
    kind: "object",
    fields: Job_SourceParams_WebCrawler_ParseOptionsFields,
  },
  parseType: "parse_type",
};

const Job_SourceParamsFields: FieldMap = {
  excludeItems: "exclude_items",
  includeItems: "include_items",
  prefix: "prefix",
  r2Jurisdiction: "r2_jurisdiction",
  webCrawler: {
    wireName: "web_crawler",
    kind: "object",
    fields: Job_SourceParams_WebCrawlerFields,
  },
};

export interface JobConfig {
  /** The AI Gateway requests through this AI Search instance are routed through. (AI-inferred) */
  aiGatewayId?: string | Computed<string>;
  /** A Workers AI model ID or an AI Gateway model ID compatible with the OpenAI Chat Completions API. An empty string uses the configured or default model. */
  aiSearchModel?: string | Computed<string>;
  /** Whether response caching is enabled for this instance. (AI-inferred) */
  cache?: boolean | Computed<boolean>;
  /** The minimum similarity score required for a cached response to be reused. (AI-inferred) */
  cacheThreshold?: string | Computed<string>;
  /** Cache entry TTL in seconds. Allowed values: 600 (10min), 1800 (30min), 3600 (1h), 7200 (2h), 21600 (6h), 43200 (12h), 86400 (24h), 172800 (48h), 259200 (72h), 518400 (6d). */
  cacheTtl?: number | Computed<number>;
  /** The chunking configuration used when indexing source content. (AI-inferred) */
  chunk?: boolean | Computed<boolean>;
  /** The number of overlapping tokens between adjacent chunks. (AI-inferred) */
  chunkOverlap?: number | Computed<number>;
  /** The maximum size, in tokens, of each indexed chunk. (AI-inferred) */
  chunkSize?: number | Computed<number>;
  /** Arbitrary custom metadata attached to the instance. (AI-inferred) */
  customMetadata?: Job_CustomMetadata[] | Computed<Job_CustomMetadata[]>;
  /** The model used to generate vector embeddings for indexed content. (AI-inferred) */
  embeddingModel?: string | Computed<string>;
  /** The method used to combine multiple retrieval signals when ranking results. (AI-inferred) */
  fusionMethod?: string | Computed<string>;
  /** Deprecated — use index_method instead. */
  hybridSearchEnabled?: boolean | Computed<boolean>;
  /** AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores. */
  id: string | Computed<string>;
  /** Controls which storage backends are used during indexing. Defaults to vector-only. */
  indexMethod?: Job_IndexMethod | Computed<Job_IndexMethod>;
  indexingOptions?: Job_IndexingOptions | Computed<Job_IndexingOptions>;
  /** The maximum number of results returned per query. (AI-inferred) */
  maxNumResults?: number | Computed<number>;
  /** Metadata associated with the instance. (AI-inferred) */
  metadata?: Job_Metadata | Computed<Job_Metadata>;
  /** The configuration for the instance's own public query endpoint. (AI-inferred) */
  publicEndpointParams?: Job_PublicEndpointParams | Computed<Job_PublicEndpointParams>;
  /** Whether a reranking pass is applied to retrieved results. (AI-inferred) */
  reranking?: boolean | Computed<boolean>;
  /** The model used to rerank retrieved results. (AI-inferred) */
  rerankingModel?: string | Computed<string>;
  retrievalOptions?: Job_RetrievalOptions | Computed<Job_RetrievalOptions>;
  /** A Workers AI model ID or an AI Gateway model ID compatible with the OpenAI Chat Completions API. An empty string uses the configured or default model. */
  rewriteModel?: string | Computed<string>;
  /** Whether incoming queries are rewritten before retrieval. (AI-inferred) */
  rewriteQuery?: boolean | Computed<boolean>;
  /** The minimum relevance score a result must reach to be returned. (AI-inferred) */
  scoreThreshold?: number | Computed<number>;
  /** The data source content is indexed from. (AI-inferred) */
  source?: string | Computed<string>;
  /** Configuration specific to the instance's own data source. (AI-inferred) */
  sourceParams?: Job_SourceParams | Computed<Job_SourceParams>;
  /** Interval between automatic syncs, in seconds. Allowed values: 900 (15min), 1800 (30min), 3600 (1h), 7200 (2h), 14400 (4h), 21600 (6h), 43200 (12h), 86400 (24h). */
  syncInterval?: number | Computed<number>;
  /** The AI Search API token used to authenticate requests for this instance. (AI-inferred) */
  tokenId?: string | Computed<string>;
  /** The type of AI Search instance. (AI-inferred) */
  type?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  jobId: string | Computed<string>;
}

export interface JobAttrs {
  /** The AI Gateway requests through this AI Search instance are routed through. (AI-inferred) */
  aiGatewayId: string;
  /** A Workers AI model ID or an AI Gateway model ID compatible with the OpenAI Chat Completions API. An empty string uses the configured or default model. */
  aiSearchModel: string;
  /** Whether response caching is enabled for this instance. (AI-inferred) */
  cache: boolean;
  /** The minimum similarity score required for a cached response to be reused. (AI-inferred) */
  cacheThreshold: string;
  /** Cache entry TTL in seconds. Allowed values: 600 (10min), 1800 (30min), 3600 (1h), 7200 (2h), 21600 (6h), 43200 (12h), 86400 (24h), 172800 (48h), 259200 (72h), 518400 (6d). */
  cacheTtl: number;
  /** The chunking configuration used when indexing source content. (AI-inferred) */
  chunk: boolean;
  /** The number of overlapping tokens between adjacent chunks. (AI-inferred) */
  chunkOverlap: number;
  /** The maximum size, in tokens, of each indexed chunk. (AI-inferred) */
  chunkSize: number;
  /** Arbitrary custom metadata attached to the instance. (AI-inferred) */
  customMetadata: Job_CustomMetadata[];
  /** The model used to generate vector embeddings for indexed content. (AI-inferred) */
  embeddingModel: string;
  /** The method used to combine multiple retrieval signals when ranking results. (AI-inferred) */
  fusionMethod: string;
  /** Deprecated — use index_method instead. */
  hybridSearchEnabled: boolean;
  /** AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores. */
  id: string;
  /** Controls which storage backends are used during indexing. Defaults to vector-only. */
  indexMethod: Job_IndexMethod;
  indexingOptions: Job_IndexingOptions;
  /** The maximum number of results returned per query. (AI-inferred) */
  maxNumResults: number;
  /** Metadata associated with the instance. (AI-inferred) */
  metadata: Job_Metadata;
  /** The configuration for the instance's own public query endpoint. (AI-inferred) */
  publicEndpointParams: Job_PublicEndpointParams;
  /** Whether a reranking pass is applied to retrieved results. (AI-inferred) */
  reranking: boolean;
  /** The model used to rerank retrieved results. (AI-inferred) */
  rerankingModel: string;
  /** The requested resource or collection of resources. (AI-inferred) */
  result: Job_Result;
  retrievalOptions: Job_RetrievalOptions;
  /** A Workers AI model ID or an AI Gateway model ID compatible with the OpenAI Chat Completions API. An empty string uses the configured or default model. */
  rewriteModel: string;
  /** Whether incoming queries are rewritten before retrieval. (AI-inferred) */
  rewriteQuery: boolean;
  /** The minimum relevance score a result must reach to be returned. (AI-inferred) */
  scoreThreshold: number;
  /** The data source content is indexed from. (AI-inferred) */
  source: string;
  /** Configuration specific to the instance's own data source. (AI-inferred) */
  sourceParams: Job_SourceParams;
  /** Whether the API call was successful. (AI-inferred) */
  success: boolean;
  /** Interval between automatic syncs, in seconds. Allowed values: 900 (15min), 1800 (30min), 3600 (1h), 7200 (2h), 14400 (4h), 21600 (6h), 43200 (12h), 86400 (24h). */
  syncInterval: number;
  /** The AI Search API token used to authenticate requests for this instance. (AI-inferred) */
  tokenId: string;
  /** The type of AI Search instance. (AI-inferred) */
  type: string;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
  /** path parameter, not part of the API's own resource representation */
  jobId: string;
}

export const Job: ResourceBinding<JobConfig, JobAttrs> = {
  wireType: "cloudflare_job",
  fields: {
    aiGatewayId: "ai_gateway_id",
    aiSearchModel: "ai_search_model",
    cache: "cache",
    cacheThreshold: "cache_threshold",
    cacheTtl: "cache_ttl",
    chunk: "chunk",
    chunkOverlap: "chunk_overlap",
    chunkSize: "chunk_size",
    customMetadata: {
      wireName: "custom_metadata",
      kind: "list",
      fields: Job_CustomMetadataFields,
    },
    embeddingModel: "embedding_model",
    fusionMethod: "fusion_method",
    hybridSearchEnabled: "hybrid_search_enabled",
    id: "id",
    indexMethod: {
      wireName: "index_method",
      kind: "object",
      fields: Job_IndexMethodFields,
    },
    indexingOptions: {
      wireName: "indexing_options",
      kind: "object",
      fields: Job_IndexingOptionsFields,
    },
    maxNumResults: "max_num_results",
    metadata: {
      wireName: "metadata",
      kind: "object",
      fields: Job_MetadataFields,
    },
    publicEndpointParams: {
      wireName: "public_endpoint_params",
      kind: "object",
      fields: Job_PublicEndpointParamsFields,
    },
    reranking: "reranking",
    rerankingModel: "reranking_model",
    retrievalOptions: {
      wireName: "retrieval_options",
      kind: "object",
      fields: Job_RetrievalOptionsFields,
    },
    rewriteModel: "rewrite_model",
    rewriteQuery: "rewrite_query",
    scoreThreshold: "score_threshold",
    source: "source",
    sourceParams: {
      wireName: "source_params",
      kind: "object",
      fields: Job_SourceParamsFields,
    },
    syncInterval: "sync_interval",
    tokenId: "token_id",
    type: "type",
    accountId: "account_id",
    jobId: "job_id",
  },
};
