// Code generated by `ubx sdk gen` from cloudflare_aegi. DO NOT EDIT.
package zonesettings

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AegiConfig struct {
}

type AegiAttrs struct {
	// Identifier.
	ZoneId any
}

var Aegi = ubx.DataSourceBinding{
	WireType: "cloudflare_aegi",
	Fields: ubx.FieldMap{
	},
}
